/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.2
 */

/**
 * This code is generated via firehose.
 * DO NOT hand edit code.  Make any changes required using the firehose repo instead
 */
package aspn23_lcm;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
/**
 * 2D direction to points.
 */
public final class measurement_direction_2d_to_points implements lcm.lcm.LCMEncodable
{
    /**
     * Non ASPN. Do not use. Extra field encoding the struct name to disambiguate LCM type fingerprint hashes.
     */
    public byte icd_measurement_direction_2d_to_points;

    /**
     * Description: Standard ASPN measurement header.
     * Units: none
     */
    public aspn23_lcm.type_header header;

    /**
     * Description: Time at which the measurement is considered to be valid.
     * Units: none
     */
    public aspn23_lcm.type_timestamp time_of_validity;

    /**
     * Description: Total number of observations.
     * Units: none
     */
    public int num_obs;

    /**
     * Description: Array of observations.
     * Units: none
     * LCM Type: aspn23_lcm.type_direction_2d_to_point[num_obs]
     */
    public aspn23_lcm.type_direction_2d_to_point obs[];

 
    public measurement_direction_2d_to_points()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x3457c13eb0198e87L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(aspn23_lcm.measurement_direction_2d_to_points.class))
            return 0L;
 
        classes.add(aspn23_lcm.measurement_direction_2d_to_points.class);
        long hash = LCM_FINGERPRINT_BASE
             + aspn23_lcm.type_header._hashRecursive(classes)
             + aspn23_lcm.type_timestamp._hashRecursive(classes)
             + aspn23_lcm.type_direction_2d_to_point._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeByte(this.icd_measurement_direction_2d_to_points); 
 
        this.header._encodeRecursive(outs); 
 
        this.time_of_validity._encodeRecursive(outs); 
 
        outs.writeInt(this.num_obs); 
 
        for (int a = 0; a < this.num_obs; a++) {
            this.obs[a]._encodeRecursive(outs); 
        }
 
    }
 
    public measurement_direction_2d_to_points(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public measurement_direction_2d_to_points(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static aspn23_lcm.measurement_direction_2d_to_points _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        aspn23_lcm.measurement_direction_2d_to_points o = new aspn23_lcm.measurement_direction_2d_to_points();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.icd_measurement_direction_2d_to_points = ins.readByte();
 
        this.header = aspn23_lcm.type_header._decodeRecursiveFactory(ins);
 
        this.time_of_validity = aspn23_lcm.type_timestamp._decodeRecursiveFactory(ins);
 
        this.num_obs = ins.readInt();
 
        this.obs = new aspn23_lcm.type_direction_2d_to_point[(int) num_obs];
        for (int a = 0; a < this.num_obs; a++) {
            this.obs[a] = aspn23_lcm.type_direction_2d_to_point._decodeRecursiveFactory(ins);
        }
 
    }
 
    public aspn23_lcm.measurement_direction_2d_to_points copy()
    {
        aspn23_lcm.measurement_direction_2d_to_points outobj = new aspn23_lcm.measurement_direction_2d_to_points();
        outobj.icd_measurement_direction_2d_to_points = this.icd_measurement_direction_2d_to_points;
 
        outobj.header = this.header.copy();
 
        outobj.time_of_validity = this.time_of_validity.copy();
 
        outobj.num_obs = this.num_obs;
 
        outobj.obs = new aspn23_lcm.type_direction_2d_to_point[(int) num_obs];
        for (int a = 0; a < this.num_obs; a++) {
            outobj.obs[a] = this.obs[a].copy();
        }
 
        return outobj;
    }
 
}

