/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.2
 */

/**
 * This code is generated via firehose.
 * DO NOT hand edit code.  Make any changes required using the firehose repo instead
 */
package aspn23_lcm;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
/**
 * Measures the apparent specific force along the sense-axis. Example sensors are an atomic
 * interferometer, quantum gravimeter, or accelerometer. The apparent specific force is corrupted by
 * inertial (Coriolis and Centrifugal) effects. The sense-axis is the sensor frame x-axis as defined in
 * mounting.
 */
public final class measurement_specific_force_1d implements lcm.lcm.LCMEncodable
{
    /**
     * Non ASPN. Do not use. Extra field encoding the struct name to disambiguate LCM type fingerprint hashes.
     */
    public byte icd_measurement_specific_force_1d;

    /**
     * Description: Standard ASPN measurement header.
     * Units: none
     */
    public aspn23_lcm.type_header header;

    /**
     * Description: Time at which the measurement is considered to be valid.
     * Units: none
     */
    public aspn23_lcm.type_timestamp time_of_validity;

    /**
     * sensor type
     */
    public byte sensor_type;

    /**
     * Description: Specific force defined in sensor_type enum.
     * Units: various
     */
    public double obs;

    /**
     * Description: Variance of the observation with units defined in sensor_type enum.
     * Units: various
     */
    public double variance;

    /**
     * Defines an optional error model for other than zero-mean, additive, white Gaussian noise (AWGN).
     */
    public byte error_model;

    /**
     * Description: Number of parameters required for the error model chosen.
     * Units: none
     */
    public int num_error_model_params;

    /**
     * Description: Error model parameters that characterize the optional error model.
     * Units: various
     * LCM Type: double[num_error_model_params]
     */
    public double error_model_params[];

    /**
     * Description: Number of integrity values.
     * Units: none
     */
    public short num_integrity;

    /**
     * Description: Measurement integrity. Includes the integrity method used and an integrity value
     * (which is to be interpreted based upon the integrity method). The intent of allowing num_integrity >
     * 1 is to report multiple integrity values based on multiple integrity methods.
     * Units: none
     * LCM Type: aspn23_lcm.type_integrity[num_integrity]
     */
    public aspn23_lcm.type_integrity integrity[];

 
    public measurement_specific_force_1d()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xbbdfce6767d9127fL;
 
    /**
     * Specific force integrated over last measurement period expressed as delta velocity in m/s.
     * Variance units are (m/s)^2. Time of validity is the end of integration period. Integration period is
     * from previous measurement to the current measurement.
     */
    public static final byte SENSOR_TYPE_INTEGRATED = (byte) 0;
    /**
     * Specific force is sampled expressed in m/s/s. Variance units are (m/s/s)^2.
     */
    public static final byte SENSOR_TYPE_SAMPLED = (byte) 1;
    /**
     * No additional error model provided (num_error_model_params = 0).
     */
    public static final byte ERROR_MODEL_NONE = (byte) 0;

    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(aspn23_lcm.measurement_specific_force_1d.class))
            return 0L;
 
        classes.add(aspn23_lcm.measurement_specific_force_1d.class);
        long hash = LCM_FINGERPRINT_BASE
             + aspn23_lcm.type_header._hashRecursive(classes)
             + aspn23_lcm.type_timestamp._hashRecursive(classes)
             + aspn23_lcm.type_integrity._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeByte(this.icd_measurement_specific_force_1d); 
 
        this.header._encodeRecursive(outs); 
 
        this.time_of_validity._encodeRecursive(outs); 
 
        outs.writeByte(this.sensor_type); 
 
        outs.writeDouble(this.obs); 
 
        outs.writeDouble(this.variance); 
 
        outs.writeByte(this.error_model); 
 
        outs.writeInt(this.num_error_model_params); 
 
        for (int a = 0; a < this.num_error_model_params; a++) {
            outs.writeDouble(this.error_model_params[a]); 
        }
 
        outs.writeShort(this.num_integrity); 
 
        for (int a = 0; a < this.num_integrity; a++) {
            this.integrity[a]._encodeRecursive(outs); 
        }
 
    }
 
    public measurement_specific_force_1d(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public measurement_specific_force_1d(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static aspn23_lcm.measurement_specific_force_1d _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        aspn23_lcm.measurement_specific_force_1d o = new aspn23_lcm.measurement_specific_force_1d();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.icd_measurement_specific_force_1d = ins.readByte();
 
        this.header = aspn23_lcm.type_header._decodeRecursiveFactory(ins);
 
        this.time_of_validity = aspn23_lcm.type_timestamp._decodeRecursiveFactory(ins);
 
        this.sensor_type = ins.readByte();
 
        this.obs = ins.readDouble();
 
        this.variance = ins.readDouble();
 
        this.error_model = ins.readByte();
 
        this.num_error_model_params = ins.readInt();
 
        this.error_model_params = new double[(int) num_error_model_params];
        for (int a = 0; a < this.num_error_model_params; a++) {
            this.error_model_params[a] = ins.readDouble();
        }
 
        this.num_integrity = ins.readShort();
 
        this.integrity = new aspn23_lcm.type_integrity[(int) num_integrity];
        for (int a = 0; a < this.num_integrity; a++) {
            this.integrity[a] = aspn23_lcm.type_integrity._decodeRecursiveFactory(ins);
        }
 
    }
 
    public aspn23_lcm.measurement_specific_force_1d copy()
    {
        aspn23_lcm.measurement_specific_force_1d outobj = new aspn23_lcm.measurement_specific_force_1d();
        outobj.icd_measurement_specific_force_1d = this.icd_measurement_specific_force_1d;
 
        outobj.header = this.header.copy();
 
        outobj.time_of_validity = this.time_of_validity.copy();
 
        outobj.sensor_type = this.sensor_type;
 
        outobj.obs = this.obs;
 
        outobj.variance = this.variance;
 
        outobj.error_model = this.error_model;
 
        outobj.num_error_model_params = this.num_error_model_params;
 
        outobj.error_model_params = new double[(int) num_error_model_params];
        if (this.num_error_model_params > 0)
            System.arraycopy(this.error_model_params, 0, outobj.error_model_params, 0, (int) this.num_error_model_params); 
        outobj.num_integrity = this.num_integrity;
 
        outobj.integrity = new aspn23_lcm.type_integrity[(int) num_integrity];
        for (int a = 0; a < this.num_integrity; a++) {
            outobj.integrity[a] = this.integrity[a].copy();
        }
 
        return outobj;
    }
 
}

