/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.2
 */

/**
 * This code is generated via firehose.
 * DO NOT hand edit code.  Make any changes required using the firehose repo instead
 */
package aspn23_lcm;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
/**
 * Inertial Measurement Unit (IMU) measurements from the device's three axis accelerometers and three
 * axis gyroscopes.
 */
public final class measurement_IMU implements lcm.lcm.LCMEncodable
{
    /**
     * Non ASPN. Do not use. Extra field encoding the struct name to disambiguate LCM type fingerprint hashes.
     */
    public byte icd_measurement_IMU;

    /**
     * Description: Standard ASPN measurement header.
     * Units: none
     */
    public aspn23_lcm.type_header header;

    /**
     * Description: Time at which the measurement is considered to be valid.
     * Units: none
     */
    public aspn23_lcm.type_timestamp time_of_validity;

    /**
     * IMU type
     */
    public byte imu_type;

    /**
     * Description: Accelerometer (specific force) measurements in 3 axes per enumerated definition.
     * Units: various
     * LCM Type: double[3]
     */
    public double meas_accel[];

    /**
     * Description: Gyroscope measurements in 3 axes per enumerated definition.
     * Units: various
     * LCM Type: double[3]
     */
    public double meas_gyro[];

    /**
     * Description: Number of integrity values.
     * Units: none
     */
    public short num_integrity;

    /**
     * Description: Measurement integrity. Includes the integrity method used and an integrity value
     * (which is to be interpreted based upon the integrity method). The intent of allowing num_integrity >
     * 1 is to report multiple integrity values based on multiple integrity methods.
     * Units: none
     * LCM Type: aspn23_lcm.type_integrity[num_integrity]
     */
    public aspn23_lcm.type_integrity integrity[];

 
    public measurement_IMU()
    {
        meas_accel = new double[3];
        meas_gyro = new double[3];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x2e4773c22e4fc6eaL;
 
    /**
     * delta velocity and delta rotation measurements from the device's three axis accelerometers and
     * three axis gyroscopes. Specific force integrated over last measurement period expressed as delta_v
     * array in m/s. Angular rate integrated over last measurement period expressed as delta_theta array in
     * radians. Time of validity is the end of integration period. Integration period is from previous
     * measurement to the current measurement.
     */
    public static final byte IMU_TYPE_INTEGRATED = (byte) 0;
    /**
     * sampled specific force and rotation rates from the device's three axis accelerometers and three
     * axis gyroscopes. Specific force is sampled expressed as an array in m/s/s. Angular rate is sampled
     * and expressed as an array in rad/s.
     */
    public static final byte IMU_TYPE_SAMPLED = (byte) 1;

    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(aspn23_lcm.measurement_IMU.class))
            return 0L;
 
        classes.add(aspn23_lcm.measurement_IMU.class);
        long hash = LCM_FINGERPRINT_BASE
             + aspn23_lcm.type_header._hashRecursive(classes)
             + aspn23_lcm.type_timestamp._hashRecursive(classes)
             + aspn23_lcm.type_integrity._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeByte(this.icd_measurement_IMU); 
 
        this.header._encodeRecursive(outs); 
 
        this.time_of_validity._encodeRecursive(outs); 
 
        outs.writeByte(this.imu_type); 
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.meas_accel[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.meas_gyro[a]); 
        }
 
        outs.writeShort(this.num_integrity); 
 
        for (int a = 0; a < this.num_integrity; a++) {
            this.integrity[a]._encodeRecursive(outs); 
        }
 
    }
 
    public measurement_IMU(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public measurement_IMU(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static aspn23_lcm.measurement_IMU _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        aspn23_lcm.measurement_IMU o = new aspn23_lcm.measurement_IMU();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.icd_measurement_IMU = ins.readByte();
 
        this.header = aspn23_lcm.type_header._decodeRecursiveFactory(ins);
 
        this.time_of_validity = aspn23_lcm.type_timestamp._decodeRecursiveFactory(ins);
 
        this.imu_type = ins.readByte();
 
        this.meas_accel = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.meas_accel[a] = ins.readDouble();
        }
 
        this.meas_gyro = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.meas_gyro[a] = ins.readDouble();
        }
 
        this.num_integrity = ins.readShort();
 
        this.integrity = new aspn23_lcm.type_integrity[(int) num_integrity];
        for (int a = 0; a < this.num_integrity; a++) {
            this.integrity[a] = aspn23_lcm.type_integrity._decodeRecursiveFactory(ins);
        }
 
    }
 
    public aspn23_lcm.measurement_IMU copy()
    {
        aspn23_lcm.measurement_IMU outobj = new aspn23_lcm.measurement_IMU();
        outobj.icd_measurement_IMU = this.icd_measurement_IMU;
 
        outobj.header = this.header.copy();
 
        outobj.time_of_validity = this.time_of_validity.copy();
 
        outobj.imu_type = this.imu_type;
 
        outobj.meas_accel = new double[(int) 3];
        System.arraycopy(this.meas_accel, 0, outobj.meas_accel, 0, 3); 
        outobj.meas_gyro = new double[(int) 3];
        System.arraycopy(this.meas_gyro, 0, outobj.meas_gyro, 0, 3); 
        outobj.num_integrity = this.num_integrity;
 
        outobj.integrity = new aspn23_lcm.type_integrity[(int) num_integrity];
        for (int a = 0; a < this.num_integrity; a++) {
            outobj.integrity[a] = this.integrity[a].copy();
        }
 
        return outobj;
    }
 
}

