/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.2
 */

/**
 * This code is generated via firehose.
 * DO NOT hand edit code.  Make any changes required using the firehose repo instead
 */
package aspn23_lcm;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
/**
 * One, two, or three dimensional position relative to a user-defined reference frame.
 */
public final class measurement_position implements lcm.lcm.LCMEncodable
{
    /**
     * Non ASPN. Do not use. Extra field encoding the struct name to disambiguate LCM type fingerprint hashes.
     */
    public byte icd_measurement_position;

    /**
     * Description: Standard ASPN measurement header.
     * Units: none
     */
    public aspn23_lcm.type_header header;

    /**
     * Description: Time at which the measurement is considered to be valid.
     * Units: none
     */
    public aspn23_lcm.type_timestamp time_of_validity;

    /**
     * Defines measurement reference.
     */
    public byte reference_frame;

    /**
     * Description: First position term as defined in enum.
     * Units: various
     */
    public double term1;

    /**
     * Description: Second position term as defined in enum.
     * Units: various
     */
    public double term2;

    /**
     * Description: Third position term as defined in enum.
     * Units: various
     */
    public double term3;

    /**
     * Description: Dimension of measurement provided.
     * Units: none
     */
    public short num_meas;

    /**
     * Description: Error covariance or variance depending on observation dimension.
     * Units: various Dimensions of covariance must be num_meas²
     * LCM Type: double[num_meas][num_meas]
     */
    public double covariance[][];

    /**
     * Defines an optional error model for other than zero-mean, additive, white Gaussian noise (AWGN).
     */
    public byte error_model;

    /**
     * Description: Number of parameters required for the error model chosen.
     * Units: none
     */
    public int num_error_model_params;

    /**
     * Description: Error model parameters that characterize the optional error model.
     * Units: various
     * LCM Type: double[num_error_model_params]
     */
    public double error_model_params[];

    /**
     * Description: Number of integrity values.
     * Units: none
     */
    public short num_integrity;

    /**
     * Description: Measurement integrity. Includes the integrity method used and an integrity value
     * (which is to be interpreted based upon the integrity method). The intent of allowing num_integrity >
     * 1 is to report multiple integrity values based on multiple integrity methods.
     * Units: none
     * LCM Type: aspn23_lcm.type_integrity[num_integrity]
     */
    public aspn23_lcm.type_integrity integrity[];

 
    public measurement_position()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xf8c23b6aecb77b7aL;
 
    /**
     * Sensor position relative to the earth-centered, inertial (ECi) frame expressed where term1,
     * term2, and term3 are the x, y, and z components of ECI position in meters, respectively. Each term
     * is optional. Error covariance is given using x-axis position error component (meters), y-axis
     * position error component (meters), and z-axis position error component (meters). In the case of
     * nulled position components, the corresponding error covariance terms are omitted. See also ECi
     * coordinate frame definition for x, y, and z definitions.
     */
    public static final byte REFERENCE_FRAME_ECI = (byte) 0;
    /**
     * Sensor position relative to the WGS-84 reference expressed using term1 as geodetic latitude in
     * radians, term2 as longitude in radians, and term3 as geodetic altitude (or height above the WGS-84
     * ellipsoid) in meters. Each term is optional. Error covariance is given using north-south position
     * error in meters (an expression of geodetic latitude error), east-west position error in meters (an
     * expression of longitude error in meters), and geodetic altitude error in meters. In the case of
     * nulled position components, the corresponding error covariance terms are omitted.
     */
    public static final byte REFERENCE_FRAME_GEODETIC = (byte) 1;
    /**
     * No additional error model provided (num_error_model_params = 0).
     */
    public static final byte ERROR_MODEL_NONE = (byte) 0;

    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(aspn23_lcm.measurement_position.class))
            return 0L;
 
        classes.add(aspn23_lcm.measurement_position.class);
        long hash = LCM_FINGERPRINT_BASE
             + aspn23_lcm.type_header._hashRecursive(classes)
             + aspn23_lcm.type_timestamp._hashRecursive(classes)
             + aspn23_lcm.type_integrity._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeByte(this.icd_measurement_position); 
 
        this.header._encodeRecursive(outs); 
 
        this.time_of_validity._encodeRecursive(outs); 
 
        outs.writeByte(this.reference_frame); 
 
        outs.writeDouble(this.term1); 
 
        outs.writeDouble(this.term2); 
 
        outs.writeDouble(this.term3); 
 
        outs.writeShort(this.num_meas); 
 
        for (int a = 0; a < this.num_meas; a++) {
            for (int b = 0; b < this.num_meas; b++) {
                outs.writeDouble(this.covariance[a][b]); 
            }
        }
 
        outs.writeByte(this.error_model); 
 
        outs.writeInt(this.num_error_model_params); 
 
        for (int a = 0; a < this.num_error_model_params; a++) {
            outs.writeDouble(this.error_model_params[a]); 
        }
 
        outs.writeShort(this.num_integrity); 
 
        for (int a = 0; a < this.num_integrity; a++) {
            this.integrity[a]._encodeRecursive(outs); 
        }
 
    }
 
    public measurement_position(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public measurement_position(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static aspn23_lcm.measurement_position _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        aspn23_lcm.measurement_position o = new aspn23_lcm.measurement_position();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.icd_measurement_position = ins.readByte();
 
        this.header = aspn23_lcm.type_header._decodeRecursiveFactory(ins);
 
        this.time_of_validity = aspn23_lcm.type_timestamp._decodeRecursiveFactory(ins);
 
        this.reference_frame = ins.readByte();
 
        this.term1 = ins.readDouble();
 
        this.term2 = ins.readDouble();
 
        this.term3 = ins.readDouble();
 
        this.num_meas = ins.readShort();
 
        this.covariance = new double[(int) num_meas][(int) num_meas];
        for (int a = 0; a < this.num_meas; a++) {
            for (int b = 0; b < this.num_meas; b++) {
                this.covariance[a][b] = ins.readDouble();
            }
        }
 
        this.error_model = ins.readByte();
 
        this.num_error_model_params = ins.readInt();
 
        this.error_model_params = new double[(int) num_error_model_params];
        for (int a = 0; a < this.num_error_model_params; a++) {
            this.error_model_params[a] = ins.readDouble();
        }
 
        this.num_integrity = ins.readShort();
 
        this.integrity = new aspn23_lcm.type_integrity[(int) num_integrity];
        for (int a = 0; a < this.num_integrity; a++) {
            this.integrity[a] = aspn23_lcm.type_integrity._decodeRecursiveFactory(ins);
        }
 
    }
 
    public aspn23_lcm.measurement_position copy()
    {
        aspn23_lcm.measurement_position outobj = new aspn23_lcm.measurement_position();
        outobj.icd_measurement_position = this.icd_measurement_position;
 
        outobj.header = this.header.copy();
 
        outobj.time_of_validity = this.time_of_validity.copy();
 
        outobj.reference_frame = this.reference_frame;
 
        outobj.term1 = this.term1;
 
        outobj.term2 = this.term2;
 
        outobj.term3 = this.term3;
 
        outobj.num_meas = this.num_meas;
 
        outobj.covariance = new double[(int) num_meas][(int) num_meas];
        for (int a = 0; a < this.num_meas; a++) {
            if (this.num_meas > 0)
                System.arraycopy(this.covariance[a], 0, outobj.covariance[a], 0, (int) this.num_meas);        }
 
        outobj.error_model = this.error_model;
 
        outobj.num_error_model_params = this.num_error_model_params;
 
        outobj.error_model_params = new double[(int) num_error_model_params];
        if (this.num_error_model_params > 0)
            System.arraycopy(this.error_model_params, 0, outobj.error_model_params, 0, (int) this.num_error_model_params); 
        outobj.num_integrity = this.num_integrity;
 
        outobj.integrity = new aspn23_lcm.type_integrity[(int) num_integrity];
        for (int a = 0; a < this.num_integrity; a++) {
            outobj.integrity[a] = this.integrity[a].copy();
        }
 
        return outobj;
    }
 
}

