/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.2
 */

/**
 * This code is generated via firehose.
 * DO NOT hand edit code.  Make any changes required using the firehose repo instead
 */
package aspn23_lcm;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
/**
 * LNAV Ephemeris describing GPS satellite locations. Definitions and usage are covered in
 * ICD-GPS-200L, Section 20.3.3.4 and following.
 */
public final class metadata_GPS_Lnav_ephemeris implements lcm.lcm.LCMEncodable
{
    /**
     * Non ASPN. Do not use. Extra field encoding the struct name to disambiguate LCM type fingerprint hashes.
     */
    public byte icd_metadata_GPS_Lnav_ephemeris;

    /**
     * Description: Standard ASPN metadata header.
     * Units: none
     */
    public aspn23_lcm.type_metadataheader info;

    /**
     * Description: Time at which the measurement is considered to be valid.
     * Units: none
     */
    public aspn23_lcm.type_timestamp time_of_validity;

    /**
     * Description: Full GPS week number calculated from the Modulo 1024 WN in Subframe 1 and the
     * number of GPS week rollovers
     * Units: weeks
     */
    public int week_number;

    /**
     * Description: Satellite PRN number.
     * Units: none
     */
    public int prn;

    /**
     * Description: GNSS broadcast parameters required to calculate sv clock corrections.
     * Units: none
     */
    public aspn23_lcm.type_satnav_clock clock;

    /**
     * Description: Keplerian orbit parameters required to calculate satellite position.
     * Units: none
     */
    public aspn23_lcm.type_kepler_orbit orbit;

    /**
     * Description: Group delay differential between L1 and L2.
     * Units: s
     */
    public double t_gd;

    /**
     * Description: Issue of Data Clock. 10 bit value from Subframe 1
     * Units: none
     */
    public int iodc;

    /**
     * Description: Issue of Data Ephemeris. 8 bits repeated in Subframe 2 and Subframe 3. Should match
     * the 8 LSBs of the IODC.
     * Units: none
     */
    public short iode;

 
    public metadata_GPS_Lnav_ephemeris()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x64b0d0ca394139a4L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(aspn23_lcm.metadata_GPS_Lnav_ephemeris.class))
            return 0L;
 
        classes.add(aspn23_lcm.metadata_GPS_Lnav_ephemeris.class);
        long hash = LCM_FINGERPRINT_BASE
             + aspn23_lcm.type_metadataheader._hashRecursive(classes)
             + aspn23_lcm.type_timestamp._hashRecursive(classes)
             + aspn23_lcm.type_satnav_clock._hashRecursive(classes)
             + aspn23_lcm.type_kepler_orbit._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeByte(this.icd_metadata_GPS_Lnav_ephemeris); 
 
        this.info._encodeRecursive(outs); 
 
        this.time_of_validity._encodeRecursive(outs); 
 
        outs.writeInt(this.week_number); 
 
        outs.writeInt(this.prn); 
 
        this.clock._encodeRecursive(outs); 
 
        this.orbit._encodeRecursive(outs); 
 
        outs.writeDouble(this.t_gd); 
 
        outs.writeInt(this.iodc); 
 
        outs.writeShort(this.iode); 
 
    }
 
    public metadata_GPS_Lnav_ephemeris(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public metadata_GPS_Lnav_ephemeris(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static aspn23_lcm.metadata_GPS_Lnav_ephemeris _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        aspn23_lcm.metadata_GPS_Lnav_ephemeris o = new aspn23_lcm.metadata_GPS_Lnav_ephemeris();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.icd_metadata_GPS_Lnav_ephemeris = ins.readByte();
 
        this.info = aspn23_lcm.type_metadataheader._decodeRecursiveFactory(ins);
 
        this.time_of_validity = aspn23_lcm.type_timestamp._decodeRecursiveFactory(ins);
 
        this.week_number = ins.readInt();
 
        this.prn = ins.readInt();
 
        this.clock = aspn23_lcm.type_satnav_clock._decodeRecursiveFactory(ins);
 
        this.orbit = aspn23_lcm.type_kepler_orbit._decodeRecursiveFactory(ins);
 
        this.t_gd = ins.readDouble();
 
        this.iodc = ins.readInt();
 
        this.iode = ins.readShort();
 
    }
 
    public aspn23_lcm.metadata_GPS_Lnav_ephemeris copy()
    {
        aspn23_lcm.metadata_GPS_Lnav_ephemeris outobj = new aspn23_lcm.metadata_GPS_Lnav_ephemeris();
        outobj.icd_metadata_GPS_Lnav_ephemeris = this.icd_metadata_GPS_Lnav_ephemeris;
 
        outobj.info = this.info.copy();
 
        outobj.time_of_validity = this.time_of_validity.copy();
 
        outobj.week_number = this.week_number;
 
        outobj.prn = this.prn;
 
        outobj.clock = this.clock.copy();
 
        outobj.orbit = this.orbit.copy();
 
        outobj.t_gd = this.t_gd;
 
        outobj.iodc = this.iodc;
 
        outobj.iode = this.iode;
 
        return outobj;
    }
 
}

