/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.2
 */

/**
 * This code is generated via firehose.
 * DO NOT hand edit code.  Make any changes required using the firehose repo instead
 */
package aspn23_lcm;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
/**
 * Describes the translational and angular offset between the sensor frame and the platform body frame.
 * Platform body frame is defined using axes in forward, right, and down convention, and the origin is
 * system defined. This type also contains the uncertainty associated with the translational and
 * angular offset.
 */
public final class type_mounting implements lcm.lcm.LCMEncodable
{
    /**
     * Non ASPN. Do not use. Extra field encoding the struct name to disambiguate LCM type fingerprint hashes.
     */
    public byte icd_type_mounting;

    /**
     * Description: 3x1 lever arm vector describing the sensor position in the platform body frame.
     * Units: m
     * LCM Type: double[3]
     */
    public double lever_arm[];

    /**
     * Description: 3x1 lever arm uncertainty vector as standard deviations in the platform body frame.
     * Units: m
     * LCM Type: double[3]
     */
    public double lever_arm_sigma[];

    /**
     * Description: Four element quaternion, q = [a, b, c, d], where a = cos(phi/2), b =
     * (phi_x/phi)*sin(phi/2), c = (phi_y/phi)*sin(phi/2), and d = (phi_z/phi)*sin(phi/2). In this
     * description, the vector [phi_x, phi_y, phi_z] represents the rotation vector that describes the
     * frame rotation to be applied to the "reference" frame (ECI, ECEF, or NED) to rotate it into the axes
     * that describe the measured attitude, and the value phi is the magnitude of the [phi_x, phi_y, phi_z]
     * vector.
     * Orientation is optional in the sense that orientation shall be specified except in the case that
     * orientation is meaningless, for example, in the case of an RF antenna mounting.
     * See "conventions" documentation for more detailed information.
     * Units: none
     * LCM Type: double[4]
     */
    public double orientation_quaternion[];

    /**
     * Description: Tilt error covariance matrix. This matrix represents the uncertainty in the "tilt
     * errors" that represent the additional rotation to be applied to the provided attitude quaternion in
     * order to convert it to the true attitude with no errors. By convention, these "tilt errors" are
     * expressed in the reference frame (ECI, ECEF, or NED).
     * Tilt error covariance is optional only because orientation itself is optional. Orientation error
     * covariance shall be provided if orientation is provided.
     * See "conventions" documentation for more detailed information.
     * Units: rad^2
     * LCM Type: double[3][3]
     */
    public double orientation_tilt_error_covariance[][];

 
    public type_mounting()
    {
        lever_arm = new double[3];
        lever_arm_sigma = new double[3];
        orientation_quaternion = new double[4];
        orientation_tilt_error_covariance = new double[3][3];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xd0f86db27c5effbbL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(aspn23_lcm.type_mounting.class))
            return 0L;
 
        classes.add(aspn23_lcm.type_mounting.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeByte(this.icd_type_mounting); 
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.lever_arm[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.lever_arm_sigma[a]); 
        }
 
        for (int a = 0; a < 4; a++) {
            outs.writeDouble(this.orientation_quaternion[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            for (int b = 0; b < 3; b++) {
                outs.writeDouble(this.orientation_tilt_error_covariance[a][b]); 
            }
        }
 
    }
 
    public type_mounting(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public type_mounting(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static aspn23_lcm.type_mounting _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        aspn23_lcm.type_mounting o = new aspn23_lcm.type_mounting();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.icd_type_mounting = ins.readByte();
 
        this.lever_arm = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.lever_arm[a] = ins.readDouble();
        }
 
        this.lever_arm_sigma = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.lever_arm_sigma[a] = ins.readDouble();
        }
 
        this.orientation_quaternion = new double[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.orientation_quaternion[a] = ins.readDouble();
        }
 
        this.orientation_tilt_error_covariance = new double[(int) 3][(int) 3];
        for (int a = 0; a < 3; a++) {
            for (int b = 0; b < 3; b++) {
                this.orientation_tilt_error_covariance[a][b] = ins.readDouble();
            }
        }
 
    }
 
    public aspn23_lcm.type_mounting copy()
    {
        aspn23_lcm.type_mounting outobj = new aspn23_lcm.type_mounting();
        outobj.icd_type_mounting = this.icd_type_mounting;
 
        outobj.lever_arm = new double[(int) 3];
        System.arraycopy(this.lever_arm, 0, outobj.lever_arm, 0, 3); 
        outobj.lever_arm_sigma = new double[(int) 3];
        System.arraycopy(this.lever_arm_sigma, 0, outobj.lever_arm_sigma, 0, 3); 
        outobj.orientation_quaternion = new double[(int) 4];
        System.arraycopy(this.orientation_quaternion, 0, outobj.orientation_quaternion, 0, 4); 
        outobj.orientation_tilt_error_covariance = new double[(int) 3][(int) 3];
        for (int a = 0; a < 3; a++) {
            System.arraycopy(this.orientation_tilt_error_covariance[a], 0, outobj.orientation_tilt_error_covariance[a], 0, 3);        }
 
        return outobj;
    }
 
}

