/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.2
 */

/**
 * This code is generated via firehose.
 * DO NOT hand edit code.  Make any changes required using the firehose repo instead
 */
package aspn23_lcm;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
/**
 * Satellite system time
 */
public final class type_satnav_time implements lcm.lcm.LCMEncodable
{
    /**
     * Non ASPN. Do not use. Extra field encoding the struct name to disambiguate LCM type fingerprint hashes.
     */
    public byte icd_type_satnav_time;

    /**
     * Description: Full Week number since zero epoch at which the data provided in this message is
     * valid, expressed in time system defined by time_reference enum (below).
     * Units: weeks
     */
    public int week_number;

    /**
     * Description: Seconds since start of current week at which the data provided in this message is
     * valid, expressed in time system defined by time_reference enum (below).
     * Units: seconds
     */
    public double seconds_of_week;

    /**
     * Reference time system used to express the data in this message. In a multi-GNSS receiver
     * (GPS/GLONASS/Galileo/QZSS/BeiDou) all pseudorange observations must refer to one receiver clock
     * only. The receiver clock time of the measurement is the receiver clock time of the received signals.
     * It is identical for the phase and range measurements and is identical for all satellites observed in
     * a given epoch.
     */
    public byte time_reference;

 
    public type_satnav_time()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x77ce62b549494fa1L;
 
    /**
     * GPS system time.
     */
    public static final byte TIME_REFERENCE_TIME_GPS = (byte) 0;
    /**
     * Galileo system time.
     */
    public static final byte TIME_REFERENCE_TIME_GALILEO = (byte) 1;
    /**
     * BeiDou system time.
     */
    public static final byte TIME_REFERENCE_TIME_BEIDOU = (byte) 2;
    /**
     * GLONASS system time.
     */
    public static final byte TIME_REFERENCE_TIME_GLONASS = (byte) 3;

    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(aspn23_lcm.type_satnav_time.class))
            return 0L;
 
        classes.add(aspn23_lcm.type_satnav_time.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeByte(this.icd_type_satnav_time); 
 
        outs.writeInt(this.week_number); 
 
        outs.writeDouble(this.seconds_of_week); 
 
        outs.writeByte(this.time_reference); 
 
    }
 
    public type_satnav_time(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public type_satnav_time(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static aspn23_lcm.type_satnav_time _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        aspn23_lcm.type_satnav_time o = new aspn23_lcm.type_satnav_time();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.icd_type_satnav_time = ins.readByte();
 
        this.week_number = ins.readInt();
 
        this.seconds_of_week = ins.readDouble();
 
        this.time_reference = ins.readByte();
 
    }
 
    public aspn23_lcm.type_satnav_time copy()
    {
        aspn23_lcm.type_satnav_time outobj = new aspn23_lcm.type_satnav_time();
        outobj.icd_type_satnav_time = this.icd_type_satnav_time;
 
        outobj.week_number = this.week_number;
 
        outobj.seconds_of_week = this.seconds_of_week;
 
        outobj.time_reference = this.time_reference;
 
        return outobj;
    }
 
}

