/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.2
 */

/**
 * This code is generated via firehose.
 * DO NOT hand edit code.  Make any changes required using the firehose repo instead
 */
package aspn23_lcm;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
/**
 * Header for each ASPN measurement
 */
public final class type_header implements lcm.lcm.LCMEncodable
{
    /**
     * Non ASPN. Do not use. Extra field encoding the struct name to disambiguate LCM type fingerprint hashes.
     */
    public byte icd_type_header;

    /**
     * Description: Unique identifier that identifies the device or application vendor. Vendor ID is
     * user-selected, inspired by your company name to mitigate conflicts with other users. Vendor IDs 0x23
     * 00 00 00 through 0x23 FF FF FF inclusive are reserved and shall not be chosen as user-selected
     * vendor IDs.
     * Units: none
     */
    public long vendor_id;

    /**
     * Description: Unique identifier that identifies the sensor or device type as assigned by the
     * vendor. Device_ids are unique within a given vendor_id.
     * Units: none
     */
    public long device_id;

    /**
     * Description: Unique identifier that provides additional context to define a logical stream of
     * data from the sensor or device as assigned by the vendor. This identifier allows multiple
     * measurements of the same type to be provided by a device. Context_ids are unique within a given
     * vendor_id and device_id.
     * Units: none
     */
    public long context_id;

    /**
     * Description: Unique identifier for a specific message within a data stream as defined by a
     * vendor_id, device_id, and context_id. Sequential messages from each data source (identified by
     * vendor_id, device_id, and context_id) shall increment by exactly 1 and rollover to 0 after an
     * overflow.
     * Units: none
     */
    public int sequence_id;

 
    public type_header()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xfdde0d3af6218fb2L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(aspn23_lcm.type_header.class))
            return 0L;
 
        classes.add(aspn23_lcm.type_header.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeByte(this.icd_type_header); 
 
        outs.writeLong(this.vendor_id); 
 
        outs.writeLong(this.device_id); 
 
        outs.writeLong(this.context_id); 
 
        outs.writeInt(this.sequence_id); 
 
    }
 
    public type_header(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public type_header(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static aspn23_lcm.type_header _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        aspn23_lcm.type_header o = new aspn23_lcm.type_header();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.icd_type_header = ins.readByte();
 
        this.vendor_id = ins.readLong();
 
        this.device_id = ins.readLong();
 
        this.context_id = ins.readLong();
 
        this.sequence_id = ins.readInt();
 
    }
 
    public aspn23_lcm.type_header copy()
    {
        aspn23_lcm.type_header outobj = new aspn23_lcm.type_header();
        outobj.icd_type_header = this.icd_type_header;
 
        outobj.vendor_id = this.vendor_id;
 
        outobj.device_id = this.device_id;
 
        outobj.context_id = this.context_id;
 
        outobj.sequence_id = this.sequence_id;
 
        return outobj;
    }
 
}

