/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.2
 */

/**
 * This code is generated via firehose.
 * DO NOT hand edit code.  Make any changes required using the firehose repo instead
 */
package aspn23_lcm;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
/**
 * satnav broadcast parameters required to calculate sv clock corrections
 */
public final class type_satnav_clock implements lcm.lcm.LCMEncodable
{
    /**
     * Non ASPN. Do not use. Extra field encoding the struct name to disambiguate LCM type fingerprint hashes.
     */
    public byte icd_type_satnav_clock;

    /**
     * Description: Clock reference time.
     * Units: s
     */
    public double t_oc;

    /**
     * Description: Satellite clock bias.
     * Units: s
     */
    public double af_0;

    /**
     * Description: Satellite clock drift.
     * Units: s/s
     */
    public double af_1;

    /**
     * Description: Satellite clock drift rate.
     * Units: s/s^2
     */
    public double af_2;

 
    public type_satnav_clock()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xdf69b6d398318d75L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(aspn23_lcm.type_satnav_clock.class))
            return 0L;
 
        classes.add(aspn23_lcm.type_satnav_clock.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeByte(this.icd_type_satnav_clock); 
 
        outs.writeDouble(this.t_oc); 
 
        outs.writeDouble(this.af_0); 
 
        outs.writeDouble(this.af_1); 
 
        outs.writeDouble(this.af_2); 
 
    }
 
    public type_satnav_clock(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public type_satnav_clock(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static aspn23_lcm.type_satnav_clock _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        aspn23_lcm.type_satnav_clock o = new aspn23_lcm.type_satnav_clock();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.icd_type_satnav_clock = ins.readByte();
 
        this.t_oc = ins.readDouble();
 
        this.af_0 = ins.readDouble();
 
        this.af_1 = ins.readDouble();
 
        this.af_2 = ins.readDouble();
 
    }
 
    public aspn23_lcm.type_satnav_clock copy()
    {
        aspn23_lcm.type_satnav_clock outobj = new aspn23_lcm.type_satnav_clock();
        outobj.icd_type_satnav_clock = this.icd_type_satnav_clock;
 
        outobj.t_oc = this.t_oc;
 
        outobj.af_0 = this.af_0;
 
        outobj.af_1 = this.af_1;
 
        outobj.af_2 = this.af_2;
 
        return outobj;
    }
 
}

