
# This code is generated via firehose.
# DO NOT hand edit code.  Make any changes required using the firehose repo instead

# Keplerian orbit parameters required to calculate satellite position

# Description: Mean anomaly at reference time.
# Units: rad
float64 m_0

# Description: Mean motion difference from computed value.
# Units: rad/s
float64 delta_n

# Description: Eccentricity.
# Units: none
float64 e

# Description: Square root of semi-major axis.
# Units: sqrt(m)
float64 sqrt_a

# Description: Longitude of ascending node of orbit plane at weekly epoch
# Units: rad
float64 omega_0

# Description: Inclination angle at reference time.
# Units: rad
float64 i_0

# Description: Rate of change of inclination angle.
# Units: rad
float64 i_dot

# Description: Argument of perigee.
# Units: rad
float64 omega

# Description: Rate of right ascension.
# Units: rad/s
float64 omega_dot

# Description: Amplitude of cosine harmonic correction terms to the argument of latitude.
# Units: rad
float64 c_uc

# Description: Amplitude of sine harmonic correction terms to the argument of latitude.
# Units: rad
float64 c_us

# Description: Amplitude of cosine harmonic correction terms to the orbit radius.
# Units: m
float64 c_rc

# Description: Amplitude of sine harmonic correction terms to the orbit radius.
# Units: m
float64 c_rs

# Description: Amplitude of cosine harmonic correction terms to the angle of inclination.
# Units: rad
float64 c_ic

# Description: Amplitude of sine harmonic correction terms to the angle of inclination.
# Units: rad
float64 c_is

# Description: Ephemeris reference time.
# Units: s
float64 t_oe
