
// This code is generated via firehose.
// DO NOT hand edit code.  Make any changes required using the firehose repo instead

#ifndef __ASPN23_DDS_MEASUREMENTMAGNETICFIELD__
#define __ASPN23_DDS_MEASUREMENTMAGNETICFIELD__

#include <aspn23_dds/TypeHeader.idl>
#include <aspn23_dds/TypeIntegrity.idl>
#include <aspn23_dds/TypeTimestamp.idl>

module aspn23_dds {
    enum MeasurementMagneticFieldErrorModelValue {
        ASPN23_MEASUREMENT_MAGNETIC_FIELD_ERROR_MODEL_NONE
    };
    
    @topic
    struct MeasurementMagneticField {
        aspn23_dds::TypeHeader header;
        aspn23_dds::TypeTimestamp time_of_validity;
        uint8 num_meas;
        @optional double x_field_strength;
        @optional double y_field_strength;
        @optional double z_field_strength;
        sequence<double> covariance;
        MeasurementMagneticFieldErrorModelValue error_model;
        uint16 num_error_model_params;
        sequence<double> error_model_params;
        uint8 num_integrity;
        sequence<aspn23_dds::TypeIntegrity> integrity;
    };
};

#endif
