
// This code is generated via firehose.
// DO NOT hand edit code.  Make any changes required using the firehose repo instead

#ifndef __ASPN23_DDS_MEASUREMENTTEMPERATURE__
#define __ASPN23_DDS_MEASUREMENTTEMPERATURE__

#include <aspn23_dds/TypeHeader.idl>
#include <aspn23_dds/TypeIntegrity.idl>
#include <aspn23_dds/TypeTimestamp.idl>

module aspn23_dds {
    enum MeasurementTemperatureErrorModelValue {
        ASPN23_MEASUREMENT_TEMPERATURE_ERROR_MODEL_NONE
    };
    
    @topic
    struct MeasurementTemperature {
        aspn23_dds::TypeHeader header;
        aspn23_dds::TypeTimestamp time_of_validity;
        double temperature;
        double variance;
        MeasurementTemperatureErrorModelValue error_model;
        uint16 num_error_model_params;
        sequence<double> error_model_params;
        uint8 num_integrity;
        sequence<aspn23_dds::TypeIntegrity> integrity;
    };
};

#endif
