
// This code is generated via firehose.
// DO NOT hand edit code.  Make any changes required using the firehose repo instead

#ifndef __ASPN23_DDS_METADATAGPSCNAVEPHEMERIS__
#define __ASPN23_DDS_METADATAGPSCNAVEPHEMERIS__

#include <aspn23_dds/TypeKeplerOrbit.idl>
#include <aspn23_dds/TypeMetadataheader.idl>
#include <aspn23_dds/TypeSatnavClock.idl>
#include <aspn23_dds/TypeTimestamp.idl>

module aspn23_dds {
    
    @topic
    struct MetadataGpsCnavEphemeris {
        aspn23_dds::TypeMetadataheader info;
        aspn23_dds::TypeTimestamp time_of_validity;
        uint16 week_number;
        int32 prn;
        aspn23_dds::TypeSatnavClock clock;
        aspn23_dds::TypeKeplerOrbit orbit;
        double t_gd;
        uint16 iodc;
        uint8 iode;
        double isc_l1_ca;
        double isc_l2_c;
        double isc_l5_i5;
        double isc_l5_q5;
        double delta_a_0;
        double a_dot;
    };
};

#endif
