
// This code is generated via firehose.
// DO NOT hand edit code.  Make any changes required using the firehose repo instead

#ifndef __ASPN23_DDS_TYPETIMESTAMP__
#define __ASPN23_DDS_TYPETIMESTAMP__

module aspn23_dds {
    
    @topic
    struct TypeTimestamp {
        int64 elapsed_nsec;
    };
};

#endif
