
# This code is generated via firehose.
# DO NOT hand edit code.  Make any changes required using the firehose repo instead

# satnav broadcast parameters required to calculate sv clock corrections

# Description: Clock reference time.
# Units: s
float64 t_oc

# Description: Satellite clock bias.
# Units: s
float64 af_0

# Description: Satellite clock drift.
# Units: s/s
float64 af_1

# Description: Satellite clock drift rate.
# Units: s/s^2
float64 af_2
