
/*
 * This code is generated via firehose.
 * DO NOT hand edit code.  Make any changes required using the firehose repo instead.
 */

#pragma once

#ifdef __cplusplus
extern "C" {
#endif

#include "types.h"
typedef enum Aspn23MessageType AspnMessageType;
#define aspn_free aspn23_free
#define aspn_runtime_type_get_name aspn23_runtime_type_get_name

#include "utils.h"
#define aspn_is_core_message aspn23_is_core_message
#define aspn_get_time aspn23_get_time
#define aspn_set_time aspn23_set_time
#define aspn_copy_message aspn23_copy_message

#include "messages_and_types.h"

typedef Aspn23TypeDirection2DToPoint AspnTypeDirection2DToPoint;
#define aspn_type_direction_2d_to_point_new aspn23_type_direction_2d_to_point_new
#define aspn_type_direction_2d_to_point_copy aspn23_type_direction_2d_to_point_copy
#define aspn_type_direction_2d_to_point_free aspn23_type_direction_2d_to_point_free
#define aspn_type_direction_2d_to_point_free_members aspn23_type_direction_2d_to_point_free_members
#define ASPN_TYPE_DIRECTION_2D_TO_POINT_REFERENCE_NE_TO \
	ASPN23_TYPE_DIRECTION_2D_TO_POINT_REFERENCE_NE_TO
#define ASPN_TYPE_DIRECTION_2D_TO_POINT_REFERENCE_NE_FROM \
	ASPN23_TYPE_DIRECTION_2D_TO_POINT_REFERENCE_NE_FROM
#define ASPN_TYPE_DIRECTION_2D_TO_POINT_REFERENCE_ELEVATION \
	ASPN23_TYPE_DIRECTION_2D_TO_POINT_REFERENCE_ELEVATION
#define ASPN_TYPE_DIRECTION_2D_TO_POINT_REFERENCE_SENSOR \
	ASPN23_TYPE_DIRECTION_2D_TO_POINT_REFERENCE_SENSOR
#define ASPN_TYPE_DIRECTION_2D_TO_POINT_ERROR_MODEL_NONE \
	ASPN23_TYPE_DIRECTION_2D_TO_POINT_ERROR_MODEL_NONE
typedef enum Aspn23TypeDirection2DToPointErrorModel AspnTypeDirection2DToPointErrorModel;
typedef enum Aspn23TypeDirection2DToPointReference AspnTypeDirection2DToPointReference;

typedef Aspn23TypeDirection3DToPoint AspnTypeDirection3DToPoint;
#define aspn_type_direction_3d_to_point_new aspn23_type_direction_3d_to_point_new
#define aspn_type_direction_3d_to_point_copy aspn23_type_direction_3d_to_point_copy
#define aspn_type_direction_3d_to_point_free aspn23_type_direction_3d_to_point_free
#define aspn_type_direction_3d_to_point_free_members aspn23_type_direction_3d_to_point_free_members
#define ASPN_TYPE_DIRECTION_3D_TO_POINT_REFERENCE_FRAME_AZ_EL \
	ASPN23_TYPE_DIRECTION_3D_TO_POINT_REFERENCE_FRAME_AZ_EL
#define ASPN_TYPE_DIRECTION_3D_TO_POINT_REFERENCE_FRAME_PIXEL \
	ASPN23_TYPE_DIRECTION_3D_TO_POINT_REFERENCE_FRAME_PIXEL
#define ASPN_TYPE_DIRECTION_3D_TO_POINT_REFERENCE_FRAME_NORMALIZED_IMAGE \
	ASPN23_TYPE_DIRECTION_3D_TO_POINT_REFERENCE_FRAME_NORMALIZED_IMAGE
#define ASPN_TYPE_DIRECTION_3D_TO_POINT_REFERENCE_FRAME_SINE_SPACE \
	ASPN23_TYPE_DIRECTION_3D_TO_POINT_REFERENCE_FRAME_SINE_SPACE
#define ASPN_TYPE_DIRECTION_3D_TO_POINT_ERROR_MODEL_NONE \
	ASPN23_TYPE_DIRECTION_3D_TO_POINT_ERROR_MODEL_NONE
typedef enum Aspn23TypeDirection3DToPointErrorModel AspnTypeDirection3DToPointErrorModel;
typedef enum Aspn23TypeDirection3DToPointReferenceFrame AspnTypeDirection3DToPointReferenceFrame;

typedef Aspn23TypeHeader AspnTypeHeader;
#define aspn_type_header_new aspn23_type_header_new
#define aspn_type_header_copy aspn23_type_header_copy
#define aspn_type_header_free aspn23_type_header_free
#define aspn_type_header_free_members aspn23_type_header_free_members

typedef Aspn23TypeImageFeature AspnTypeImageFeature;
#define aspn_type_image_feature_new aspn23_type_image_feature_new
#define aspn_type_image_feature_copy aspn23_type_image_feature_copy
#define aspn_type_image_feature_free aspn23_type_image_feature_free
#define aspn_type_image_feature_free_members aspn23_type_image_feature_free_members

typedef Aspn23TypeIntegrity AspnTypeIntegrity;
#define aspn_type_integrity_new aspn23_type_integrity_new
#define aspn_type_integrity_copy aspn23_type_integrity_copy
#define aspn_type_integrity_free aspn23_type_integrity_free
#define aspn_type_integrity_free_members aspn23_type_integrity_free_members

typedef Aspn23TypeKeplerOrbit AspnTypeKeplerOrbit;
#define aspn_type_kepler_orbit_new aspn23_type_kepler_orbit_new
#define aspn_type_kepler_orbit_copy aspn23_type_kepler_orbit_copy
#define aspn_type_kepler_orbit_free aspn23_type_kepler_orbit_free
#define aspn_type_kepler_orbit_free_members aspn23_type_kepler_orbit_free_members

typedef Aspn23TypeMetadataheader AspnTypeMetadataheader;
#define aspn_type_metadataheader_new aspn23_type_metadataheader_new
#define aspn_type_metadataheader_copy aspn23_type_metadataheader_copy
#define aspn_type_metadataheader_free aspn23_type_metadataheader_free
#define aspn_type_metadataheader_free_members aspn23_type_metadataheader_free_members

typedef Aspn23TypeMounting AspnTypeMounting;
#define aspn_type_mounting_new aspn23_type_mounting_new
#define aspn_type_mounting_copy aspn23_type_mounting_copy
#define aspn_type_mounting_free aspn23_type_mounting_free
#define aspn_type_mounting_free_members aspn23_type_mounting_free_members

typedef Aspn23TypeRemotePoint AspnTypeRemotePoint;
#define aspn_type_remote_point_new aspn23_type_remote_point_new
#define aspn_type_remote_point_copy aspn23_type_remote_point_copy
#define aspn_type_remote_point_free aspn23_type_remote_point_free
#define aspn_type_remote_point_free_members aspn23_type_remote_point_free_members
#define ASPN_TYPE_REMOTE_POINT_POSITION_REFERENCE_FRAME_NONE \
	ASPN23_TYPE_REMOTE_POINT_POSITION_REFERENCE_FRAME_NONE
#define ASPN_TYPE_REMOTE_POINT_POSITION_REFERENCE_FRAME_GEODETIC \
	ASPN23_TYPE_REMOTE_POINT_POSITION_REFERENCE_FRAME_GEODETIC
typedef enum Aspn23TypeRemotePointPositionReferenceFrame AspnTypeRemotePointPositionReferenceFrame;

typedef Aspn23TypeSatnavClock AspnTypeSatnavClock;
#define aspn_type_satnav_clock_new aspn23_type_satnav_clock_new
#define aspn_type_satnav_clock_copy aspn23_type_satnav_clock_copy
#define aspn_type_satnav_clock_free aspn23_type_satnav_clock_free
#define aspn_type_satnav_clock_free_members aspn23_type_satnav_clock_free_members

typedef Aspn23TypeSatnavObs AspnTypeSatnavObs;
#define aspn_type_satnav_obs_new aspn23_type_satnav_obs_new
#define aspn_type_satnav_obs_copy aspn23_type_satnav_obs_copy
#define aspn_type_satnav_obs_free aspn23_type_satnav_obs_free
#define aspn_type_satnav_obs_free_members aspn23_type_satnav_obs_free_members
#define ASPN_TYPE_SATNAV_OBS_PSEUDORANGE_RATE_TYPE_PSR_RATE_DOPPLER \
	ASPN23_TYPE_SATNAV_OBS_PSEUDORANGE_RATE_TYPE_PSR_RATE_DOPPLER
#define ASPN_TYPE_SATNAV_OBS_PSEUDORANGE_RATE_TYPE_PSR_RATE_DELTA_RANGE \
	ASPN23_TYPE_SATNAV_OBS_PSEUDORANGE_RATE_TYPE_PSR_RATE_DELTA_RANGE
#define ASPN_TYPE_SATNAV_OBS_IONO_CORRECTION_SOURCE_UNKNOWN \
	ASPN23_TYPE_SATNAV_OBS_IONO_CORRECTION_SOURCE_UNKNOWN
#define ASPN_TYPE_SATNAV_OBS_IONO_CORRECTION_SOURCE_MODELED \
	ASPN23_TYPE_SATNAV_OBS_IONO_CORRECTION_SOURCE_MODELED
#define ASPN_TYPE_SATNAV_OBS_IONO_CORRECTION_SOURCE_MEASURED \
	ASPN23_TYPE_SATNAV_OBS_IONO_CORRECTION_SOURCE_MEASURED
typedef enum Aspn23TypeSatnavObsIonoCorrectionSource AspnTypeSatnavObsIonoCorrectionSource;
typedef enum Aspn23TypeSatnavObsPseudorangeRateType AspnTypeSatnavObsPseudorangeRateType;

typedef Aspn23TypeSatnavSatelliteSystem AspnTypeSatnavSatelliteSystem;
#define aspn_type_satnav_satellite_system_new aspn23_type_satnav_satellite_system_new
#define aspn_type_satnav_satellite_system_copy aspn23_type_satnav_satellite_system_copy
#define aspn_type_satnav_satellite_system_free aspn23_type_satnav_satellite_system_free
#define aspn_type_satnav_satellite_system_free_members \
	aspn23_type_satnav_satellite_system_free_members
#define ASPN_TYPE_SATNAV_SATELLITE_SYSTEM_SATELLITE_SYSTEM_SYS_GPS \
	ASPN23_TYPE_SATNAV_SATELLITE_SYSTEM_SATELLITE_SYSTEM_SYS_GPS
#define ASPN_TYPE_SATNAV_SATELLITE_SYSTEM_SATELLITE_SYSTEM_SYS_GALILEO \
	ASPN23_TYPE_SATNAV_SATELLITE_SYSTEM_SATELLITE_SYSTEM_SYS_GALILEO
#define ASPN_TYPE_SATNAV_SATELLITE_SYSTEM_SATELLITE_SYSTEM_SYS_GLONASS \
	ASPN23_TYPE_SATNAV_SATELLITE_SYSTEM_SATELLITE_SYSTEM_SYS_GLONASS
#define ASPN_TYPE_SATNAV_SATELLITE_SYSTEM_SATELLITE_SYSTEM_SYS_BEIDOU \
	ASPN23_TYPE_SATNAV_SATELLITE_SYSTEM_SATELLITE_SYSTEM_SYS_BEIDOU
#define ASPN_TYPE_SATNAV_SATELLITE_SYSTEM_SATELLITE_SYSTEM_SYS_SBAS \
	ASPN23_TYPE_SATNAV_SATELLITE_SYSTEM_SATELLITE_SYSTEM_SYS_SBAS
#define ASPN_TYPE_SATNAV_SATELLITE_SYSTEM_SATELLITE_SYSTEM_SYS_QZSS \
	ASPN23_TYPE_SATNAV_SATELLITE_SYSTEM_SATELLITE_SYSTEM_SYS_QZSS
#define ASPN_TYPE_SATNAV_SATELLITE_SYSTEM_SATELLITE_SYSTEM_SYS_IRNSS \
	ASPN23_TYPE_SATNAV_SATELLITE_SYSTEM_SATELLITE_SYSTEM_SYS_IRNSS
typedef enum Aspn23TypeSatnavSatelliteSystemSatelliteSystem
    AspnTypeSatnavSatelliteSystemSatelliteSystem;

typedef Aspn23TypeSatnavSignalDescriptor AspnTypeSatnavSignalDescriptor;
#define aspn_type_satnav_signal_descriptor_new aspn23_type_satnav_signal_descriptor_new
#define aspn_type_satnav_signal_descriptor_copy aspn23_type_satnav_signal_descriptor_copy
#define aspn_type_satnav_signal_descriptor_free aspn23_type_satnav_signal_descriptor_free
#define aspn_type_satnav_signal_descriptor_free_members \
	aspn23_type_satnav_signal_descriptor_free_members
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L1C \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L1C
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L1S \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L1S
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L1L \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L1L
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L1X \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L1X
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L1P \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L1P
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L1W \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L1W
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L1N \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L1N
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L2C \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L2C
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L2D \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L2D
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L2S \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L2S
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L2L \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L2L
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L2X \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L2X
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L2P \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L2P
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L2W \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L2W
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L2N \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L2N
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L5I \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L5I
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L5Q \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L5Q
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L5X \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L5X
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L4A \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L4A
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L4B \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L4B
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L4X \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L4X
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L6A \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L6A
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L6B \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L6B
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L6X \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L6X
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L3I \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L3I
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L3Q \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L3Q
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L3X \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L3X
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L1B \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L1B
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L7I \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L7I
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L7Q \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L7Q
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L7X \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L7X
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L8I \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L8I
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L8Q \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L8Q
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L8X \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L8X
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L6C \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L6C
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L1Z \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L1Z
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L5D \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L5D
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L5P \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L5P
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L5Z \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L5Z
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L6S \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L6S
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L6L \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L6L
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L6E \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L6E
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L6Z \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L6Z
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L2I \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L2I
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L2Q \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L2Q
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L1D \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L1D
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L7D \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L7D
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L7P \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L7P
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L7Z \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L7Z
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L8D \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L8D
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L8P \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L8P
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L6I \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L6I
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L6Q \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L6Q
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L6D \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L6D
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L6P \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L6P
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L5A \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L5A
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L5B \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L5B
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L5C \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L5C
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L9A \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L9A
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L9B \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L9B
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L9C \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L9C
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L9X \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L9X
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L1Y \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L1Y
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L1M \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L1M
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L2Y \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L2Y
#define ASPN_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L2M \
	ASPN23_TYPE_SATNAV_SIGNAL_DESCRIPTOR_SIGNAL_DESCRIPTOR_L2M
typedef enum Aspn23TypeSatnavSignalDescriptorSignalDescriptor
    AspnTypeSatnavSignalDescriptorSignalDescriptor;

typedef Aspn23TypeSatnavSvData AspnTypeSatnavSvData;
#define aspn_type_satnav_sv_data_new aspn23_type_satnav_sv_data_new
#define aspn_type_satnav_sv_data_copy aspn23_type_satnav_sv_data_copy
#define aspn_type_satnav_sv_data_free aspn23_type_satnav_sv_data_free
#define aspn_type_satnav_sv_data_free_members aspn23_type_satnav_sv_data_free_members
#define ASPN_TYPE_SATNAV_SV_DATA_EPHEMERIS_TYPE_SET_BY_SYSTEM \
	ASPN23_TYPE_SATNAV_SV_DATA_EPHEMERIS_TYPE_SET_BY_SYSTEM
#define ASPN_TYPE_SATNAV_SV_DATA_EPHEMERIS_TYPE_GPS_LNAV \
	ASPN23_TYPE_SATNAV_SV_DATA_EPHEMERIS_TYPE_GPS_LNAV
#define ASPN_TYPE_SATNAV_SV_DATA_EPHEMERIS_TYPE_GPS_CNAV \
	ASPN23_TYPE_SATNAV_SV_DATA_EPHEMERIS_TYPE_GPS_CNAV
#define ASPN_TYPE_SATNAV_SV_DATA_EPHEMERIS_TYPE_GPS_MNAV \
	ASPN23_TYPE_SATNAV_SV_DATA_EPHEMERIS_TYPE_GPS_MNAV
#define ASPN_TYPE_SATNAV_SV_DATA_COORDINATE_FRAME_ITRF \
	ASPN23_TYPE_SATNAV_SV_DATA_COORDINATE_FRAME_ITRF
#define ASPN_TYPE_SATNAV_SV_DATA_COORDINATE_FRAME_ECEF \
	ASPN23_TYPE_SATNAV_SV_DATA_COORDINATE_FRAME_ECEF
#define ASPN_TYPE_SATNAV_SV_DATA_COORDINATE_FRAME_GTRF \
	ASPN23_TYPE_SATNAV_SV_DATA_COORDINATE_FRAME_GTRF
#define ASPN_TYPE_SATNAV_SV_DATA_COORDINATE_FRAME_PZ90 \
	ASPN23_TYPE_SATNAV_SV_DATA_COORDINATE_FRAME_PZ90
#define ASPN_TYPE_SATNAV_SV_DATA_GROUP_DELAY_ENUM_TGD_LNAV \
	ASPN23_TYPE_SATNAV_SV_DATA_GROUP_DELAY_ENUM_TGD_LNAV
typedef enum Aspn23TypeSatnavSvDataCoordinateFrame AspnTypeSatnavSvDataCoordinateFrame;
typedef enum Aspn23TypeSatnavSvDataEphemerisType AspnTypeSatnavSvDataEphemerisType;
typedef enum Aspn23TypeSatnavSvDataGroupDelayEnum AspnTypeSatnavSvDataGroupDelayEnum;

typedef Aspn23TypeSatnavTime AspnTypeSatnavTime;
#define aspn_type_satnav_time_new aspn23_type_satnav_time_new
#define aspn_type_satnav_time_copy aspn23_type_satnav_time_copy
#define aspn_type_satnav_time_free aspn23_type_satnav_time_free
#define aspn_type_satnav_time_free_members aspn23_type_satnav_time_free_members
#define ASPN_TYPE_SATNAV_TIME_TIME_REFERENCE_TIME_GPS \
	ASPN23_TYPE_SATNAV_TIME_TIME_REFERENCE_TIME_GPS
#define ASPN_TYPE_SATNAV_TIME_TIME_REFERENCE_TIME_GALILEO \
	ASPN23_TYPE_SATNAV_TIME_TIME_REFERENCE_TIME_GALILEO
#define ASPN_TYPE_SATNAV_TIME_TIME_REFERENCE_TIME_BEIDOU \
	ASPN23_TYPE_SATNAV_TIME_TIME_REFERENCE_TIME_BEIDOU
#define ASPN_TYPE_SATNAV_TIME_TIME_REFERENCE_TIME_GLONASS \
	ASPN23_TYPE_SATNAV_TIME_TIME_REFERENCE_TIME_GLONASS
typedef enum Aspn23TypeSatnavTimeTimeReference AspnTypeSatnavTimeTimeReference;

typedef Aspn23TypeTimestamp AspnTypeTimestamp;
#define aspn_type_timestamp_new aspn23_type_timestamp_new
#define aspn_type_timestamp_copy aspn23_type_timestamp_copy
#define aspn_type_timestamp_free aspn23_type_timestamp_free
#define aspn_type_timestamp_free_members aspn23_type_timestamp_free_members

typedef Aspn23MetadataBeidouEphemeris AspnMetadataBeidouEphemeris;
#define aspn_metadata_beidou_ephemeris_new aspn23_metadata_beidou_ephemeris_new
#define aspn_metadata_beidou_ephemeris_copy aspn23_metadata_beidou_ephemeris_copy
#define aspn_metadata_beidou_ephemeris_free aspn23_metadata_beidou_ephemeris_free
#define aspn_metadata_beidou_ephemeris_free_members aspn23_metadata_beidou_ephemeris_free_members

typedef Aspn23MetadataGlonassEphemeris AspnMetadataGlonassEphemeris;
#define aspn_metadata_glonass_ephemeris_new aspn23_metadata_glonass_ephemeris_new
#define aspn_metadata_glonass_ephemeris_copy aspn23_metadata_glonass_ephemeris_copy
#define aspn_metadata_glonass_ephemeris_free aspn23_metadata_glonass_ephemeris_free
#define aspn_metadata_glonass_ephemeris_free_members aspn23_metadata_glonass_ephemeris_free_members

typedef Aspn23MetadataGpsCnavEphemeris AspnMetadataGpsCnavEphemeris;
#define aspn_metadata_gps_cnav_ephemeris_new aspn23_metadata_gps_cnav_ephemeris_new
#define aspn_metadata_gps_cnav_ephemeris_copy aspn23_metadata_gps_cnav_ephemeris_copy
#define aspn_metadata_gps_cnav_ephemeris_free aspn23_metadata_gps_cnav_ephemeris_free
#define aspn_metadata_gps_cnav_ephemeris_free_members \
	aspn23_metadata_gps_cnav_ephemeris_free_members

typedef Aspn23MetadataGpsLnavEphemeris AspnMetadataGpsLnavEphemeris;
#define aspn_metadata_gps_lnav_ephemeris_new aspn23_metadata_gps_lnav_ephemeris_new
#define aspn_metadata_gps_lnav_ephemeris_copy aspn23_metadata_gps_lnav_ephemeris_copy
#define aspn_metadata_gps_lnav_ephemeris_free aspn23_metadata_gps_lnav_ephemeris_free
#define aspn_metadata_gps_lnav_ephemeris_free_members \
	aspn23_metadata_gps_lnav_ephemeris_free_members

typedef Aspn23MetadataGpsMnavEphemeris AspnMetadataGpsMnavEphemeris;
#define aspn_metadata_gps_mnav_ephemeris_new aspn23_metadata_gps_mnav_ephemeris_new
#define aspn_metadata_gps_mnav_ephemeris_copy aspn23_metadata_gps_mnav_ephemeris_copy
#define aspn_metadata_gps_mnav_ephemeris_free aspn23_metadata_gps_mnav_ephemeris_free
#define aspn_metadata_gps_mnav_ephemeris_free_members \
	aspn23_metadata_gps_mnav_ephemeris_free_members

typedef Aspn23MetadataGpsIonoUtcParameters AspnMetadataGpsIonoUtcParameters;
#define aspn_metadata_gps_iono_utc_parameters_new aspn23_metadata_gps_iono_utc_parameters_new
#define aspn_metadata_gps_iono_utc_parameters_copy aspn23_metadata_gps_iono_utc_parameters_copy
#define aspn_metadata_gps_iono_utc_parameters_free aspn23_metadata_gps_iono_utc_parameters_free
#define aspn_metadata_gps_iono_utc_parameters_free_members \
	aspn23_metadata_gps_iono_utc_parameters_free_members

typedef Aspn23MetadataGalileoEphemeris AspnMetadataGalileoEphemeris;
#define aspn_metadata_galileo_ephemeris_new aspn23_metadata_galileo_ephemeris_new
#define aspn_metadata_galileo_ephemeris_copy aspn23_metadata_galileo_ephemeris_copy
#define aspn_metadata_galileo_ephemeris_free aspn23_metadata_galileo_ephemeris_free
#define aspn_metadata_galileo_ephemeris_free_members aspn23_metadata_galileo_ephemeris_free_members
#define ASPN_METADATA_GALILEO_EPHEMERIS_NAV_MSG_TYPE_INAV \
	ASPN23_METADATA_GALILEO_EPHEMERIS_NAV_MSG_TYPE_INAV
#define ASPN_METADATA_GALILEO_EPHEMERIS_NAV_MSG_TYPE_FNAV \
	ASPN23_METADATA_GALILEO_EPHEMERIS_NAV_MSG_TYPE_FNAV
typedef enum Aspn23MetadataGalileoEphemerisNavMsgType AspnMetadataGalileoEphemerisNavMsgType;

typedef Aspn23MetadataImu AspnMetadataImu;
#define aspn_metadata_imu_new aspn23_metadata_imu_new
#define aspn_metadata_imu_copy aspn23_metadata_imu_copy
#define aspn_metadata_imu_free aspn23_metadata_imu_free
#define aspn_metadata_imu_free_members aspn23_metadata_imu_free_members
#define ASPN_METADATA_IMU_ERROR_MODEL_BASIC ASPN23_METADATA_IMU_ERROR_MODEL_BASIC
typedef enum Aspn23MetadataImuErrorModel AspnMetadataImuErrorModel;

typedef Aspn23MetadataGeneric AspnMetadataGeneric;
#define aspn_metadata_generic_new aspn23_metadata_generic_new
#define aspn_metadata_generic_copy aspn23_metadata_generic_copy
#define aspn_metadata_generic_free aspn23_metadata_generic_free
#define aspn_metadata_generic_free_members aspn23_metadata_generic_free_members

typedef Aspn23MetadataImageFeatures AspnMetadataImageFeatures;
#define aspn_metadata_image_features_new aspn23_metadata_image_features_new
#define aspn_metadata_image_features_copy aspn23_metadata_image_features_copy
#define aspn_metadata_image_features_free aspn23_metadata_image_features_free
#define aspn_metadata_image_features_free_members aspn23_metadata_image_features_free_members
#define ASPN_METADATA_IMAGE_FEATURES_KEYPOINT_DETECTOR_DET_AGAST \
	ASPN23_METADATA_IMAGE_FEATURES_KEYPOINT_DETECTOR_DET_AGAST
#define ASPN_METADATA_IMAGE_FEATURES_KEYPOINT_DETECTOR_DET_AKAZE \
	ASPN23_METADATA_IMAGE_FEATURES_KEYPOINT_DETECTOR_DET_AKAZE
#define ASPN_METADATA_IMAGE_FEATURES_KEYPOINT_DETECTOR_DET_BRISK \
	ASPN23_METADATA_IMAGE_FEATURES_KEYPOINT_DETECTOR_DET_BRISK
#define ASPN_METADATA_IMAGE_FEATURES_KEYPOINT_DETECTOR_DET_FAST \
	ASPN23_METADATA_IMAGE_FEATURES_KEYPOINT_DETECTOR_DET_FAST
#define ASPN_METADATA_IMAGE_FEATURES_KEYPOINT_DETECTOR_DET_GFTT \
	ASPN23_METADATA_IMAGE_FEATURES_KEYPOINT_DETECTOR_DET_GFTT
#define ASPN_METADATA_IMAGE_FEATURES_KEYPOINT_DETECTOR_DET_KAZE \
	ASPN23_METADATA_IMAGE_FEATURES_KEYPOINT_DETECTOR_DET_KAZE
#define ASPN_METADATA_IMAGE_FEATURES_KEYPOINT_DETECTOR_DET_MSER \
	ASPN23_METADATA_IMAGE_FEATURES_KEYPOINT_DETECTOR_DET_MSER
#define ASPN_METADATA_IMAGE_FEATURES_KEYPOINT_DETECTOR_DET_ORB \
	ASPN23_METADATA_IMAGE_FEATURES_KEYPOINT_DETECTOR_DET_ORB
#define ASPN_METADATA_IMAGE_FEATURES_KEYPOINT_DETECTOR_DET_SIFT \
	ASPN23_METADATA_IMAGE_FEATURES_KEYPOINT_DETECTOR_DET_SIFT
#define ASPN_METADATA_IMAGE_FEATURES_KEYPOINT_DETECTOR_DET_SURF \
	ASPN23_METADATA_IMAGE_FEATURES_KEYPOINT_DETECTOR_DET_SURF
#define ASPN_METADATA_IMAGE_FEATURES_KEYPOINT_DETECTOR_DET_HARRIS \
	ASPN23_METADATA_IMAGE_FEATURES_KEYPOINT_DETECTOR_DET_HARRIS
#define ASPN_METADATA_IMAGE_FEATURES_KEYPOINT_DETECTOR_DET_SHI \
	ASPN23_METADATA_IMAGE_FEATURES_KEYPOINT_DETECTOR_DET_SHI
#define ASPN_METADATA_IMAGE_FEATURES_KEYPOINT_DETECTOR_DET_OTHER \
	ASPN23_METADATA_IMAGE_FEATURES_KEYPOINT_DETECTOR_DET_OTHER
#define ASPN_METADATA_IMAGE_FEATURES_DESCRIPTOR_EXTRACTOR_DESC_AKAZE \
	ASPN23_METADATA_IMAGE_FEATURES_DESCRIPTOR_EXTRACTOR_DESC_AKAZE
#define ASPN_METADATA_IMAGE_FEATURES_DESCRIPTOR_EXTRACTOR_DESC_BRISK \
	ASPN23_METADATA_IMAGE_FEATURES_DESCRIPTOR_EXTRACTOR_DESC_BRISK
#define ASPN_METADATA_IMAGE_FEATURES_DESCRIPTOR_EXTRACTOR_DESC_KAZE \
	ASPN23_METADATA_IMAGE_FEATURES_DESCRIPTOR_EXTRACTOR_DESC_KAZE
#define ASPN_METADATA_IMAGE_FEATURES_DESCRIPTOR_EXTRACTOR_DESC_ORB \
	ASPN23_METADATA_IMAGE_FEATURES_DESCRIPTOR_EXTRACTOR_DESC_ORB
#define ASPN_METADATA_IMAGE_FEATURES_DESCRIPTOR_EXTRACTOR_DESC_SIFT \
	ASPN23_METADATA_IMAGE_FEATURES_DESCRIPTOR_EXTRACTOR_DESC_SIFT
#define ASPN_METADATA_IMAGE_FEATURES_DESCRIPTOR_EXTRACTOR_DESC_SURF \
	ASPN23_METADATA_IMAGE_FEATURES_DESCRIPTOR_EXTRACTOR_DESC_SURF
#define ASPN_METADATA_IMAGE_FEATURES_DESCRIPTOR_EXTRACTOR_DESC_OTHER \
	ASPN23_METADATA_IMAGE_FEATURES_DESCRIPTOR_EXTRACTOR_DESC_OTHER
#define ASPN_METADATA_IMAGE_FEATURES_DESCRIPTOR_TYPE_UINT8 \
	ASPN23_METADATA_IMAGE_FEATURES_DESCRIPTOR_TYPE_UINT8
#define ASPN_METADATA_IMAGE_FEATURES_DESCRIPTOR_TYPE_FLOAT32 \
	ASPN23_METADATA_IMAGE_FEATURES_DESCRIPTOR_TYPE_FLOAT32
typedef enum Aspn23MetadataImageFeaturesDescriptorExtractor
    AspnMetadataImageFeaturesDescriptorExtractor;
typedef enum Aspn23MetadataImageFeaturesDescriptorType AspnMetadataImageFeaturesDescriptorType;
typedef enum Aspn23MetadataImageFeaturesKeypointDetector AspnMetadataImageFeaturesKeypointDetector;

typedef Aspn23MetadataMagneticField AspnMetadataMagneticField;
#define aspn_metadata_magnetic_field_new aspn23_metadata_magnetic_field_new
#define aspn_metadata_magnetic_field_copy aspn23_metadata_magnetic_field_copy
#define aspn_metadata_magnetic_field_free aspn23_metadata_magnetic_field_free
#define aspn_metadata_magnetic_field_free_members aspn23_metadata_magnetic_field_free_members

typedef Aspn23MetadataSatnavObs AspnMetadataSatnavObs;
#define aspn_metadata_satnav_obs_new aspn23_metadata_satnav_obs_new
#define aspn_metadata_satnav_obs_copy aspn23_metadata_satnav_obs_copy
#define aspn_metadata_satnav_obs_free aspn23_metadata_satnav_obs_free
#define aspn_metadata_satnav_obs_free_members aspn23_metadata_satnav_obs_free_members

typedef Aspn23MeasurementImu AspnMeasurementImu;
#define aspn_measurement_imu_new aspn23_measurement_imu_new
#define aspn_measurement_imu_copy aspn23_measurement_imu_copy
#define aspn_measurement_imu_free aspn23_measurement_imu_free
#define aspn_measurement_imu_free_members aspn23_measurement_imu_free_members
#define ASPN_MEASUREMENT_IMU_IMU_TYPE_INTEGRATED ASPN23_MEASUREMENT_IMU_IMU_TYPE_INTEGRATED
#define ASPN_MEASUREMENT_IMU_IMU_TYPE_SAMPLED ASPN23_MEASUREMENT_IMU_IMU_TYPE_SAMPLED
typedef enum Aspn23MeasurementImuImuType AspnMeasurementImuImuType;

typedef Aspn23MeasurementTdoa1Tx2Rx AspnMeasurementTdoa1Tx2Rx;
#define aspn_measurement_tdoa_1tx_2rx_new aspn23_measurement_tdoa_1tx_2rx_new
#define aspn_measurement_tdoa_1tx_2rx_copy aspn23_measurement_tdoa_1tx_2rx_copy
#define aspn_measurement_tdoa_1tx_2rx_free aspn23_measurement_tdoa_1tx_2rx_free
#define aspn_measurement_tdoa_1tx_2rx_free_members aspn23_measurement_tdoa_1tx_2rx_free_members
#define ASPN_MEASUREMENT_TDOA_1TX_2RX_ERROR_MODEL_NONE \
	ASPN23_MEASUREMENT_TDOA_1TX_2RX_ERROR_MODEL_NONE
typedef enum Aspn23MeasurementTdoa1Tx2RxErrorModel AspnMeasurementTdoa1Tx2RxErrorModel;

typedef Aspn23MeasurementTdoa2Tx1Rx AspnMeasurementTdoa2Tx1Rx;
#define aspn_measurement_tdoa_2tx_1rx_new aspn23_measurement_tdoa_2tx_1rx_new
#define aspn_measurement_tdoa_2tx_1rx_copy aspn23_measurement_tdoa_2tx_1rx_copy
#define aspn_measurement_tdoa_2tx_1rx_free aspn23_measurement_tdoa_2tx_1rx_free
#define aspn_measurement_tdoa_2tx_1rx_free_members aspn23_measurement_tdoa_2tx_1rx_free_members
#define ASPN_MEASUREMENT_TDOA_2TX_1RX_ERROR_MODEL_NONE \
	ASPN23_MEASUREMENT_TDOA_2TX_1RX_ERROR_MODEL_NONE
typedef enum Aspn23MeasurementTdoa2Tx1RxErrorModel AspnMeasurementTdoa2Tx1RxErrorModel;

typedef Aspn23MeasurementAccumulatedDistanceTraveled AspnMeasurementAccumulatedDistanceTraveled;
#define aspn_measurement_accumulated_distance_traveled_new \
	aspn23_measurement_accumulated_distance_traveled_new
#define aspn_measurement_accumulated_distance_traveled_copy \
	aspn23_measurement_accumulated_distance_traveled_copy
#define aspn_measurement_accumulated_distance_traveled_free \
	aspn23_measurement_accumulated_distance_traveled_free
#define aspn_measurement_accumulated_distance_traveled_free_members \
	aspn23_measurement_accumulated_distance_traveled_free_members
#define ASPN_MEASUREMENT_ACCUMULATED_DISTANCE_TRAVELED_ERROR_MODEL_NONE \
	ASPN23_MEASUREMENT_ACCUMULATED_DISTANCE_TRAVELED_ERROR_MODEL_NONE
typedef enum Aspn23MeasurementAccumulatedDistanceTraveledErrorModel
    AspnMeasurementAccumulatedDistanceTraveledErrorModel;

typedef Aspn23MeasurementAltitude AspnMeasurementAltitude;
#define aspn_measurement_altitude_new aspn23_measurement_altitude_new
#define aspn_measurement_altitude_copy aspn23_measurement_altitude_copy
#define aspn_measurement_altitude_free aspn23_measurement_altitude_free
#define aspn_measurement_altitude_free_members aspn23_measurement_altitude_free_members
#define ASPN_MEASUREMENT_ALTITUDE_REFERENCE_AGL ASPN23_MEASUREMENT_ALTITUDE_REFERENCE_AGL
#define ASPN_MEASUREMENT_ALTITUDE_REFERENCE_MSL ASPN23_MEASUREMENT_ALTITUDE_REFERENCE_MSL
#define ASPN_MEASUREMENT_ALTITUDE_REFERENCE_HAE ASPN23_MEASUREMENT_ALTITUDE_REFERENCE_HAE
#define ASPN_MEASUREMENT_ALTITUDE_ERROR_MODEL_NONE ASPN23_MEASUREMENT_ALTITUDE_ERROR_MODEL_NONE
#define ASPN_MEASUREMENT_ALTITUDE_ERROR_MODEL_FOGM ASPN23_MEASUREMENT_ALTITUDE_ERROR_MODEL_FOGM
typedef enum Aspn23MeasurementAltitudeErrorModel AspnMeasurementAltitudeErrorModel;
typedef enum Aspn23MeasurementAltitudeReference AspnMeasurementAltitudeReference;

typedef Aspn23MeasurementAngularVelocity AspnMeasurementAngularVelocity;
#define aspn_measurement_angular_velocity_new aspn23_measurement_angular_velocity_new
#define aspn_measurement_angular_velocity_copy aspn23_measurement_angular_velocity_copy
#define aspn_measurement_angular_velocity_free aspn23_measurement_angular_velocity_free
#define aspn_measurement_angular_velocity_free_members \
	aspn23_measurement_angular_velocity_free_members
#define ASPN_MEASUREMENT_ANGULAR_VELOCITY_REFERENCE_FRAME_ECI \
	ASPN23_MEASUREMENT_ANGULAR_VELOCITY_REFERENCE_FRAME_ECI
#define ASPN_MEASUREMENT_ANGULAR_VELOCITY_REFERENCE_FRAME_ECEF \
	ASPN23_MEASUREMENT_ANGULAR_VELOCITY_REFERENCE_FRAME_ECEF
#define ASPN_MEASUREMENT_ANGULAR_VELOCITY_REFERENCE_FRAME_NED \
	ASPN23_MEASUREMENT_ANGULAR_VELOCITY_REFERENCE_FRAME_NED
#define ASPN_MEASUREMENT_ANGULAR_VELOCITY_REFERENCE_FRAME_SENSOR \
	ASPN23_MEASUREMENT_ANGULAR_VELOCITY_REFERENCE_FRAME_SENSOR
#define ASPN_MEASUREMENT_ANGULAR_VELOCITY_IMU_TYPE_INTEGRATED \
	ASPN23_MEASUREMENT_ANGULAR_VELOCITY_IMU_TYPE_INTEGRATED
#define ASPN_MEASUREMENT_ANGULAR_VELOCITY_IMU_TYPE_SAMPLED \
	ASPN23_MEASUREMENT_ANGULAR_VELOCITY_IMU_TYPE_SAMPLED
#define ASPN_MEASUREMENT_ANGULAR_VELOCITY_ERROR_MODEL_NONE \
	ASPN23_MEASUREMENT_ANGULAR_VELOCITY_ERROR_MODEL_NONE
typedef enum Aspn23MeasurementAngularVelocityErrorModel AspnMeasurementAngularVelocityErrorModel;
typedef enum Aspn23MeasurementAngularVelocityImuType AspnMeasurementAngularVelocityImuType;
typedef enum Aspn23MeasurementAngularVelocityReferenceFrame
    AspnMeasurementAngularVelocityReferenceFrame;

typedef Aspn23MeasurementAngularVelocity1D AspnMeasurementAngularVelocity1D;
#define aspn_measurement_angular_velocity_1d_new aspn23_measurement_angular_velocity_1d_new
#define aspn_measurement_angular_velocity_1d_copy aspn23_measurement_angular_velocity_1d_copy
#define aspn_measurement_angular_velocity_1d_free aspn23_measurement_angular_velocity_1d_free
#define aspn_measurement_angular_velocity_1d_free_members \
	aspn23_measurement_angular_velocity_1d_free_members
#define ASPN_MEASUREMENT_ANGULAR_VELOCITY_1D_SENSOR_TYPE_INTEGRATED \
	ASPN23_MEASUREMENT_ANGULAR_VELOCITY_1D_SENSOR_TYPE_INTEGRATED
#define ASPN_MEASUREMENT_ANGULAR_VELOCITY_1D_SENSOR_TYPE_SAMPLED \
	ASPN23_MEASUREMENT_ANGULAR_VELOCITY_1D_SENSOR_TYPE_SAMPLED
#define ASPN_MEASUREMENT_ANGULAR_VELOCITY_1D_ERROR_MODEL_NONE \
	ASPN23_MEASUREMENT_ANGULAR_VELOCITY_1D_ERROR_MODEL_NONE
typedef enum Aspn23MeasurementAngularVelocity1DErrorModel
    AspnMeasurementAngularVelocity1DErrorModel;
typedef enum Aspn23MeasurementAngularVelocity1DSensorType
    AspnMeasurementAngularVelocity1DSensorType;

typedef Aspn23MeasurementAttitude2D AspnMeasurementAttitude2D;
#define aspn_measurement_attitude_2d_new aspn23_measurement_attitude_2d_new
#define aspn_measurement_attitude_2d_copy aspn23_measurement_attitude_2d_copy
#define aspn_measurement_attitude_2d_free aspn23_measurement_attitude_2d_free
#define aspn_measurement_attitude_2d_free_members aspn23_measurement_attitude_2d_free_members
#define ASPN_MEASUREMENT_ATTITUDE_2D_REFERENCE_FRAME_NE \
	ASPN23_MEASUREMENT_ATTITUDE_2D_REFERENCE_FRAME_NE
#define ASPN_MEASUREMENT_ATTITUDE_2D_REFERENCE_FRAME_ND \
	ASPN23_MEASUREMENT_ATTITUDE_2D_REFERENCE_FRAME_ND
#define ASPN_MEASUREMENT_ATTITUDE_2D_REFERENCE_FRAME_ED \
	ASPN23_MEASUREMENT_ATTITUDE_2D_REFERENCE_FRAME_ED
#define ASPN_MEASUREMENT_ATTITUDE_2D_ERROR_MODEL_NONE \
	ASPN23_MEASUREMENT_ATTITUDE_2D_ERROR_MODEL_NONE
typedef enum Aspn23MeasurementAttitude2DErrorModel AspnMeasurementAttitude2DErrorModel;
typedef enum Aspn23MeasurementAttitude2DReferenceFrame AspnMeasurementAttitude2DReferenceFrame;

typedef Aspn23MeasurementAttitude3D AspnMeasurementAttitude3D;
#define aspn_measurement_attitude_3d_new aspn23_measurement_attitude_3d_new
#define aspn_measurement_attitude_3d_copy aspn23_measurement_attitude_3d_copy
#define aspn_measurement_attitude_3d_free aspn23_measurement_attitude_3d_free
#define aspn_measurement_attitude_3d_free_members aspn23_measurement_attitude_3d_free_members
#define ASPN_MEASUREMENT_ATTITUDE_3D_REFERENCE_FRAME_ECI \
	ASPN23_MEASUREMENT_ATTITUDE_3D_REFERENCE_FRAME_ECI
#define ASPN_MEASUREMENT_ATTITUDE_3D_REFERENCE_FRAME_ECEF \
	ASPN23_MEASUREMENT_ATTITUDE_3D_REFERENCE_FRAME_ECEF
#define ASPN_MEASUREMENT_ATTITUDE_3D_REFERENCE_FRAME_NED \
	ASPN23_MEASUREMENT_ATTITUDE_3D_REFERENCE_FRAME_NED
#define ASPN_MEASUREMENT_ATTITUDE_3D_ERROR_MODEL_NONE \
	ASPN23_MEASUREMENT_ATTITUDE_3D_ERROR_MODEL_NONE
typedef enum Aspn23MeasurementAttitude3DErrorModel AspnMeasurementAttitude3DErrorModel;
typedef enum Aspn23MeasurementAttitude3DReferenceFrame AspnMeasurementAttitude3DReferenceFrame;

typedef Aspn23MeasurementBarometer AspnMeasurementBarometer;
#define aspn_measurement_barometer_new aspn23_measurement_barometer_new
#define aspn_measurement_barometer_copy aspn23_measurement_barometer_copy
#define aspn_measurement_barometer_free aspn23_measurement_barometer_free
#define aspn_measurement_barometer_free_members aspn23_measurement_barometer_free_members
#define ASPN_MEASUREMENT_BAROMETER_ERROR_MODEL_NONE ASPN23_MEASUREMENT_BAROMETER_ERROR_MODEL_NONE
typedef enum Aspn23MeasurementBarometerErrorModel AspnMeasurementBarometerErrorModel;

typedef Aspn23MeasurementDeltaPosition AspnMeasurementDeltaPosition;
#define aspn_measurement_delta_position_new aspn23_measurement_delta_position_new
#define aspn_measurement_delta_position_copy aspn23_measurement_delta_position_copy
#define aspn_measurement_delta_position_free aspn23_measurement_delta_position_free
#define aspn_measurement_delta_position_free_members aspn23_measurement_delta_position_free_members
#define ASPN_MEASUREMENT_DELTA_POSITION_REFERENCE_FRAME_NED \
	ASPN23_MEASUREMENT_DELTA_POSITION_REFERENCE_FRAME_NED
#define ASPN_MEASUREMENT_DELTA_POSITION_REFERENCE_FRAME_SENSOR_START \
	ASPN23_MEASUREMENT_DELTA_POSITION_REFERENCE_FRAME_SENSOR_START
#define ASPN_MEASUREMENT_DELTA_POSITION_REFERENCE_FRAME_SENSOR_END \
	ASPN23_MEASUREMENT_DELTA_POSITION_REFERENCE_FRAME_SENSOR_END
#define ASPN_MEASUREMENT_DELTA_POSITION_ERROR_MODEL_NONE \
	ASPN23_MEASUREMENT_DELTA_POSITION_ERROR_MODEL_NONE
typedef enum Aspn23MeasurementDeltaPositionErrorModel AspnMeasurementDeltaPositionErrorModel;
typedef enum Aspn23MeasurementDeltaPositionReferenceFrame
    AspnMeasurementDeltaPositionReferenceFrame;

typedef Aspn23MeasurementDeltaRange AspnMeasurementDeltaRange;
#define aspn_measurement_delta_range_new aspn23_measurement_delta_range_new
#define aspn_measurement_delta_range_copy aspn23_measurement_delta_range_copy
#define aspn_measurement_delta_range_free aspn23_measurement_delta_range_free
#define aspn_measurement_delta_range_free_members aspn23_measurement_delta_range_free_members
#define ASPN_MEASUREMENT_DELTA_RANGE_ERROR_MODEL_NONE \
	ASPN23_MEASUREMENT_DELTA_RANGE_ERROR_MODEL_NONE
typedef enum Aspn23MeasurementDeltaRangeErrorModel AspnMeasurementDeltaRangeErrorModel;

typedef Aspn23MeasurementDeltaRangeToPoint AspnMeasurementDeltaRangeToPoint;
#define aspn_measurement_delta_range_to_point_new aspn23_measurement_delta_range_to_point_new
#define aspn_measurement_delta_range_to_point_copy aspn23_measurement_delta_range_to_point_copy
#define aspn_measurement_delta_range_to_point_free aspn23_measurement_delta_range_to_point_free
#define aspn_measurement_delta_range_to_point_free_members \
	aspn23_measurement_delta_range_to_point_free_members
#define ASPN_MEASUREMENT_DELTA_RANGE_TO_POINT_ERROR_MODEL_NONE \
	ASPN23_MEASUREMENT_DELTA_RANGE_TO_POINT_ERROR_MODEL_NONE
typedef enum Aspn23MeasurementDeltaRangeToPointErrorModel
    AspnMeasurementDeltaRangeToPointErrorModel;

typedef Aspn23MeasurementDirection2DToPoints AspnMeasurementDirection2DToPoints;
#define aspn_measurement_direction_2d_to_points_new aspn23_measurement_direction_2d_to_points_new
#define aspn_measurement_direction_2d_to_points_copy aspn23_measurement_direction_2d_to_points_copy
#define aspn_measurement_direction_2d_to_points_free aspn23_measurement_direction_2d_to_points_free
#define aspn_measurement_direction_2d_to_points_free_members \
	aspn23_measurement_direction_2d_to_points_free_members

typedef Aspn23MeasurementDirection3DToPoints AspnMeasurementDirection3DToPoints;
#define aspn_measurement_direction_3d_to_points_new aspn23_measurement_direction_3d_to_points_new
#define aspn_measurement_direction_3d_to_points_copy aspn23_measurement_direction_3d_to_points_copy
#define aspn_measurement_direction_3d_to_points_free aspn23_measurement_direction_3d_to_points_free
#define aspn_measurement_direction_3d_to_points_free_members \
	aspn23_measurement_direction_3d_to_points_free_members

typedef Aspn23MeasurementDirectionOfMotion2D AspnMeasurementDirectionOfMotion2D;
#define aspn_measurement_direction_of_motion_2d_new aspn23_measurement_direction_of_motion_2d_new
#define aspn_measurement_direction_of_motion_2d_copy aspn23_measurement_direction_of_motion_2d_copy
#define aspn_measurement_direction_of_motion_2d_free aspn23_measurement_direction_of_motion_2d_free
#define aspn_measurement_direction_of_motion_2d_free_members \
	aspn23_measurement_direction_of_motion_2d_free_members
#define ASPN_MEASUREMENT_DIRECTION_OF_MOTION_2D_REFERENCE_NE \
	ASPN23_MEASUREMENT_DIRECTION_OF_MOTION_2D_REFERENCE_NE
#define ASPN_MEASUREMENT_DIRECTION_OF_MOTION_2D_REFERENCE_ND \
	ASPN23_MEASUREMENT_DIRECTION_OF_MOTION_2D_REFERENCE_ND
#define ASPN_MEASUREMENT_DIRECTION_OF_MOTION_2D_REFERENCE_ED \
	ASPN23_MEASUREMENT_DIRECTION_OF_MOTION_2D_REFERENCE_ED
#define ASPN_MEASUREMENT_DIRECTION_OF_MOTION_2D_REFERENCE_SENSOR \
	ASPN23_MEASUREMENT_DIRECTION_OF_MOTION_2D_REFERENCE_SENSOR
#define ASPN_MEASUREMENT_DIRECTION_OF_MOTION_2D_ERROR_MODEL_NONE \
	ASPN23_MEASUREMENT_DIRECTION_OF_MOTION_2D_ERROR_MODEL_NONE
typedef enum Aspn23MeasurementDirectionOfMotion2DErrorModel
    AspnMeasurementDirectionOfMotion2DErrorModel;
typedef enum Aspn23MeasurementDirectionOfMotion2DReference
    AspnMeasurementDirectionOfMotion2DReference;

typedef Aspn23MeasurementDirectionOfMotion3D AspnMeasurementDirectionOfMotion3D;
#define aspn_measurement_direction_of_motion_3d_new aspn23_measurement_direction_of_motion_3d_new
#define aspn_measurement_direction_of_motion_3d_copy aspn23_measurement_direction_of_motion_3d_copy
#define aspn_measurement_direction_of_motion_3d_free aspn23_measurement_direction_of_motion_3d_free
#define aspn_measurement_direction_of_motion_3d_free_members \
	aspn23_measurement_direction_of_motion_3d_free_members
#define ASPN_MEASUREMENT_DIRECTION_OF_MOTION_3D_REFERENCE_FRAME_ECI \
	ASPN23_MEASUREMENT_DIRECTION_OF_MOTION_3D_REFERENCE_FRAME_ECI
#define ASPN_MEASUREMENT_DIRECTION_OF_MOTION_3D_REFERENCE_FRAME_ECEF \
	ASPN23_MEASUREMENT_DIRECTION_OF_MOTION_3D_REFERENCE_FRAME_ECEF
#define ASPN_MEASUREMENT_DIRECTION_OF_MOTION_3D_REFERENCE_FRAME_NED \
	ASPN23_MEASUREMENT_DIRECTION_OF_MOTION_3D_REFERENCE_FRAME_NED
#define ASPN_MEASUREMENT_DIRECTION_OF_MOTION_3D_REFERENCE_FRAME_SENSOR \
	ASPN23_MEASUREMENT_DIRECTION_OF_MOTION_3D_REFERENCE_FRAME_SENSOR
#define ASPN_MEASUREMENT_DIRECTION_OF_MOTION_3D_ERROR_MODEL_NONE \
	ASPN23_MEASUREMENT_DIRECTION_OF_MOTION_3D_ERROR_MODEL_NONE
typedef enum Aspn23MeasurementDirectionOfMotion3DErrorModel
    AspnMeasurementDirectionOfMotion3DErrorModel;
typedef enum Aspn23MeasurementDirectionOfMotion3DReferenceFrame
    AspnMeasurementDirectionOfMotion3DReferenceFrame;

typedef Aspn23MeasurementFrequencyDifference AspnMeasurementFrequencyDifference;
#define aspn_measurement_frequency_difference_new aspn23_measurement_frequency_difference_new
#define aspn_measurement_frequency_difference_copy aspn23_measurement_frequency_difference_copy
#define aspn_measurement_frequency_difference_free aspn23_measurement_frequency_difference_free
#define aspn_measurement_frequency_difference_free_members \
	aspn23_measurement_frequency_difference_free_members
#define ASPN_MEASUREMENT_FREQUENCY_DIFFERENCE_ERROR_MODEL_NONE \
	ASPN23_MEASUREMENT_FREQUENCY_DIFFERENCE_ERROR_MODEL_NONE
typedef enum Aspn23MeasurementFrequencyDifferenceErrorModel
    AspnMeasurementFrequencyDifferenceErrorModel;

typedef Aspn23MeasurementHeading AspnMeasurementHeading;
#define aspn_measurement_heading_new aspn23_measurement_heading_new
#define aspn_measurement_heading_copy aspn23_measurement_heading_copy
#define aspn_measurement_heading_free aspn23_measurement_heading_free
#define aspn_measurement_heading_free_members aspn23_measurement_heading_free_members
#define ASPN_MEASUREMENT_HEADING_REFERENCE_TRUE_HEADING \
	ASPN23_MEASUREMENT_HEADING_REFERENCE_TRUE_HEADING
#define ASPN_MEASUREMENT_HEADING_REFERENCE_MAGNETIC_HEADING \
	ASPN23_MEASUREMENT_HEADING_REFERENCE_MAGNETIC_HEADING
#define ASPN_MEASUREMENT_HEADING_ERROR_MODEL_NONE ASPN23_MEASUREMENT_HEADING_ERROR_MODEL_NONE
typedef enum Aspn23MeasurementHeadingErrorModel AspnMeasurementHeadingErrorModel;
typedef enum Aspn23MeasurementHeadingReference AspnMeasurementHeadingReference;

typedef Aspn23MeasurementImage AspnMeasurementImage;
#define aspn_measurement_image_new aspn23_measurement_image_new
#define aspn_measurement_image_copy aspn23_measurement_image_copy
#define aspn_measurement_image_free aspn23_measurement_image_free
#define aspn_measurement_image_free_members aspn23_measurement_image_free_members
#define ASPN_MEASUREMENT_IMAGE_IMAGE_TYPE_BMP ASPN23_MEASUREMENT_IMAGE_IMAGE_TYPE_BMP
#define ASPN_MEASUREMENT_IMAGE_IMAGE_TYPE_PNG ASPN23_MEASUREMENT_IMAGE_IMAGE_TYPE_PNG
#define ASPN_MEASUREMENT_IMAGE_IMAGE_TYPE_JPG ASPN23_MEASUREMENT_IMAGE_IMAGE_TYPE_JPG
#define ASPN_MEASUREMENT_IMAGE_IMAGE_TYPE_TIFF ASPN23_MEASUREMENT_IMAGE_IMAGE_TYPE_TIFF
#define ASPN_MEASUREMENT_IMAGE_IMAGE_TYPE_RAW_GRAY8 ASPN23_MEASUREMENT_IMAGE_IMAGE_TYPE_RAW_GRAY8
#define ASPN_MEASUREMENT_IMAGE_IMAGE_TYPE_RAW_RGB8 ASPN23_MEASUREMENT_IMAGE_IMAGE_TYPE_RAW_RGB8
#define ASPN_MEASUREMENT_IMAGE_IMAGE_TYPE_RAW_BGR8 ASPN23_MEASUREMENT_IMAGE_IMAGE_TYPE_RAW_BGR8
#define ASPN_MEASUREMENT_IMAGE_IMAGE_TYPE_RAW_RGBA8 ASPN23_MEASUREMENT_IMAGE_IMAGE_TYPE_RAW_RGBA8
#define ASPN_MEASUREMENT_IMAGE_IMAGE_TYPE_RAW_BGRA8 ASPN23_MEASUREMENT_IMAGE_IMAGE_TYPE_RAW_BGRA8
#define ASPN_MEASUREMENT_IMAGE_IMAGE_TYPE_RAW_GRAY16 ASPN23_MEASUREMENT_IMAGE_IMAGE_TYPE_RAW_GRAY16
#define ASPN_MEASUREMENT_IMAGE_IMAGE_TYPE_RAW_GRAYFLOAT64 \
	ASPN23_MEASUREMENT_IMAGE_IMAGE_TYPE_RAW_GRAYFLOAT64
#define ASPN_MEASUREMENT_IMAGE_CAMERA_MODEL_ASPN_PINHOLE_PLUMB_BOB \
	ASPN23_MEASUREMENT_IMAGE_CAMERA_MODEL_ASPN_PINHOLE_PLUMB_BOB
#define ASPN_MEASUREMENT_IMAGE_CAMERA_MODEL_ASPN_LINEAR_MODEL \
	ASPN23_MEASUREMENT_IMAGE_CAMERA_MODEL_ASPN_LINEAR_MODEL
typedef enum Aspn23MeasurementImageCameraModel AspnMeasurementImageCameraModel;
typedef enum Aspn23MeasurementImageImageType AspnMeasurementImageImageType;

typedef Aspn23MeasurementMagneticField AspnMeasurementMagneticField;
#define aspn_measurement_magnetic_field_new aspn23_measurement_magnetic_field_new
#define aspn_measurement_magnetic_field_copy aspn23_measurement_magnetic_field_copy
#define aspn_measurement_magnetic_field_free aspn23_measurement_magnetic_field_free
#define aspn_measurement_magnetic_field_free_members aspn23_measurement_magnetic_field_free_members
#define ASPN_MEASUREMENT_MAGNETIC_FIELD_ERROR_MODEL_NONE \
	ASPN23_MEASUREMENT_MAGNETIC_FIELD_ERROR_MODEL_NONE
typedef enum Aspn23MeasurementMagneticFieldErrorModel AspnMeasurementMagneticFieldErrorModel;

typedef Aspn23MeasurementMagneticFieldMagnitude AspnMeasurementMagneticFieldMagnitude;
#define aspn_measurement_magnetic_field_magnitude_new \
	aspn23_measurement_magnetic_field_magnitude_new
#define aspn_measurement_magnetic_field_magnitude_copy \
	aspn23_measurement_magnetic_field_magnitude_copy
#define aspn_measurement_magnetic_field_magnitude_free \
	aspn23_measurement_magnetic_field_magnitude_free
#define aspn_measurement_magnetic_field_magnitude_free_members \
	aspn23_measurement_magnetic_field_magnitude_free_members
#define ASPN_MEASUREMENT_MAGNETIC_FIELD_MAGNITUDE_ERROR_MODEL_NONE \
	ASPN23_MEASUREMENT_MAGNETIC_FIELD_MAGNITUDE_ERROR_MODEL_NONE
typedef enum Aspn23MeasurementMagneticFieldMagnitudeErrorModel
    AspnMeasurementMagneticFieldMagnitudeErrorModel;

typedef Aspn23MeasurementPosition AspnMeasurementPosition;
#define aspn_measurement_position_new aspn23_measurement_position_new
#define aspn_measurement_position_copy aspn23_measurement_position_copy
#define aspn_measurement_position_free aspn23_measurement_position_free
#define aspn_measurement_position_free_members aspn23_measurement_position_free_members
#define ASPN_MEASUREMENT_POSITION_REFERENCE_FRAME_ECI \
	ASPN23_MEASUREMENT_POSITION_REFERENCE_FRAME_ECI
#define ASPN_MEASUREMENT_POSITION_REFERENCE_FRAME_GEODETIC \
	ASPN23_MEASUREMENT_POSITION_REFERENCE_FRAME_GEODETIC
#define ASPN_MEASUREMENT_POSITION_ERROR_MODEL_NONE ASPN23_MEASUREMENT_POSITION_ERROR_MODEL_NONE
typedef enum Aspn23MeasurementPositionErrorModel AspnMeasurementPositionErrorModel;
typedef enum Aspn23MeasurementPositionReferenceFrame AspnMeasurementPositionReferenceFrame;

typedef Aspn23MeasurementPositionAttitude AspnMeasurementPositionAttitude;
#define aspn_measurement_position_attitude_new aspn23_measurement_position_attitude_new
#define aspn_measurement_position_attitude_copy aspn23_measurement_position_attitude_copy
#define aspn_measurement_position_attitude_free aspn23_measurement_position_attitude_free
#define aspn_measurement_position_attitude_free_members \
	aspn23_measurement_position_attitude_free_members
#define ASPN_MEASUREMENT_POSITION_ATTITUDE_REFERENCE_FRAME_ECI \
	ASPN23_MEASUREMENT_POSITION_ATTITUDE_REFERENCE_FRAME_ECI
#define ASPN_MEASUREMENT_POSITION_ATTITUDE_REFERENCE_FRAME_GEODETIC \
	ASPN23_MEASUREMENT_POSITION_ATTITUDE_REFERENCE_FRAME_GEODETIC
#define ASPN_MEASUREMENT_POSITION_ATTITUDE_ERROR_MODEL_NONE \
	ASPN23_MEASUREMENT_POSITION_ATTITUDE_ERROR_MODEL_NONE
typedef enum Aspn23MeasurementPositionAttitudeErrorModel AspnMeasurementPositionAttitudeErrorModel;
typedef enum Aspn23MeasurementPositionAttitudeReferenceFrame
    AspnMeasurementPositionAttitudeReferenceFrame;

typedef Aspn23MeasurementPositionVelocityAttitude AspnMeasurementPositionVelocityAttitude;
#define aspn_measurement_position_velocity_attitude_new \
	aspn23_measurement_position_velocity_attitude_new
#define aspn_measurement_position_velocity_attitude_copy \
	aspn23_measurement_position_velocity_attitude_copy
#define aspn_measurement_position_velocity_attitude_free \
	aspn23_measurement_position_velocity_attitude_free
#define aspn_measurement_position_velocity_attitude_free_members \
	aspn23_measurement_position_velocity_attitude_free_members
#define ASPN_MEASUREMENT_POSITION_VELOCITY_ATTITUDE_REFERENCE_FRAME_ECI \
	ASPN23_MEASUREMENT_POSITION_VELOCITY_ATTITUDE_REFERENCE_FRAME_ECI
#define ASPN_MEASUREMENT_POSITION_VELOCITY_ATTITUDE_REFERENCE_FRAME_GEODETIC \
	ASPN23_MEASUREMENT_POSITION_VELOCITY_ATTITUDE_REFERENCE_FRAME_GEODETIC
#define ASPN_MEASUREMENT_POSITION_VELOCITY_ATTITUDE_ERROR_MODEL_NONE \
	ASPN23_MEASUREMENT_POSITION_VELOCITY_ATTITUDE_ERROR_MODEL_NONE
typedef enum Aspn23MeasurementPositionVelocityAttitudeErrorModel
    AspnMeasurementPositionVelocityAttitudeErrorModel;
typedef enum Aspn23MeasurementPositionVelocityAttitudeReferenceFrame
    AspnMeasurementPositionVelocityAttitudeReferenceFrame;

typedef Aspn23MeasurementRangeRateToPoint AspnMeasurementRangeRateToPoint;
#define aspn_measurement_range_rate_to_point_new aspn23_measurement_range_rate_to_point_new
#define aspn_measurement_range_rate_to_point_copy aspn23_measurement_range_rate_to_point_copy
#define aspn_measurement_range_rate_to_point_free aspn23_measurement_range_rate_to_point_free
#define aspn_measurement_range_rate_to_point_free_members \
	aspn23_measurement_range_rate_to_point_free_members
#define ASPN_MEASUREMENT_RANGE_RATE_TO_POINT_ERROR_MODEL_NONE \
	ASPN23_MEASUREMENT_RANGE_RATE_TO_POINT_ERROR_MODEL_NONE
typedef enum Aspn23MeasurementRangeRateToPointErrorModel AspnMeasurementRangeRateToPointErrorModel;

typedef Aspn23MeasurementRangeToPoint AspnMeasurementRangeToPoint;
#define aspn_measurement_range_to_point_new aspn23_measurement_range_to_point_new
#define aspn_measurement_range_to_point_copy aspn23_measurement_range_to_point_copy
#define aspn_measurement_range_to_point_free aspn23_measurement_range_to_point_free
#define aspn_measurement_range_to_point_free_members aspn23_measurement_range_to_point_free_members
#define ASPN_MEASUREMENT_RANGE_TO_POINT_ERROR_MODEL_NONE \
	ASPN23_MEASUREMENT_RANGE_TO_POINT_ERROR_MODEL_NONE
typedef enum Aspn23MeasurementRangeToPointErrorModel AspnMeasurementRangeToPointErrorModel;

typedef Aspn23MeasurementSatnav AspnMeasurementSatnav;
#define aspn_measurement_satnav_new aspn23_measurement_satnav_new
#define aspn_measurement_satnav_copy aspn23_measurement_satnav_copy
#define aspn_measurement_satnav_free aspn23_measurement_satnav_free
#define aspn_measurement_satnav_free_members aspn23_measurement_satnav_free_members

typedef Aspn23MeasurementSatnavSubframe AspnMeasurementSatnavSubframe;
#define aspn_measurement_satnav_subframe_new aspn23_measurement_satnav_subframe_new
#define aspn_measurement_satnav_subframe_copy aspn23_measurement_satnav_subframe_copy
#define aspn_measurement_satnav_subframe_free aspn23_measurement_satnav_subframe_free
#define aspn_measurement_satnav_subframe_free_members \
	aspn23_measurement_satnav_subframe_free_members

typedef Aspn23MeasurementSatnavWithSvData AspnMeasurementSatnavWithSvData;
#define aspn_measurement_satnav_with_sv_data_new aspn23_measurement_satnav_with_sv_data_new
#define aspn_measurement_satnav_with_sv_data_copy aspn23_measurement_satnav_with_sv_data_copy
#define aspn_measurement_satnav_with_sv_data_free aspn23_measurement_satnav_with_sv_data_free
#define aspn_measurement_satnav_with_sv_data_free_members \
	aspn23_measurement_satnav_with_sv_data_free_members

typedef Aspn23MeasurementSpecificForce1D AspnMeasurementSpecificForce1D;
#define aspn_measurement_specific_force_1d_new aspn23_measurement_specific_force_1d_new
#define aspn_measurement_specific_force_1d_copy aspn23_measurement_specific_force_1d_copy
#define aspn_measurement_specific_force_1d_free aspn23_measurement_specific_force_1d_free
#define aspn_measurement_specific_force_1d_free_members \
	aspn23_measurement_specific_force_1d_free_members
#define ASPN_MEASUREMENT_SPECIFIC_FORCE_1D_SENSOR_TYPE_INTEGRATED \
	ASPN23_MEASUREMENT_SPECIFIC_FORCE_1D_SENSOR_TYPE_INTEGRATED
#define ASPN_MEASUREMENT_SPECIFIC_FORCE_1D_SENSOR_TYPE_SAMPLED \
	ASPN23_MEASUREMENT_SPECIFIC_FORCE_1D_SENSOR_TYPE_SAMPLED
#define ASPN_MEASUREMENT_SPECIFIC_FORCE_1D_ERROR_MODEL_NONE \
	ASPN23_MEASUREMENT_SPECIFIC_FORCE_1D_ERROR_MODEL_NONE
typedef enum Aspn23MeasurementSpecificForce1DErrorModel AspnMeasurementSpecificForce1DErrorModel;
typedef enum Aspn23MeasurementSpecificForce1DSensorType AspnMeasurementSpecificForce1DSensorType;

typedef Aspn23MeasurementSpeed AspnMeasurementSpeed;
#define aspn_measurement_speed_new aspn23_measurement_speed_new
#define aspn_measurement_speed_copy aspn23_measurement_speed_copy
#define aspn_measurement_speed_free aspn23_measurement_speed_free
#define aspn_measurement_speed_free_members aspn23_measurement_speed_free_members
#define ASPN_MEASUREMENT_SPEED_REFERENCE_TAS ASPN23_MEASUREMENT_SPEED_REFERENCE_TAS
#define ASPN_MEASUREMENT_SPEED_REFERENCE_IAS ASPN23_MEASUREMENT_SPEED_REFERENCE_IAS
#define ASPN_MEASUREMENT_SPEED_REFERENCE_WATER ASPN23_MEASUREMENT_SPEED_REFERENCE_WATER
#define ASPN_MEASUREMENT_SPEED_REFERENCE_GROUND ASPN23_MEASUREMENT_SPEED_REFERENCE_GROUND
#define ASPN_MEASUREMENT_SPEED_ERROR_MODEL_NONE ASPN23_MEASUREMENT_SPEED_ERROR_MODEL_NONE
typedef enum Aspn23MeasurementSpeedErrorModel AspnMeasurementSpeedErrorModel;
typedef enum Aspn23MeasurementSpeedReference AspnMeasurementSpeedReference;

typedef Aspn23MeasurementTemperature AspnMeasurementTemperature;
#define aspn_measurement_temperature_new aspn23_measurement_temperature_new
#define aspn_measurement_temperature_copy aspn23_measurement_temperature_copy
#define aspn_measurement_temperature_free aspn23_measurement_temperature_free
#define aspn_measurement_temperature_free_members aspn23_measurement_temperature_free_members
#define ASPN_MEASUREMENT_TEMPERATURE_ERROR_MODEL_NONE \
	ASPN23_MEASUREMENT_TEMPERATURE_ERROR_MODEL_NONE
typedef enum Aspn23MeasurementTemperatureErrorModel AspnMeasurementTemperatureErrorModel;

typedef Aspn23MeasurementTime AspnMeasurementTime;
#define aspn_measurement_time_new aspn23_measurement_time_new
#define aspn_measurement_time_copy aspn23_measurement_time_copy
#define aspn_measurement_time_free aspn23_measurement_time_free
#define aspn_measurement_time_free_members aspn23_measurement_time_free_members
#define ASPN_MEASUREMENT_TIME_ERROR_MODEL_NONE ASPN23_MEASUREMENT_TIME_ERROR_MODEL_NONE
typedef enum Aspn23MeasurementTimeErrorModel AspnMeasurementTimeErrorModel;

typedef Aspn23MeasurementTimeDifference AspnMeasurementTimeDifference;
#define aspn_measurement_time_difference_new aspn23_measurement_time_difference_new
#define aspn_measurement_time_difference_copy aspn23_measurement_time_difference_copy
#define aspn_measurement_time_difference_free aspn23_measurement_time_difference_free
#define aspn_measurement_time_difference_free_members \
	aspn23_measurement_time_difference_free_members
#define ASPN_MEASUREMENT_TIME_DIFFERENCE_ERROR_MODEL_NONE \
	ASPN23_MEASUREMENT_TIME_DIFFERENCE_ERROR_MODEL_NONE
typedef enum Aspn23MeasurementTimeDifferenceErrorModel AspnMeasurementTimeDifferenceErrorModel;

typedef Aspn23MeasurementTimeFrequencyDifference AspnMeasurementTimeFrequencyDifference;
#define aspn_measurement_time_frequency_difference_new \
	aspn23_measurement_time_frequency_difference_new
#define aspn_measurement_time_frequency_difference_copy \
	aspn23_measurement_time_frequency_difference_copy
#define aspn_measurement_time_frequency_difference_free \
	aspn23_measurement_time_frequency_difference_free
#define aspn_measurement_time_frequency_difference_free_members \
	aspn23_measurement_time_frequency_difference_free_members
#define ASPN_MEASUREMENT_TIME_FREQUENCY_DIFFERENCE_ERROR_MODEL_NONE \
	ASPN23_MEASUREMENT_TIME_FREQUENCY_DIFFERENCE_ERROR_MODEL_NONE
typedef enum Aspn23MeasurementTimeFrequencyDifferenceErrorModel
    AspnMeasurementTimeFrequencyDifferenceErrorModel;

typedef Aspn23MeasurementVelocity AspnMeasurementVelocity;
#define aspn_measurement_velocity_new aspn23_measurement_velocity_new
#define aspn_measurement_velocity_copy aspn23_measurement_velocity_copy
#define aspn_measurement_velocity_free aspn23_measurement_velocity_free
#define aspn_measurement_velocity_free_members aspn23_measurement_velocity_free_members
#define ASPN_MEASUREMENT_VELOCITY_REFERENCE_FRAME_ECI \
	ASPN23_MEASUREMENT_VELOCITY_REFERENCE_FRAME_ECI
#define ASPN_MEASUREMENT_VELOCITY_REFERENCE_FRAME_ECEF \
	ASPN23_MEASUREMENT_VELOCITY_REFERENCE_FRAME_ECEF
#define ASPN_MEASUREMENT_VELOCITY_REFERENCE_FRAME_NED \
	ASPN23_MEASUREMENT_VELOCITY_REFERENCE_FRAME_NED
#define ASPN_MEASUREMENT_VELOCITY_REFERENCE_FRAME_SENSOR \
	ASPN23_MEASUREMENT_VELOCITY_REFERENCE_FRAME_SENSOR
#define ASPN_MEASUREMENT_VELOCITY_ERROR_MODEL_NONE ASPN23_MEASUREMENT_VELOCITY_ERROR_MODEL_NONE
typedef enum Aspn23MeasurementVelocityErrorModel AspnMeasurementVelocityErrorModel;
typedef enum Aspn23MeasurementVelocityReferenceFrame AspnMeasurementVelocityReferenceFrame;

#ifdef __cplusplus
}  // extern "C"
#endif
