
#pragma once

#ifdef __cplusplus
extern "C" {
#endif

/**
 * An enum containing the entire set of measurements and metadata in ASPN
 */
typedef enum Aspn23MessageType {
	/* ASPN_UNDEFINED should never be used. Indicates that uninitialized memory is being used */
	ASPN_UNDEFINED,
	ASPN_METADATA_BEIDOU_EPHEMERIS,
	ASPN_METADATA_GLONASS_EPHEMERIS,
	ASPN_METADATA_GPS_CNAV_EPHEMERIS,
	ASPN_METADATA_GPS_LNAV_EPHEMERIS,
	ASPN_METADATA_GPS_MNAV_EPHEMERIS,
	ASPN_METADATA_GPS_IONO_UTC_PARAMETERS,
	ASPN_METADATA_GALILEO_EPHEMERIS,
	ASPN_METADATA_IMU,
	ASPN_METADATA_GENERIC,
	ASPN_METADATA_IMAGE_FEATURES,
	ASPN_METADATA_MAGNETIC_FIELD,
	ASPN_METADATA_SATNAV_OBS,
	ASPN_MEASUREMENT_IMU,
	ASPN_MEASUREMENT_TDOA_1TX_2RX,
	ASPN_MEASUREMENT_TDOA_2TX_1RX,
	ASPN_MEASUREMENT_ACCUMULATED_DISTANCE_TRAVELED,
	ASPN_MEASUREMENT_ALTITUDE,
	ASPN_MEASUREMENT_ANGULAR_VELOCITY,
	ASPN_MEASUREMENT_ANGULAR_VELOCITY_1D,
	ASPN_MEASUREMENT_ATTITUDE_2D,
	ASPN_MEASUREMENT_ATTITUDE_3D,
	ASPN_MEASUREMENT_BAROMETER,
	ASPN_MEASUREMENT_DELTA_POSITION,
	ASPN_MEASUREMENT_DELTA_RANGE,
	ASPN_MEASUREMENT_DELTA_RANGE_TO_POINT,
	ASPN_MEASUREMENT_DIRECTION_2D_TO_POINTS,
	ASPN_MEASUREMENT_DIRECTION_3D_TO_POINTS,
	ASPN_MEASUREMENT_DIRECTION_OF_MOTION_2D,
	ASPN_MEASUREMENT_DIRECTION_OF_MOTION_3D,
	ASPN_MEASUREMENT_FREQUENCY_DIFFERENCE,
	ASPN_MEASUREMENT_HEADING,
	ASPN_MEASUREMENT_IMAGE,
	ASPN_MEASUREMENT_MAGNETIC_FIELD,
	ASPN_MEASUREMENT_MAGNETIC_FIELD_MAGNITUDE,
	ASPN_MEASUREMENT_POSITION,
	ASPN_MEASUREMENT_POSITION_ATTITUDE,
	ASPN_MEASUREMENT_POSITION_VELOCITY_ATTITUDE,
	ASPN_MEASUREMENT_RANGE_RATE_TO_POINT,
	ASPN_MEASUREMENT_RANGE_TO_POINT,
	ASPN_MEASUREMENT_SATNAV,
	ASPN_MEASUREMENT_SATNAV_SUBFRAME,
	ASPN_MEASUREMENT_SATNAV_WITH_SV_DATA,
	ASPN_MEASUREMENT_SPECIFIC_FORCE_1D,
	ASPN_MEASUREMENT_SPEED,
	ASPN_MEASUREMENT_TEMPERATURE,
	ASPN_MEASUREMENT_TIME,
	ASPN_MEASUREMENT_TIME_DIFFERENCE,
	ASPN_MEASUREMENT_TIME_FREQUENCY_DIFFERENCE,
	ASPN_MEASUREMENT_VELOCITY,
	ASPN_LAST_MESSAGE = ASPN_MEASUREMENT_VELOCITY,
	/*
	The values between ASPN_EXTENDED_BEGIN and ASPN_EXTENDED_END are reserved for extensions to
	ASPN. ASPN users may use these values for implementation-specific messages. Users utilizing
	these values must ensure all implementations coordinate on the interpretation of these values.
	These values should also begin with "ASPN_EXTENDED_". The types associated with these additional
	enum values should begin with "AspnExtended". For example, a new enum value might be called
	ASPN_EXTENDED_COMPASS_RESET with a corresponding struct named AspnExtendedCompassReset.

	Any values before ASPN_EXTENDED_BEGIN are reserved for usage by future ASPN revisions. Users
	must not use any value between ASPN_LAST_MESSAGE and ASPN_EXTENDED_BEGIN until those values are
	specified by a future ASPN revision.
	*/
	ASPN_EXTENDED_BEGIN = 0x2000,
	ASPN_EXTENDED_END   = 0xFFFF,
} Aspn23MessageType;

#define ASPN_NUM_MESSAGES 50

void aspn23_free(void* pointer);

char* aspn23_runtime_type_get_name(Aspn23MessageType type);

#ifdef __cplusplus
}
#endif
