// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file MeasurementVelocity.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_ASPN23_DDS_MEASUREMENTVELOCITY_H_
#define _FAST_DDS_GENERATED_ASPN23_DDS_MEASUREMENTVELOCITY_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>

#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>

#include "TypeHeader.h"
#include "TypeTimestamp.h"
#include "TypeIntegrity.h"


#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(MEASUREMENTVELOCITY_SOURCE)
#define MEASUREMENTVELOCITY_DllAPI __declspec( dllexport )
#else
#define MEASUREMENTVELOCITY_DllAPI __declspec( dllimport )
#endif // MEASUREMENTVELOCITY_SOURCE
#else
#define MEASUREMENTVELOCITY_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define MEASUREMENTVELOCITY_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima



namespace aspn23_dds {

/*!
 * @brief This class represents the enumeration MeasurementVelocityReferenceFrameValue defined by the user in the IDL file.
 * @ingroup MeasurementVelocity
 */
enum MeasurementVelocityReferenceFrameValue : uint32_t
{
    ASPN23_MEASUREMENT_VELOCITY_REFERENCE_FRAME_ECI,
    ASPN23_MEASUREMENT_VELOCITY_REFERENCE_FRAME_ECEF,
    ASPN23_MEASUREMENT_VELOCITY_REFERENCE_FRAME_NED,
    ASPN23_MEASUREMENT_VELOCITY_REFERENCE_FRAME_SENSOR
};
/*!
 * @brief This class represents the enumeration MeasurementVelocityErrorModelValue defined by the user in the IDL file.
 * @ingroup MeasurementVelocity
 */
enum MeasurementVelocityErrorModelValue : uint32_t
{
    ASPN23_MEASUREMENT_VELOCITY_ERROR_MODEL_NONE
};




/*!
 * @brief This class represents the structure MeasurementVelocity defined by the user in the IDL file.
 * @ingroup MeasurementVelocity
 */
class MeasurementVelocity
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport MeasurementVelocity();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~MeasurementVelocity();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object aspn23_dds::MeasurementVelocity that will be copied.
     */
    eProsima_user_DllExport MeasurementVelocity(
            const MeasurementVelocity& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object aspn23_dds::MeasurementVelocity that will be copied.
     */
    eProsima_user_DllExport MeasurementVelocity(
            MeasurementVelocity&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object aspn23_dds::MeasurementVelocity that will be copied.
     */
    eProsima_user_DllExport MeasurementVelocity& operator =(
            const MeasurementVelocity& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object aspn23_dds::MeasurementVelocity that will be copied.
     */
    eProsima_user_DllExport MeasurementVelocity& operator =(
            MeasurementVelocity&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x aspn23_dds::MeasurementVelocity object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const MeasurementVelocity& x) const;

    /*!
     * @brief Comparison operator.
     * @param x aspn23_dds::MeasurementVelocity object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const MeasurementVelocity& x) const;

    /*!
     * @brief This function copies the value in member header
     * @param _header New value to be copied in member header
     */
    eProsima_user_DllExport void header(
            const aspn23_dds::TypeHeader& _header);

    /*!
     * @brief This function moves the value in member header
     * @param _header New value to be moved in member header
     */
    eProsima_user_DllExport void header(
            aspn23_dds::TypeHeader&& _header);

    /*!
     * @brief This function returns a constant reference to member header
     * @return Constant reference to member header
     */
    eProsima_user_DllExport const aspn23_dds::TypeHeader& header() const;

    /*!
     * @brief This function returns a reference to member header
     * @return Reference to member header
     */
    eProsima_user_DllExport aspn23_dds::TypeHeader& header();


    /*!
     * @brief This function copies the value in member time_of_validity
     * @param _time_of_validity New value to be copied in member time_of_validity
     */
    eProsima_user_DllExport void time_of_validity(
            const aspn23_dds::TypeTimestamp& _time_of_validity);

    /*!
     * @brief This function moves the value in member time_of_validity
     * @param _time_of_validity New value to be moved in member time_of_validity
     */
    eProsima_user_DllExport void time_of_validity(
            aspn23_dds::TypeTimestamp&& _time_of_validity);

    /*!
     * @brief This function returns a constant reference to member time_of_validity
     * @return Constant reference to member time_of_validity
     */
    eProsima_user_DllExport const aspn23_dds::TypeTimestamp& time_of_validity() const;

    /*!
     * @brief This function returns a reference to member time_of_validity
     * @return Reference to member time_of_validity
     */
    eProsima_user_DllExport aspn23_dds::TypeTimestamp& time_of_validity();


    /*!
     * @brief This function sets a value in member reference_frame
     * @param _reference_frame New value for member reference_frame
     */
    eProsima_user_DllExport void reference_frame(
            aspn23_dds::MeasurementVelocityReferenceFrameValue _reference_frame);

    /*!
     * @brief This function returns the value of member reference_frame
     * @return Value of member reference_frame
     */
    eProsima_user_DllExport aspn23_dds::MeasurementVelocityReferenceFrameValue reference_frame() const;

    /*!
     * @brief This function returns a reference to member reference_frame
     * @return Reference to member reference_frame
     */
    eProsima_user_DllExport aspn23_dds::MeasurementVelocityReferenceFrameValue& reference_frame();


    /*!
     * @brief This function copies the value in member x
     * @param _x New value to be copied in member x
     */
    eProsima_user_DllExport void x(
            const eprosima::fastcdr::optional<double>& _x);

    /*!
     * @brief This function moves the value in member x
     * @param _x New value to be moved in member x
     */
    eProsima_user_DllExport void x(
            eprosima::fastcdr::optional<double>&& _x);

    /*!
     * @brief This function returns a constant reference to member x
     * @return Constant reference to member x
     */
    eProsima_user_DllExport const eprosima::fastcdr::optional<double>& x() const;

    /*!
     * @brief This function returns a reference to member x
     * @return Reference to member x
     */
    eProsima_user_DllExport eprosima::fastcdr::optional<double>& x();


    /*!
     * @brief This function copies the value in member y
     * @param _y New value to be copied in member y
     */
    eProsima_user_DllExport void y(
            const eprosima::fastcdr::optional<double>& _y);

    /*!
     * @brief This function moves the value in member y
     * @param _y New value to be moved in member y
     */
    eProsima_user_DllExport void y(
            eprosima::fastcdr::optional<double>&& _y);

    /*!
     * @brief This function returns a constant reference to member y
     * @return Constant reference to member y
     */
    eProsima_user_DllExport const eprosima::fastcdr::optional<double>& y() const;

    /*!
     * @brief This function returns a reference to member y
     * @return Reference to member y
     */
    eProsima_user_DllExport eprosima::fastcdr::optional<double>& y();


    /*!
     * @brief This function copies the value in member z
     * @param _z New value to be copied in member z
     */
    eProsima_user_DllExport void z(
            const eprosima::fastcdr::optional<double>& _z);

    /*!
     * @brief This function moves the value in member z
     * @param _z New value to be moved in member z
     */
    eProsima_user_DllExport void z(
            eprosima::fastcdr::optional<double>&& _z);

    /*!
     * @brief This function returns a constant reference to member z
     * @return Constant reference to member z
     */
    eProsima_user_DllExport const eprosima::fastcdr::optional<double>& z() const;

    /*!
     * @brief This function returns a reference to member z
     * @return Reference to member z
     */
    eProsima_user_DllExport eprosima::fastcdr::optional<double>& z();


    /*!
     * @brief This function sets a value in member num_meas
     * @param _num_meas New value for member num_meas
     */
    eProsima_user_DllExport void num_meas(
            uint8_t _num_meas);

    /*!
     * @brief This function returns the value of member num_meas
     * @return Value of member num_meas
     */
    eProsima_user_DllExport uint8_t num_meas() const;

    /*!
     * @brief This function returns a reference to member num_meas
     * @return Reference to member num_meas
     */
    eProsima_user_DllExport uint8_t& num_meas();


    /*!
     * @brief This function copies the value in member covariance
     * @param _covariance New value to be copied in member covariance
     */
    eProsima_user_DllExport void covariance(
            const std::vector<double>& _covariance);

    /*!
     * @brief This function moves the value in member covariance
     * @param _covariance New value to be moved in member covariance
     */
    eProsima_user_DllExport void covariance(
            std::vector<double>&& _covariance);

    /*!
     * @brief This function returns a constant reference to member covariance
     * @return Constant reference to member covariance
     */
    eProsima_user_DllExport const std::vector<double>& covariance() const;

    /*!
     * @brief This function returns a reference to member covariance
     * @return Reference to member covariance
     */
    eProsima_user_DllExport std::vector<double>& covariance();


    /*!
     * @brief This function sets a value in member error_model
     * @param _error_model New value for member error_model
     */
    eProsima_user_DllExport void error_model(
            aspn23_dds::MeasurementVelocityErrorModelValue _error_model);

    /*!
     * @brief This function returns the value of member error_model
     * @return Value of member error_model
     */
    eProsima_user_DllExport aspn23_dds::MeasurementVelocityErrorModelValue error_model() const;

    /*!
     * @brief This function returns a reference to member error_model
     * @return Reference to member error_model
     */
    eProsima_user_DllExport aspn23_dds::MeasurementVelocityErrorModelValue& error_model();


    /*!
     * @brief This function sets a value in member num_error_model_params
     * @param _num_error_model_params New value for member num_error_model_params
     */
    eProsima_user_DllExport void num_error_model_params(
            uint16_t _num_error_model_params);

    /*!
     * @brief This function returns the value of member num_error_model_params
     * @return Value of member num_error_model_params
     */
    eProsima_user_DllExport uint16_t num_error_model_params() const;

    /*!
     * @brief This function returns a reference to member num_error_model_params
     * @return Reference to member num_error_model_params
     */
    eProsima_user_DllExport uint16_t& num_error_model_params();


    /*!
     * @brief This function copies the value in member error_model_params
     * @param _error_model_params New value to be copied in member error_model_params
     */
    eProsima_user_DllExport void error_model_params(
            const std::vector<double>& _error_model_params);

    /*!
     * @brief This function moves the value in member error_model_params
     * @param _error_model_params New value to be moved in member error_model_params
     */
    eProsima_user_DllExport void error_model_params(
            std::vector<double>&& _error_model_params);

    /*!
     * @brief This function returns a constant reference to member error_model_params
     * @return Constant reference to member error_model_params
     */
    eProsima_user_DllExport const std::vector<double>& error_model_params() const;

    /*!
     * @brief This function returns a reference to member error_model_params
     * @return Reference to member error_model_params
     */
    eProsima_user_DllExport std::vector<double>& error_model_params();


    /*!
     * @brief This function sets a value in member num_integrity
     * @param _num_integrity New value for member num_integrity
     */
    eProsima_user_DllExport void num_integrity(
            uint8_t _num_integrity);

    /*!
     * @brief This function returns the value of member num_integrity
     * @return Value of member num_integrity
     */
    eProsima_user_DllExport uint8_t num_integrity() const;

    /*!
     * @brief This function returns a reference to member num_integrity
     * @return Reference to member num_integrity
     */
    eProsima_user_DllExport uint8_t& num_integrity();


    /*!
     * @brief This function copies the value in member integrity
     * @param _integrity New value to be copied in member integrity
     */
    eProsima_user_DllExport void integrity(
            const std::vector<aspn23_dds::TypeIntegrity>& _integrity);

    /*!
     * @brief This function moves the value in member integrity
     * @param _integrity New value to be moved in member integrity
     */
    eProsima_user_DllExport void integrity(
            std::vector<aspn23_dds::TypeIntegrity>&& _integrity);

    /*!
     * @brief This function returns a constant reference to member integrity
     * @return Constant reference to member integrity
     */
    eProsima_user_DllExport const std::vector<aspn23_dds::TypeIntegrity>& integrity() const;

    /*!
     * @brief This function returns a reference to member integrity
     * @return Reference to member integrity
     */
    eProsima_user_DllExport std::vector<aspn23_dds::TypeIntegrity>& integrity();

private:

    aspn23_dds::TypeHeader m_header;
    aspn23_dds::TypeTimestamp m_time_of_validity;
    aspn23_dds::MeasurementVelocityReferenceFrameValue m_reference_frame{aspn23_dds::ASPN23_MEASUREMENT_VELOCITY_REFERENCE_FRAME_ECI};
    eprosima::fastcdr::optional<double> m_x;
    eprosima::fastcdr::optional<double> m_y;
    eprosima::fastcdr::optional<double> m_z;
    uint8_t m_num_meas{0};
    std::vector<double> m_covariance;
    aspn23_dds::MeasurementVelocityErrorModelValue m_error_model{aspn23_dds::ASPN23_MEASUREMENT_VELOCITY_ERROR_MODEL_NONE};
    uint16_t m_num_error_model_params{0};
    std::vector<double> m_error_model_params;
    uint8_t m_num_integrity{0};
    std::vector<aspn23_dds::TypeIntegrity> m_integrity;

};

} // namespace aspn23_dds

#endif // _FAST_DDS_GENERATED_ASPN23_DDS_MEASUREMENTVELOCITY_H_



