// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file MeasurementImage.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_ASPN23_DDS_MEASUREMENTIMAGE_H_
#define _FAST_DDS_GENERATED_ASPN23_DDS_MEASUREMENTIMAGE_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>

#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>

#include "TypeHeader.h"
#include "TypeTimestamp.h"
#include "TypeIntegrity.h"


#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(MEASUREMENTIMAGE_SOURCE)
#define MEASUREMENTIMAGE_DllAPI __declspec( dllexport )
#else
#define MEASUREMENTIMAGE_DllAPI __declspec( dllimport )
#endif // MEASUREMENTIMAGE_SOURCE
#else
#define MEASUREMENTIMAGE_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define MEASUREMENTIMAGE_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima



namespace aspn23_dds {

/*!
 * @brief This class represents the enumeration MeasurementImageImageTypeValue defined by the user in the IDL file.
 * @ingroup MeasurementImage
 */
enum MeasurementImageImageTypeValue : uint32_t
{
    ASPN23_MEASUREMENT_IMAGE_IMAGE_TYPE_BMP,
    ASPN23_MEASUREMENT_IMAGE_IMAGE_TYPE_PNG,
    ASPN23_MEASUREMENT_IMAGE_IMAGE_TYPE_JPG,
    ASPN23_MEASUREMENT_IMAGE_IMAGE_TYPE_TIFF,
    ASPN23_MEASUREMENT_IMAGE_IMAGE_TYPE_RAW_GRAY8,
    ASPN23_MEASUREMENT_IMAGE_IMAGE_TYPE_RAW_RGB8,
    ASPN23_MEASUREMENT_IMAGE_IMAGE_TYPE_RAW_BGR8,
    ASPN23_MEASUREMENT_IMAGE_IMAGE_TYPE_RAW_RGBA8,
    ASPN23_MEASUREMENT_IMAGE_IMAGE_TYPE_RAW_BGRA8,
    ASPN23_MEASUREMENT_IMAGE_IMAGE_TYPE_RAW_GRAY16,
    ASPN23_MEASUREMENT_IMAGE_IMAGE_TYPE_RAW_GRAYFLOAT64
};
/*!
 * @brief This class represents the enumeration MeasurementImageCameraModelValue defined by the user in the IDL file.
 * @ingroup MeasurementImage
 */
enum MeasurementImageCameraModelValue : uint32_t
{
    ASPN23_MEASUREMENT_IMAGE_CAMERA_MODEL_ASPN_PINHOLE_PLUMB_BOB,
    ASPN23_MEASUREMENT_IMAGE_CAMERA_MODEL_ASPN_LINEAR_MODEL
};




/*!
 * @brief This class represents the structure MeasurementImage defined by the user in the IDL file.
 * @ingroup MeasurementImage
 */
class MeasurementImage
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport MeasurementImage();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~MeasurementImage();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object aspn23_dds::MeasurementImage that will be copied.
     */
    eProsima_user_DllExport MeasurementImage(
            const MeasurementImage& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object aspn23_dds::MeasurementImage that will be copied.
     */
    eProsima_user_DllExport MeasurementImage(
            MeasurementImage&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object aspn23_dds::MeasurementImage that will be copied.
     */
    eProsima_user_DllExport MeasurementImage& operator =(
            const MeasurementImage& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object aspn23_dds::MeasurementImage that will be copied.
     */
    eProsima_user_DllExport MeasurementImage& operator =(
            MeasurementImage&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x aspn23_dds::MeasurementImage object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const MeasurementImage& x) const;

    /*!
     * @brief Comparison operator.
     * @param x aspn23_dds::MeasurementImage object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const MeasurementImage& x) const;

    /*!
     * @brief This function copies the value in member header
     * @param _header New value to be copied in member header
     */
    eProsima_user_DllExport void header(
            const aspn23_dds::TypeHeader& _header);

    /*!
     * @brief This function moves the value in member header
     * @param _header New value to be moved in member header
     */
    eProsima_user_DllExport void header(
            aspn23_dds::TypeHeader&& _header);

    /*!
     * @brief This function returns a constant reference to member header
     * @return Constant reference to member header
     */
    eProsima_user_DllExport const aspn23_dds::TypeHeader& header() const;

    /*!
     * @brief This function returns a reference to member header
     * @return Reference to member header
     */
    eProsima_user_DllExport aspn23_dds::TypeHeader& header();


    /*!
     * @brief This function copies the value in member time_of_validity
     * @param _time_of_validity New value to be copied in member time_of_validity
     */
    eProsima_user_DllExport void time_of_validity(
            const aspn23_dds::TypeTimestamp& _time_of_validity);

    /*!
     * @brief This function moves the value in member time_of_validity
     * @param _time_of_validity New value to be moved in member time_of_validity
     */
    eProsima_user_DllExport void time_of_validity(
            aspn23_dds::TypeTimestamp&& _time_of_validity);

    /*!
     * @brief This function returns a constant reference to member time_of_validity
     * @return Constant reference to member time_of_validity
     */
    eProsima_user_DllExport const aspn23_dds::TypeTimestamp& time_of_validity() const;

    /*!
     * @brief This function returns a reference to member time_of_validity
     * @return Reference to member time_of_validity
     */
    eProsima_user_DllExport aspn23_dds::TypeTimestamp& time_of_validity();


    /*!
     * @brief This function sets a value in member height
     * @param _height New value for member height
     */
    eProsima_user_DllExport void height(
            uint32_t _height);

    /*!
     * @brief This function returns the value of member height
     * @return Value of member height
     */
    eProsima_user_DllExport uint32_t height() const;

    /*!
     * @brief This function returns a reference to member height
     * @return Reference to member height
     */
    eProsima_user_DllExport uint32_t& height();


    /*!
     * @brief This function sets a value in member width
     * @param _width New value for member width
     */
    eProsima_user_DllExport void width(
            uint32_t _width);

    /*!
     * @brief This function returns the value of member width
     * @return Value of member width
     */
    eProsima_user_DllExport uint32_t width() const;

    /*!
     * @brief This function returns a reference to member width
     * @return Reference to member width
     */
    eProsima_user_DllExport uint32_t& width();


    /*!
     * @brief This function sets a value in member is_bigendian
     * @param _is_bigendian New value for member is_bigendian
     */
    eProsima_user_DllExport void is_bigendian(
            bool _is_bigendian);

    /*!
     * @brief This function returns the value of member is_bigendian
     * @return Value of member is_bigendian
     */
    eProsima_user_DllExport bool is_bigendian() const;

    /*!
     * @brief This function returns a reference to member is_bigendian
     * @return Reference to member is_bigendian
     */
    eProsima_user_DllExport bool& is_bigendian();


    /*!
     * @brief This function sets a value in member image_type
     * @param _image_type New value for member image_type
     */
    eProsima_user_DllExport void image_type(
            aspn23_dds::MeasurementImageImageTypeValue _image_type);

    /*!
     * @brief This function returns the value of member image_type
     * @return Value of member image_type
     */
    eProsima_user_DllExport aspn23_dds::MeasurementImageImageTypeValue image_type() const;

    /*!
     * @brief This function returns a reference to member image_type
     * @return Reference to member image_type
     */
    eProsima_user_DllExport aspn23_dds::MeasurementImageImageTypeValue& image_type();


    /*!
     * @brief This function sets a value in member image_data_length
     * @param _image_data_length New value for member image_data_length
     */
    eProsima_user_DllExport void image_data_length(
            uint64_t _image_data_length);

    /*!
     * @brief This function returns the value of member image_data_length
     * @return Value of member image_data_length
     */
    eProsima_user_DllExport uint64_t image_data_length() const;

    /*!
     * @brief This function returns a reference to member image_data_length
     * @return Reference to member image_data_length
     */
    eProsima_user_DllExport uint64_t& image_data_length();


    /*!
     * @brief This function copies the value in member image_data
     * @param _image_data New value to be copied in member image_data
     */
    eProsima_user_DllExport void image_data(
            const std::vector<uint8_t>& _image_data);

    /*!
     * @brief This function moves the value in member image_data
     * @param _image_data New value to be moved in member image_data
     */
    eProsima_user_DllExport void image_data(
            std::vector<uint8_t>&& _image_data);

    /*!
     * @brief This function returns a constant reference to member image_data
     * @return Constant reference to member image_data
     */
    eProsima_user_DllExport const std::vector<uint8_t>& image_data() const;

    /*!
     * @brief This function returns a reference to member image_data
     * @return Reference to member image_data
     */
    eProsima_user_DllExport std::vector<uint8_t>& image_data();


    /*!
     * @brief This function sets a value in member camera_model
     * @param _camera_model New value for member camera_model
     */
    eProsima_user_DllExport void camera_model(
            aspn23_dds::MeasurementImageCameraModelValue _camera_model);

    /*!
     * @brief This function returns the value of member camera_model
     * @return Value of member camera_model
     */
    eProsima_user_DllExport aspn23_dds::MeasurementImageCameraModelValue camera_model() const;

    /*!
     * @brief This function returns a reference to member camera_model
     * @return Reference to member camera_model
     */
    eProsima_user_DllExport aspn23_dds::MeasurementImageCameraModelValue& camera_model();


    /*!
     * @brief This function sets a value in member num_model_coefficients
     * @param _num_model_coefficients New value for member num_model_coefficients
     */
    eProsima_user_DllExport void num_model_coefficients(
            uint8_t _num_model_coefficients);

    /*!
     * @brief This function returns the value of member num_model_coefficients
     * @return Value of member num_model_coefficients
     */
    eProsima_user_DllExport uint8_t num_model_coefficients() const;

    /*!
     * @brief This function returns a reference to member num_model_coefficients
     * @return Reference to member num_model_coefficients
     */
    eProsima_user_DllExport uint8_t& num_model_coefficients();


    /*!
     * @brief This function copies the value in member model_coefficients
     * @param _model_coefficients New value to be copied in member model_coefficients
     */
    eProsima_user_DllExport void model_coefficients(
            const std::vector<double>& _model_coefficients);

    /*!
     * @brief This function moves the value in member model_coefficients
     * @param _model_coefficients New value to be moved in member model_coefficients
     */
    eProsima_user_DllExport void model_coefficients(
            std::vector<double>&& _model_coefficients);

    /*!
     * @brief This function returns a constant reference to member model_coefficients
     * @return Constant reference to member model_coefficients
     */
    eProsima_user_DllExport const std::vector<double>& model_coefficients() const;

    /*!
     * @brief This function returns a reference to member model_coefficients
     * @return Reference to member model_coefficients
     */
    eProsima_user_DllExport std::vector<double>& model_coefficients();


    /*!
     * @brief This function sets a value in member num_integrity
     * @param _num_integrity New value for member num_integrity
     */
    eProsima_user_DllExport void num_integrity(
            uint8_t _num_integrity);

    /*!
     * @brief This function returns the value of member num_integrity
     * @return Value of member num_integrity
     */
    eProsima_user_DllExport uint8_t num_integrity() const;

    /*!
     * @brief This function returns a reference to member num_integrity
     * @return Reference to member num_integrity
     */
    eProsima_user_DllExport uint8_t& num_integrity();


    /*!
     * @brief This function copies the value in member integrity
     * @param _integrity New value to be copied in member integrity
     */
    eProsima_user_DllExport void integrity(
            const std::vector<aspn23_dds::TypeIntegrity>& _integrity);

    /*!
     * @brief This function moves the value in member integrity
     * @param _integrity New value to be moved in member integrity
     */
    eProsima_user_DllExport void integrity(
            std::vector<aspn23_dds::TypeIntegrity>&& _integrity);

    /*!
     * @brief This function returns a constant reference to member integrity
     * @return Constant reference to member integrity
     */
    eProsima_user_DllExport const std::vector<aspn23_dds::TypeIntegrity>& integrity() const;

    /*!
     * @brief This function returns a reference to member integrity
     * @return Reference to member integrity
     */
    eProsima_user_DllExport std::vector<aspn23_dds::TypeIntegrity>& integrity();

private:

    aspn23_dds::TypeHeader m_header;
    aspn23_dds::TypeTimestamp m_time_of_validity;
    uint32_t m_height{0};
    uint32_t m_width{0};
    bool m_is_bigendian{false};
    aspn23_dds::MeasurementImageImageTypeValue m_image_type{aspn23_dds::ASPN23_MEASUREMENT_IMAGE_IMAGE_TYPE_BMP};
    uint64_t m_image_data_length{0};
    std::vector<uint8_t> m_image_data;
    aspn23_dds::MeasurementImageCameraModelValue m_camera_model{aspn23_dds::ASPN23_MEASUREMENT_IMAGE_CAMERA_MODEL_ASPN_PINHOLE_PLUMB_BOB};
    uint8_t m_num_model_coefficients{0};
    std::vector<double> m_model_coefficients;
    uint8_t m_num_integrity{0};
    std::vector<aspn23_dds::TypeIntegrity> m_integrity;

};

} // namespace aspn23_dds

#endif // _FAST_DDS_GENERATED_ASPN23_DDS_MEASUREMENTIMAGE_H_



