// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file MeasurementSatnavWithSvData.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_ASPN23_DDS_MEASUREMENTSATNAVWITHSVDATA_H_
#define _FAST_DDS_GENERATED_ASPN23_DDS_MEASUREMENTSATNAVWITHSVDATA_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>

#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>

#include "TypeHeader.h"
#include "TypeTimestamp.h"
#include "TypeSatnavSvData.h"
#include "TypeIntegrity.h"
#include "TypeSatnavObs.h"


#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(MEASUREMENTSATNAVWITHSVDATA_SOURCE)
#define MEASUREMENTSATNAVWITHSVDATA_DllAPI __declspec( dllexport )
#else
#define MEASUREMENTSATNAVWITHSVDATA_DllAPI __declspec( dllimport )
#endif // MEASUREMENTSATNAVWITHSVDATA_SOURCE
#else
#define MEASUREMENTSATNAVWITHSVDATA_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define MEASUREMENTSATNAVWITHSVDATA_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima



namespace aspn23_dds {





/*!
 * @brief This class represents the structure MeasurementSatnavWithSvData defined by the user in the IDL file.
 * @ingroup MeasurementSatnavWithSvData
 */
class MeasurementSatnavWithSvData
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport MeasurementSatnavWithSvData();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~MeasurementSatnavWithSvData();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object aspn23_dds::MeasurementSatnavWithSvData that will be copied.
     */
    eProsima_user_DllExport MeasurementSatnavWithSvData(
            const MeasurementSatnavWithSvData& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object aspn23_dds::MeasurementSatnavWithSvData that will be copied.
     */
    eProsima_user_DllExport MeasurementSatnavWithSvData(
            MeasurementSatnavWithSvData&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object aspn23_dds::MeasurementSatnavWithSvData that will be copied.
     */
    eProsima_user_DllExport MeasurementSatnavWithSvData& operator =(
            const MeasurementSatnavWithSvData& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object aspn23_dds::MeasurementSatnavWithSvData that will be copied.
     */
    eProsima_user_DllExport MeasurementSatnavWithSvData& operator =(
            MeasurementSatnavWithSvData&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x aspn23_dds::MeasurementSatnavWithSvData object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const MeasurementSatnavWithSvData& x) const;

    /*!
     * @brief Comparison operator.
     * @param x aspn23_dds::MeasurementSatnavWithSvData object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const MeasurementSatnavWithSvData& x) const;

    /*!
     * @brief This function copies the value in member header
     * @param _header New value to be copied in member header
     */
    eProsima_user_DllExport void header(
            const aspn23_dds::TypeHeader& _header);

    /*!
     * @brief This function moves the value in member header
     * @param _header New value to be moved in member header
     */
    eProsima_user_DllExport void header(
            aspn23_dds::TypeHeader&& _header);

    /*!
     * @brief This function returns a constant reference to member header
     * @return Constant reference to member header
     */
    eProsima_user_DllExport const aspn23_dds::TypeHeader& header() const;

    /*!
     * @brief This function returns a reference to member header
     * @return Reference to member header
     */
    eProsima_user_DllExport aspn23_dds::TypeHeader& header();


    /*!
     * @brief This function copies the value in member time_of_validity
     * @param _time_of_validity New value to be copied in member time_of_validity
     */
    eProsima_user_DllExport void time_of_validity(
            const aspn23_dds::TypeTimestamp& _time_of_validity);

    /*!
     * @brief This function moves the value in member time_of_validity
     * @param _time_of_validity New value to be moved in member time_of_validity
     */
    eProsima_user_DllExport void time_of_validity(
            aspn23_dds::TypeTimestamp&& _time_of_validity);

    /*!
     * @brief This function returns a constant reference to member time_of_validity
     * @return Constant reference to member time_of_validity
     */
    eProsima_user_DllExport const aspn23_dds::TypeTimestamp& time_of_validity() const;

    /*!
     * @brief This function returns a reference to member time_of_validity
     * @return Reference to member time_of_validity
     */
    eProsima_user_DllExport aspn23_dds::TypeTimestamp& time_of_validity();


    /*!
     * @brief This function copies the value in member receiver_clock_time
     * @param _receiver_clock_time New value to be copied in member receiver_clock_time
     */
    eProsima_user_DllExport void receiver_clock_time(
            const aspn23_dds::TypeSatnavTime& _receiver_clock_time);

    /*!
     * @brief This function moves the value in member receiver_clock_time
     * @param _receiver_clock_time New value to be moved in member receiver_clock_time
     */
    eProsima_user_DllExport void receiver_clock_time(
            aspn23_dds::TypeSatnavTime&& _receiver_clock_time);

    /*!
     * @brief This function returns a constant reference to member receiver_clock_time
     * @return Constant reference to member receiver_clock_time
     */
    eProsima_user_DllExport const aspn23_dds::TypeSatnavTime& receiver_clock_time() const;

    /*!
     * @brief This function returns a reference to member receiver_clock_time
     * @return Reference to member receiver_clock_time
     */
    eProsima_user_DllExport aspn23_dds::TypeSatnavTime& receiver_clock_time();


    /*!
     * @brief This function sets a value in member num_signal_types
     * @param _num_signal_types New value for member num_signal_types
     */
    eProsima_user_DllExport void num_signal_types(
            uint16_t _num_signal_types);

    /*!
     * @brief This function returns the value of member num_signal_types
     * @return Value of member num_signal_types
     */
    eProsima_user_DllExport uint16_t num_signal_types() const;

    /*!
     * @brief This function returns a reference to member num_signal_types
     * @return Reference to member num_signal_types
     */
    eProsima_user_DllExport uint16_t& num_signal_types();


    /*!
     * @brief This function sets a value in member num_signals_tracked
     * @param _num_signals_tracked New value for member num_signals_tracked
     */
    eProsima_user_DllExport void num_signals_tracked(
            uint16_t _num_signals_tracked);

    /*!
     * @brief This function returns the value of member num_signals_tracked
     * @return Value of member num_signals_tracked
     */
    eProsima_user_DllExport uint16_t num_signals_tracked() const;

    /*!
     * @brief This function returns a reference to member num_signals_tracked
     * @return Reference to member num_signals_tracked
     */
    eProsima_user_DllExport uint16_t& num_signals_tracked();


    /*!
     * @brief This function copies the value in member obs
     * @param _obs New value to be copied in member obs
     */
    eProsima_user_DllExport void obs(
            const std::vector<aspn23_dds::TypeSatnavObs>& _obs);

    /*!
     * @brief This function moves the value in member obs
     * @param _obs New value to be moved in member obs
     */
    eProsima_user_DllExport void obs(
            std::vector<aspn23_dds::TypeSatnavObs>&& _obs);

    /*!
     * @brief This function returns a constant reference to member obs
     * @return Constant reference to member obs
     */
    eProsima_user_DllExport const std::vector<aspn23_dds::TypeSatnavObs>& obs() const;

    /*!
     * @brief This function returns a reference to member obs
     * @return Reference to member obs
     */
    eProsima_user_DllExport std::vector<aspn23_dds::TypeSatnavObs>& obs();


    /*!
     * @brief This function copies the value in member sv_data
     * @param _sv_data New value to be copied in member sv_data
     */
    eProsima_user_DllExport void sv_data(
            const std::vector<aspn23_dds::TypeSatnavSvData>& _sv_data);

    /*!
     * @brief This function moves the value in member sv_data
     * @param _sv_data New value to be moved in member sv_data
     */
    eProsima_user_DllExport void sv_data(
            std::vector<aspn23_dds::TypeSatnavSvData>&& _sv_data);

    /*!
     * @brief This function returns a constant reference to member sv_data
     * @return Constant reference to member sv_data
     */
    eProsima_user_DllExport const std::vector<aspn23_dds::TypeSatnavSvData>& sv_data() const;

    /*!
     * @brief This function returns a reference to member sv_data
     * @return Reference to member sv_data
     */
    eProsima_user_DllExport std::vector<aspn23_dds::TypeSatnavSvData>& sv_data();


    /*!
     * @brief This function sets a value in member num_integrity
     * @param _num_integrity New value for member num_integrity
     */
    eProsima_user_DllExport void num_integrity(
            uint8_t _num_integrity);

    /*!
     * @brief This function returns the value of member num_integrity
     * @return Value of member num_integrity
     */
    eProsima_user_DllExport uint8_t num_integrity() const;

    /*!
     * @brief This function returns a reference to member num_integrity
     * @return Reference to member num_integrity
     */
    eProsima_user_DllExport uint8_t& num_integrity();


    /*!
     * @brief This function copies the value in member integrity
     * @param _integrity New value to be copied in member integrity
     */
    eProsima_user_DllExport void integrity(
            const std::vector<aspn23_dds::TypeIntegrity>& _integrity);

    /*!
     * @brief This function moves the value in member integrity
     * @param _integrity New value to be moved in member integrity
     */
    eProsima_user_DllExport void integrity(
            std::vector<aspn23_dds::TypeIntegrity>&& _integrity);

    /*!
     * @brief This function returns a constant reference to member integrity
     * @return Constant reference to member integrity
     */
    eProsima_user_DllExport const std::vector<aspn23_dds::TypeIntegrity>& integrity() const;

    /*!
     * @brief This function returns a reference to member integrity
     * @return Reference to member integrity
     */
    eProsima_user_DllExport std::vector<aspn23_dds::TypeIntegrity>& integrity();

private:

    aspn23_dds::TypeHeader m_header;
    aspn23_dds::TypeTimestamp m_time_of_validity;
    aspn23_dds::TypeSatnavTime m_receiver_clock_time;
    uint16_t m_num_signal_types{0};
    uint16_t m_num_signals_tracked{0};
    std::vector<aspn23_dds::TypeSatnavObs> m_obs;
    std::vector<aspn23_dds::TypeSatnavSvData> m_sv_data;
    uint8_t m_num_integrity{0};
    std::vector<aspn23_dds::TypeIntegrity> m_integrity;

};

} // namespace aspn23_dds

#endif // _FAST_DDS_GENERATED_ASPN23_DDS_MEASUREMENTSATNAVWITHSVDATA_H_



