// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file MeasurementDirection3DToPoints.cpp
 * This source file contains the implementation of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "MeasurementDirection3DToPoints.h"

#include <fastcdr/Cdr.h>


#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>


namespace aspn23_dds {





MeasurementDirection3DToPoints::MeasurementDirection3DToPoints()
{
}

MeasurementDirection3DToPoints::~MeasurementDirection3DToPoints()
{
}

MeasurementDirection3DToPoints::MeasurementDirection3DToPoints(
        const MeasurementDirection3DToPoints& x)
{
    m_header = x.m_header;
    m_time_of_validity = x.m_time_of_validity;
    m_num_obs = x.m_num_obs;
    m_obs = x.m_obs;
}

MeasurementDirection3DToPoints::MeasurementDirection3DToPoints(
        MeasurementDirection3DToPoints&& x) noexcept
{
    m_header = std::move(x.m_header);
    m_time_of_validity = std::move(x.m_time_of_validity);
    m_num_obs = x.m_num_obs;
    m_obs = std::move(x.m_obs);
}

MeasurementDirection3DToPoints& MeasurementDirection3DToPoints::operator =(
        const MeasurementDirection3DToPoints& x)
{

    m_header = x.m_header;
    m_time_of_validity = x.m_time_of_validity;
    m_num_obs = x.m_num_obs;
    m_obs = x.m_obs;
    return *this;
}

MeasurementDirection3DToPoints& MeasurementDirection3DToPoints::operator =(
        MeasurementDirection3DToPoints&& x) noexcept
{

    m_header = std::move(x.m_header);
    m_time_of_validity = std::move(x.m_time_of_validity);
    m_num_obs = x.m_num_obs;
    m_obs = std::move(x.m_obs);
    return *this;
}

bool MeasurementDirection3DToPoints::operator ==(
        const MeasurementDirection3DToPoints& x) const
{
    return (m_header == x.m_header &&
           m_time_of_validity == x.m_time_of_validity &&
           m_num_obs == x.m_num_obs &&
           m_obs == x.m_obs);
}

bool MeasurementDirection3DToPoints::operator !=(
        const MeasurementDirection3DToPoints& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function copies the value in member header
 * @param _header New value to be copied in member header
 */
void MeasurementDirection3DToPoints::header(
        const aspn23_dds::TypeHeader& _header)
{
    m_header = _header;
}

/*!
 * @brief This function moves the value in member header
 * @param _header New value to be moved in member header
 */
void MeasurementDirection3DToPoints::header(
        aspn23_dds::TypeHeader&& _header)
{
    m_header = std::move(_header);
}

/*!
 * @brief This function returns a constant reference to member header
 * @return Constant reference to member header
 */
const aspn23_dds::TypeHeader& MeasurementDirection3DToPoints::header() const
{
    return m_header;
}

/*!
 * @brief This function returns a reference to member header
 * @return Reference to member header
 */
aspn23_dds::TypeHeader& MeasurementDirection3DToPoints::header()
{
    return m_header;
}


/*!
 * @brief This function copies the value in member time_of_validity
 * @param _time_of_validity New value to be copied in member time_of_validity
 */
void MeasurementDirection3DToPoints::time_of_validity(
        const aspn23_dds::TypeTimestamp& _time_of_validity)
{
    m_time_of_validity = _time_of_validity;
}

/*!
 * @brief This function moves the value in member time_of_validity
 * @param _time_of_validity New value to be moved in member time_of_validity
 */
void MeasurementDirection3DToPoints::time_of_validity(
        aspn23_dds::TypeTimestamp&& _time_of_validity)
{
    m_time_of_validity = std::move(_time_of_validity);
}

/*!
 * @brief This function returns a constant reference to member time_of_validity
 * @return Constant reference to member time_of_validity
 */
const aspn23_dds::TypeTimestamp& MeasurementDirection3DToPoints::time_of_validity() const
{
    return m_time_of_validity;
}

/*!
 * @brief This function returns a reference to member time_of_validity
 * @return Reference to member time_of_validity
 */
aspn23_dds::TypeTimestamp& MeasurementDirection3DToPoints::time_of_validity()
{
    return m_time_of_validity;
}


/*!
 * @brief This function sets a value in member num_obs
 * @param _num_obs New value for member num_obs
 */
void MeasurementDirection3DToPoints::num_obs(
        uint16_t _num_obs)
{
    m_num_obs = _num_obs;
}

/*!
 * @brief This function returns the value of member num_obs
 * @return Value of member num_obs
 */
uint16_t MeasurementDirection3DToPoints::num_obs() const
{
    return m_num_obs;
}

/*!
 * @brief This function returns a reference to member num_obs
 * @return Reference to member num_obs
 */
uint16_t& MeasurementDirection3DToPoints::num_obs()
{
    return m_num_obs;
}


/*!
 * @brief This function copies the value in member obs
 * @param _obs New value to be copied in member obs
 */
void MeasurementDirection3DToPoints::obs(
        const std::vector<aspn23_dds::TypeDirection3DToPoint>& _obs)
{
    m_obs = _obs;
}

/*!
 * @brief This function moves the value in member obs
 * @param _obs New value to be moved in member obs
 */
void MeasurementDirection3DToPoints::obs(
        std::vector<aspn23_dds::TypeDirection3DToPoint>&& _obs)
{
    m_obs = std::move(_obs);
}

/*!
 * @brief This function returns a constant reference to member obs
 * @return Constant reference to member obs
 */
const std::vector<aspn23_dds::TypeDirection3DToPoint>& MeasurementDirection3DToPoints::obs() const
{
    return m_obs;
}

/*!
 * @brief This function returns a reference to member obs
 * @return Reference to member obs
 */
std::vector<aspn23_dds::TypeDirection3DToPoint>& MeasurementDirection3DToPoints::obs()
{
    return m_obs;
}




} // namespace aspn23_dds
// Include auxiliary functions like for serializing/deserializing.
#include "MeasurementDirection3DToPointsCdrAux.ipp"

