// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file MeasurementAttitude3D.cpp
 * This source file contains the implementation of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "MeasurementAttitude3D.h"

#include <fastcdr/Cdr.h>


#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>


namespace aspn23_dds {





MeasurementAttitude3D::MeasurementAttitude3D()
{
}

MeasurementAttitude3D::~MeasurementAttitude3D()
{
}

MeasurementAttitude3D::MeasurementAttitude3D(
        const MeasurementAttitude3D& x)
{
    m_header = x.m_header;
    m_time_of_validity = x.m_time_of_validity;
    m_reference_frame = x.m_reference_frame;
    m_quaternion = x.m_quaternion;
    m_tilt_error_covariance = x.m_tilt_error_covariance;
    m_error_model = x.m_error_model;
    m_num_error_model_params = x.m_num_error_model_params;
    m_error_model_params = x.m_error_model_params;
    m_num_integrity = x.m_num_integrity;
    m_integrity = x.m_integrity;
}

MeasurementAttitude3D::MeasurementAttitude3D(
        MeasurementAttitude3D&& x) noexcept
{
    m_header = std::move(x.m_header);
    m_time_of_validity = std::move(x.m_time_of_validity);
    m_reference_frame = x.m_reference_frame;
    m_quaternion = std::move(x.m_quaternion);
    m_tilt_error_covariance = std::move(x.m_tilt_error_covariance);
    m_error_model = x.m_error_model;
    m_num_error_model_params = x.m_num_error_model_params;
    m_error_model_params = std::move(x.m_error_model_params);
    m_num_integrity = x.m_num_integrity;
    m_integrity = std::move(x.m_integrity);
}

MeasurementAttitude3D& MeasurementAttitude3D::operator =(
        const MeasurementAttitude3D& x)
{

    m_header = x.m_header;
    m_time_of_validity = x.m_time_of_validity;
    m_reference_frame = x.m_reference_frame;
    m_quaternion = x.m_quaternion;
    m_tilt_error_covariance = x.m_tilt_error_covariance;
    m_error_model = x.m_error_model;
    m_num_error_model_params = x.m_num_error_model_params;
    m_error_model_params = x.m_error_model_params;
    m_num_integrity = x.m_num_integrity;
    m_integrity = x.m_integrity;
    return *this;
}

MeasurementAttitude3D& MeasurementAttitude3D::operator =(
        MeasurementAttitude3D&& x) noexcept
{

    m_header = std::move(x.m_header);
    m_time_of_validity = std::move(x.m_time_of_validity);
    m_reference_frame = x.m_reference_frame;
    m_quaternion = std::move(x.m_quaternion);
    m_tilt_error_covariance = std::move(x.m_tilt_error_covariance);
    m_error_model = x.m_error_model;
    m_num_error_model_params = x.m_num_error_model_params;
    m_error_model_params = std::move(x.m_error_model_params);
    m_num_integrity = x.m_num_integrity;
    m_integrity = std::move(x.m_integrity);
    return *this;
}

bool MeasurementAttitude3D::operator ==(
        const MeasurementAttitude3D& x) const
{
    return (m_header == x.m_header &&
           m_time_of_validity == x.m_time_of_validity &&
           m_reference_frame == x.m_reference_frame &&
           m_quaternion == x.m_quaternion &&
           m_tilt_error_covariance == x.m_tilt_error_covariance &&
           m_error_model == x.m_error_model &&
           m_num_error_model_params == x.m_num_error_model_params &&
           m_error_model_params == x.m_error_model_params &&
           m_num_integrity == x.m_num_integrity &&
           m_integrity == x.m_integrity);
}

bool MeasurementAttitude3D::operator !=(
        const MeasurementAttitude3D& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function copies the value in member header
 * @param _header New value to be copied in member header
 */
void MeasurementAttitude3D::header(
        const aspn23_dds::TypeHeader& _header)
{
    m_header = _header;
}

/*!
 * @brief This function moves the value in member header
 * @param _header New value to be moved in member header
 */
void MeasurementAttitude3D::header(
        aspn23_dds::TypeHeader&& _header)
{
    m_header = std::move(_header);
}

/*!
 * @brief This function returns a constant reference to member header
 * @return Constant reference to member header
 */
const aspn23_dds::TypeHeader& MeasurementAttitude3D::header() const
{
    return m_header;
}

/*!
 * @brief This function returns a reference to member header
 * @return Reference to member header
 */
aspn23_dds::TypeHeader& MeasurementAttitude3D::header()
{
    return m_header;
}


/*!
 * @brief This function copies the value in member time_of_validity
 * @param _time_of_validity New value to be copied in member time_of_validity
 */
void MeasurementAttitude3D::time_of_validity(
        const aspn23_dds::TypeTimestamp& _time_of_validity)
{
    m_time_of_validity = _time_of_validity;
}

/*!
 * @brief This function moves the value in member time_of_validity
 * @param _time_of_validity New value to be moved in member time_of_validity
 */
void MeasurementAttitude3D::time_of_validity(
        aspn23_dds::TypeTimestamp&& _time_of_validity)
{
    m_time_of_validity = std::move(_time_of_validity);
}

/*!
 * @brief This function returns a constant reference to member time_of_validity
 * @return Constant reference to member time_of_validity
 */
const aspn23_dds::TypeTimestamp& MeasurementAttitude3D::time_of_validity() const
{
    return m_time_of_validity;
}

/*!
 * @brief This function returns a reference to member time_of_validity
 * @return Reference to member time_of_validity
 */
aspn23_dds::TypeTimestamp& MeasurementAttitude3D::time_of_validity()
{
    return m_time_of_validity;
}


/*!
 * @brief This function sets a value in member reference_frame
 * @param _reference_frame New value for member reference_frame
 */
void MeasurementAttitude3D::reference_frame(
        aspn23_dds::MeasurementAttitude3DReferenceFrameValue _reference_frame)
{
    m_reference_frame = _reference_frame;
}

/*!
 * @brief This function returns the value of member reference_frame
 * @return Value of member reference_frame
 */
aspn23_dds::MeasurementAttitude3DReferenceFrameValue MeasurementAttitude3D::reference_frame() const
{
    return m_reference_frame;
}

/*!
 * @brief This function returns a reference to member reference_frame
 * @return Reference to member reference_frame
 */
aspn23_dds::MeasurementAttitude3DReferenceFrameValue& MeasurementAttitude3D::reference_frame()
{
    return m_reference_frame;
}


/*!
 * @brief This function copies the value in member quaternion
 * @param _quaternion New value to be copied in member quaternion
 */
void MeasurementAttitude3D::quaternion(
        const std::array<double, 4>& _quaternion)
{
    m_quaternion = _quaternion;
}

/*!
 * @brief This function moves the value in member quaternion
 * @param _quaternion New value to be moved in member quaternion
 */
void MeasurementAttitude3D::quaternion(
        std::array<double, 4>&& _quaternion)
{
    m_quaternion = std::move(_quaternion);
}

/*!
 * @brief This function returns a constant reference to member quaternion
 * @return Constant reference to member quaternion
 */
const std::array<double, 4>& MeasurementAttitude3D::quaternion() const
{
    return m_quaternion;
}

/*!
 * @brief This function returns a reference to member quaternion
 * @return Reference to member quaternion
 */
std::array<double, 4>& MeasurementAttitude3D::quaternion()
{
    return m_quaternion;
}


/*!
 * @brief This function copies the value in member tilt_error_covariance
 * @param _tilt_error_covariance New value to be copied in member tilt_error_covariance
 */
void MeasurementAttitude3D::tilt_error_covariance(
        const std::vector<double>& _tilt_error_covariance)
{
    m_tilt_error_covariance = _tilt_error_covariance;
}

/*!
 * @brief This function moves the value in member tilt_error_covariance
 * @param _tilt_error_covariance New value to be moved in member tilt_error_covariance
 */
void MeasurementAttitude3D::tilt_error_covariance(
        std::vector<double>&& _tilt_error_covariance)
{
    m_tilt_error_covariance = std::move(_tilt_error_covariance);
}

/*!
 * @brief This function returns a constant reference to member tilt_error_covariance
 * @return Constant reference to member tilt_error_covariance
 */
const std::vector<double>& MeasurementAttitude3D::tilt_error_covariance() const
{
    return m_tilt_error_covariance;
}

/*!
 * @brief This function returns a reference to member tilt_error_covariance
 * @return Reference to member tilt_error_covariance
 */
std::vector<double>& MeasurementAttitude3D::tilt_error_covariance()
{
    return m_tilt_error_covariance;
}


/*!
 * @brief This function sets a value in member error_model
 * @param _error_model New value for member error_model
 */
void MeasurementAttitude3D::error_model(
        aspn23_dds::MeasurementAttitude3DErrorModelValue _error_model)
{
    m_error_model = _error_model;
}

/*!
 * @brief This function returns the value of member error_model
 * @return Value of member error_model
 */
aspn23_dds::MeasurementAttitude3DErrorModelValue MeasurementAttitude3D::error_model() const
{
    return m_error_model;
}

/*!
 * @brief This function returns a reference to member error_model
 * @return Reference to member error_model
 */
aspn23_dds::MeasurementAttitude3DErrorModelValue& MeasurementAttitude3D::error_model()
{
    return m_error_model;
}


/*!
 * @brief This function sets a value in member num_error_model_params
 * @param _num_error_model_params New value for member num_error_model_params
 */
void MeasurementAttitude3D::num_error_model_params(
        uint16_t _num_error_model_params)
{
    m_num_error_model_params = _num_error_model_params;
}

/*!
 * @brief This function returns the value of member num_error_model_params
 * @return Value of member num_error_model_params
 */
uint16_t MeasurementAttitude3D::num_error_model_params() const
{
    return m_num_error_model_params;
}

/*!
 * @brief This function returns a reference to member num_error_model_params
 * @return Reference to member num_error_model_params
 */
uint16_t& MeasurementAttitude3D::num_error_model_params()
{
    return m_num_error_model_params;
}


/*!
 * @brief This function copies the value in member error_model_params
 * @param _error_model_params New value to be copied in member error_model_params
 */
void MeasurementAttitude3D::error_model_params(
        const std::vector<double>& _error_model_params)
{
    m_error_model_params = _error_model_params;
}

/*!
 * @brief This function moves the value in member error_model_params
 * @param _error_model_params New value to be moved in member error_model_params
 */
void MeasurementAttitude3D::error_model_params(
        std::vector<double>&& _error_model_params)
{
    m_error_model_params = std::move(_error_model_params);
}

/*!
 * @brief This function returns a constant reference to member error_model_params
 * @return Constant reference to member error_model_params
 */
const std::vector<double>& MeasurementAttitude3D::error_model_params() const
{
    return m_error_model_params;
}

/*!
 * @brief This function returns a reference to member error_model_params
 * @return Reference to member error_model_params
 */
std::vector<double>& MeasurementAttitude3D::error_model_params()
{
    return m_error_model_params;
}


/*!
 * @brief This function sets a value in member num_integrity
 * @param _num_integrity New value for member num_integrity
 */
void MeasurementAttitude3D::num_integrity(
        uint8_t _num_integrity)
{
    m_num_integrity = _num_integrity;
}

/*!
 * @brief This function returns the value of member num_integrity
 * @return Value of member num_integrity
 */
uint8_t MeasurementAttitude3D::num_integrity() const
{
    return m_num_integrity;
}

/*!
 * @brief This function returns a reference to member num_integrity
 * @return Reference to member num_integrity
 */
uint8_t& MeasurementAttitude3D::num_integrity()
{
    return m_num_integrity;
}


/*!
 * @brief This function copies the value in member integrity
 * @param _integrity New value to be copied in member integrity
 */
void MeasurementAttitude3D::integrity(
        const std::vector<aspn23_dds::TypeIntegrity>& _integrity)
{
    m_integrity = _integrity;
}

/*!
 * @brief This function moves the value in member integrity
 * @param _integrity New value to be moved in member integrity
 */
void MeasurementAttitude3D::integrity(
        std::vector<aspn23_dds::TypeIntegrity>&& _integrity)
{
    m_integrity = std::move(_integrity);
}

/*!
 * @brief This function returns a constant reference to member integrity
 * @return Constant reference to member integrity
 */
const std::vector<aspn23_dds::TypeIntegrity>& MeasurementAttitude3D::integrity() const
{
    return m_integrity;
}

/*!
 * @brief This function returns a reference to member integrity
 * @return Reference to member integrity
 */
std::vector<aspn23_dds::TypeIntegrity>& MeasurementAttitude3D::integrity()
{
    return m_integrity;
}




} // namespace aspn23_dds
// Include auxiliary functions like for serializing/deserializing.
#include "MeasurementAttitude3DCdrAux.ipp"

