// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file MeasurementFrequencyDifference.cpp
 * This source file contains the implementation of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "MeasurementFrequencyDifference.h"

#include <fastcdr/Cdr.h>


#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>


namespace aspn23_dds {





MeasurementFrequencyDifference::MeasurementFrequencyDifference()
{
}

MeasurementFrequencyDifference::~MeasurementFrequencyDifference()
{
}

MeasurementFrequencyDifference::MeasurementFrequencyDifference(
        const MeasurementFrequencyDifference& x)
{
    m_header = x.m_header;
    m_time_of_validity = x.m_time_of_validity;
    m_time_of_validity_attosec = x.m_time_of_validity_attosec;
    m_clock_id1 = x.m_clock_id1;
    m_clock_id2 = x.m_clock_id2;
    m_freq_diff = x.m_freq_diff;
    m_variance = x.m_variance;
    m_error_model = x.m_error_model;
    m_num_error_model_params = x.m_num_error_model_params;
    m_error_model_params = x.m_error_model_params;
    m_num_integrity = x.m_num_integrity;
    m_integrity = x.m_integrity;
}

MeasurementFrequencyDifference::MeasurementFrequencyDifference(
        MeasurementFrequencyDifference&& x) noexcept
{
    m_header = std::move(x.m_header);
    m_time_of_validity = std::move(x.m_time_of_validity);
    m_time_of_validity_attosec = x.m_time_of_validity_attosec;
    m_clock_id1 = x.m_clock_id1;
    m_clock_id2 = x.m_clock_id2;
    m_freq_diff = x.m_freq_diff;
    m_variance = x.m_variance;
    m_error_model = x.m_error_model;
    m_num_error_model_params = x.m_num_error_model_params;
    m_error_model_params = std::move(x.m_error_model_params);
    m_num_integrity = x.m_num_integrity;
    m_integrity = std::move(x.m_integrity);
}

MeasurementFrequencyDifference& MeasurementFrequencyDifference::operator =(
        const MeasurementFrequencyDifference& x)
{

    m_header = x.m_header;
    m_time_of_validity = x.m_time_of_validity;
    m_time_of_validity_attosec = x.m_time_of_validity_attosec;
    m_clock_id1 = x.m_clock_id1;
    m_clock_id2 = x.m_clock_id2;
    m_freq_diff = x.m_freq_diff;
    m_variance = x.m_variance;
    m_error_model = x.m_error_model;
    m_num_error_model_params = x.m_num_error_model_params;
    m_error_model_params = x.m_error_model_params;
    m_num_integrity = x.m_num_integrity;
    m_integrity = x.m_integrity;
    return *this;
}

MeasurementFrequencyDifference& MeasurementFrequencyDifference::operator =(
        MeasurementFrequencyDifference&& x) noexcept
{

    m_header = std::move(x.m_header);
    m_time_of_validity = std::move(x.m_time_of_validity);
    m_time_of_validity_attosec = x.m_time_of_validity_attosec;
    m_clock_id1 = x.m_clock_id1;
    m_clock_id2 = x.m_clock_id2;
    m_freq_diff = x.m_freq_diff;
    m_variance = x.m_variance;
    m_error_model = x.m_error_model;
    m_num_error_model_params = x.m_num_error_model_params;
    m_error_model_params = std::move(x.m_error_model_params);
    m_num_integrity = x.m_num_integrity;
    m_integrity = std::move(x.m_integrity);
    return *this;
}

bool MeasurementFrequencyDifference::operator ==(
        const MeasurementFrequencyDifference& x) const
{
    return (m_header == x.m_header &&
           m_time_of_validity == x.m_time_of_validity &&
           m_time_of_validity_attosec == x.m_time_of_validity_attosec &&
           m_clock_id1 == x.m_clock_id1 &&
           m_clock_id2 == x.m_clock_id2 &&
           m_freq_diff == x.m_freq_diff &&
           m_variance == x.m_variance &&
           m_error_model == x.m_error_model &&
           m_num_error_model_params == x.m_num_error_model_params &&
           m_error_model_params == x.m_error_model_params &&
           m_num_integrity == x.m_num_integrity &&
           m_integrity == x.m_integrity);
}

bool MeasurementFrequencyDifference::operator !=(
        const MeasurementFrequencyDifference& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function copies the value in member header
 * @param _header New value to be copied in member header
 */
void MeasurementFrequencyDifference::header(
        const aspn23_dds::TypeHeader& _header)
{
    m_header = _header;
}

/*!
 * @brief This function moves the value in member header
 * @param _header New value to be moved in member header
 */
void MeasurementFrequencyDifference::header(
        aspn23_dds::TypeHeader&& _header)
{
    m_header = std::move(_header);
}

/*!
 * @brief This function returns a constant reference to member header
 * @return Constant reference to member header
 */
const aspn23_dds::TypeHeader& MeasurementFrequencyDifference::header() const
{
    return m_header;
}

/*!
 * @brief This function returns a reference to member header
 * @return Reference to member header
 */
aspn23_dds::TypeHeader& MeasurementFrequencyDifference::header()
{
    return m_header;
}


/*!
 * @brief This function copies the value in member time_of_validity
 * @param _time_of_validity New value to be copied in member time_of_validity
 */
void MeasurementFrequencyDifference::time_of_validity(
        const aspn23_dds::TypeTimestamp& _time_of_validity)
{
    m_time_of_validity = _time_of_validity;
}

/*!
 * @brief This function moves the value in member time_of_validity
 * @param _time_of_validity New value to be moved in member time_of_validity
 */
void MeasurementFrequencyDifference::time_of_validity(
        aspn23_dds::TypeTimestamp&& _time_of_validity)
{
    m_time_of_validity = std::move(_time_of_validity);
}

/*!
 * @brief This function returns a constant reference to member time_of_validity
 * @return Constant reference to member time_of_validity
 */
const aspn23_dds::TypeTimestamp& MeasurementFrequencyDifference::time_of_validity() const
{
    return m_time_of_validity;
}

/*!
 * @brief This function returns a reference to member time_of_validity
 * @return Reference to member time_of_validity
 */
aspn23_dds::TypeTimestamp& MeasurementFrequencyDifference::time_of_validity()
{
    return m_time_of_validity;
}


/*!
 * @brief This function sets a value in member time_of_validity_attosec
 * @param _time_of_validity_attosec New value for member time_of_validity_attosec
 */
void MeasurementFrequencyDifference::time_of_validity_attosec(
        int32_t _time_of_validity_attosec)
{
    m_time_of_validity_attosec = _time_of_validity_attosec;
}

/*!
 * @brief This function returns the value of member time_of_validity_attosec
 * @return Value of member time_of_validity_attosec
 */
int32_t MeasurementFrequencyDifference::time_of_validity_attosec() const
{
    return m_time_of_validity_attosec;
}

/*!
 * @brief This function returns a reference to member time_of_validity_attosec
 * @return Reference to member time_of_validity_attosec
 */
int32_t& MeasurementFrequencyDifference::time_of_validity_attosec()
{
    return m_time_of_validity_attosec;
}


/*!
 * @brief This function sets a value in member clock_id1
 * @param _clock_id1 New value for member clock_id1
 */
void MeasurementFrequencyDifference::clock_id1(
        uint8_t _clock_id1)
{
    m_clock_id1 = _clock_id1;
}

/*!
 * @brief This function returns the value of member clock_id1
 * @return Value of member clock_id1
 */
uint8_t MeasurementFrequencyDifference::clock_id1() const
{
    return m_clock_id1;
}

/*!
 * @brief This function returns a reference to member clock_id1
 * @return Reference to member clock_id1
 */
uint8_t& MeasurementFrequencyDifference::clock_id1()
{
    return m_clock_id1;
}


/*!
 * @brief This function sets a value in member clock_id2
 * @param _clock_id2 New value for member clock_id2
 */
void MeasurementFrequencyDifference::clock_id2(
        uint8_t _clock_id2)
{
    m_clock_id2 = _clock_id2;
}

/*!
 * @brief This function returns the value of member clock_id2
 * @return Value of member clock_id2
 */
uint8_t MeasurementFrequencyDifference::clock_id2() const
{
    return m_clock_id2;
}

/*!
 * @brief This function returns a reference to member clock_id2
 * @return Reference to member clock_id2
 */
uint8_t& MeasurementFrequencyDifference::clock_id2()
{
    return m_clock_id2;
}


/*!
 * @brief This function sets a value in member freq_diff
 * @param _freq_diff New value for member freq_diff
 */
void MeasurementFrequencyDifference::freq_diff(
        double _freq_diff)
{
    m_freq_diff = _freq_diff;
}

/*!
 * @brief This function returns the value of member freq_diff
 * @return Value of member freq_diff
 */
double MeasurementFrequencyDifference::freq_diff() const
{
    return m_freq_diff;
}

/*!
 * @brief This function returns a reference to member freq_diff
 * @return Reference to member freq_diff
 */
double& MeasurementFrequencyDifference::freq_diff()
{
    return m_freq_diff;
}


/*!
 * @brief This function sets a value in member variance
 * @param _variance New value for member variance
 */
void MeasurementFrequencyDifference::variance(
        double _variance)
{
    m_variance = _variance;
}

/*!
 * @brief This function returns the value of member variance
 * @return Value of member variance
 */
double MeasurementFrequencyDifference::variance() const
{
    return m_variance;
}

/*!
 * @brief This function returns a reference to member variance
 * @return Reference to member variance
 */
double& MeasurementFrequencyDifference::variance()
{
    return m_variance;
}


/*!
 * @brief This function sets a value in member error_model
 * @param _error_model New value for member error_model
 */
void MeasurementFrequencyDifference::error_model(
        aspn23_dds::MeasurementFrequencyDifferenceErrorModelValue _error_model)
{
    m_error_model = _error_model;
}

/*!
 * @brief This function returns the value of member error_model
 * @return Value of member error_model
 */
aspn23_dds::MeasurementFrequencyDifferenceErrorModelValue MeasurementFrequencyDifference::error_model() const
{
    return m_error_model;
}

/*!
 * @brief This function returns a reference to member error_model
 * @return Reference to member error_model
 */
aspn23_dds::MeasurementFrequencyDifferenceErrorModelValue& MeasurementFrequencyDifference::error_model()
{
    return m_error_model;
}


/*!
 * @brief This function sets a value in member num_error_model_params
 * @param _num_error_model_params New value for member num_error_model_params
 */
void MeasurementFrequencyDifference::num_error_model_params(
        uint16_t _num_error_model_params)
{
    m_num_error_model_params = _num_error_model_params;
}

/*!
 * @brief This function returns the value of member num_error_model_params
 * @return Value of member num_error_model_params
 */
uint16_t MeasurementFrequencyDifference::num_error_model_params() const
{
    return m_num_error_model_params;
}

/*!
 * @brief This function returns a reference to member num_error_model_params
 * @return Reference to member num_error_model_params
 */
uint16_t& MeasurementFrequencyDifference::num_error_model_params()
{
    return m_num_error_model_params;
}


/*!
 * @brief This function copies the value in member error_model_params
 * @param _error_model_params New value to be copied in member error_model_params
 */
void MeasurementFrequencyDifference::error_model_params(
        const std::vector<double>& _error_model_params)
{
    m_error_model_params = _error_model_params;
}

/*!
 * @brief This function moves the value in member error_model_params
 * @param _error_model_params New value to be moved in member error_model_params
 */
void MeasurementFrequencyDifference::error_model_params(
        std::vector<double>&& _error_model_params)
{
    m_error_model_params = std::move(_error_model_params);
}

/*!
 * @brief This function returns a constant reference to member error_model_params
 * @return Constant reference to member error_model_params
 */
const std::vector<double>& MeasurementFrequencyDifference::error_model_params() const
{
    return m_error_model_params;
}

/*!
 * @brief This function returns a reference to member error_model_params
 * @return Reference to member error_model_params
 */
std::vector<double>& MeasurementFrequencyDifference::error_model_params()
{
    return m_error_model_params;
}


/*!
 * @brief This function sets a value in member num_integrity
 * @param _num_integrity New value for member num_integrity
 */
void MeasurementFrequencyDifference::num_integrity(
        uint8_t _num_integrity)
{
    m_num_integrity = _num_integrity;
}

/*!
 * @brief This function returns the value of member num_integrity
 * @return Value of member num_integrity
 */
uint8_t MeasurementFrequencyDifference::num_integrity() const
{
    return m_num_integrity;
}

/*!
 * @brief This function returns a reference to member num_integrity
 * @return Reference to member num_integrity
 */
uint8_t& MeasurementFrequencyDifference::num_integrity()
{
    return m_num_integrity;
}


/*!
 * @brief This function copies the value in member integrity
 * @param _integrity New value to be copied in member integrity
 */
void MeasurementFrequencyDifference::integrity(
        const std::vector<aspn23_dds::TypeIntegrity>& _integrity)
{
    m_integrity = _integrity;
}

/*!
 * @brief This function moves the value in member integrity
 * @param _integrity New value to be moved in member integrity
 */
void MeasurementFrequencyDifference::integrity(
        std::vector<aspn23_dds::TypeIntegrity>&& _integrity)
{
    m_integrity = std::move(_integrity);
}

/*!
 * @brief This function returns a constant reference to member integrity
 * @return Constant reference to member integrity
 */
const std::vector<aspn23_dds::TypeIntegrity>& MeasurementFrequencyDifference::integrity() const
{
    return m_integrity;
}

/*!
 * @brief This function returns a reference to member integrity
 * @return Reference to member integrity
 */
std::vector<aspn23_dds::TypeIntegrity>& MeasurementFrequencyDifference::integrity()
{
    return m_integrity;
}




} // namespace aspn23_dds
// Include auxiliary functions like for serializing/deserializing.
#include "MeasurementFrequencyDifferenceCdrAux.ipp"

