// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file MeasurementTdoa1Tx2Rx.cpp
 * This source file contains the implementation of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "MeasurementTdoa1Tx2Rx.h"

#include <fastcdr/Cdr.h>


#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>


namespace aspn23_dds {





MeasurementTdoa1Tx2Rx::MeasurementTdoa1Tx2Rx()
{
}

MeasurementTdoa1Tx2Rx::~MeasurementTdoa1Tx2Rx()
{
}

MeasurementTdoa1Tx2Rx::MeasurementTdoa1Tx2Rx(
        const MeasurementTdoa1Tx2Rx& x)
{
    m_header = x.m_header;
    m_time_of_validity = x.m_time_of_validity;
    m_tx_position_and_covariance = x.m_tx_position_and_covariance;
    m_rx1_position_and_covariance = x.m_rx1_position_and_covariance;
    m_obs = x.m_obs;
    m_variance = x.m_variance;
    m_error_model = x.m_error_model;
    m_num_error_model_params = x.m_num_error_model_params;
    m_error_model_params = x.m_error_model_params;
    m_num_integrity = x.m_num_integrity;
    m_integrity = x.m_integrity;
}

MeasurementTdoa1Tx2Rx::MeasurementTdoa1Tx2Rx(
        MeasurementTdoa1Tx2Rx&& x) noexcept
{
    m_header = std::move(x.m_header);
    m_time_of_validity = std::move(x.m_time_of_validity);
    m_tx_position_and_covariance = std::move(x.m_tx_position_and_covariance);
    m_rx1_position_and_covariance = std::move(x.m_rx1_position_and_covariance);
    m_obs = x.m_obs;
    m_variance = x.m_variance;
    m_error_model = x.m_error_model;
    m_num_error_model_params = x.m_num_error_model_params;
    m_error_model_params = std::move(x.m_error_model_params);
    m_num_integrity = x.m_num_integrity;
    m_integrity = std::move(x.m_integrity);
}

MeasurementTdoa1Tx2Rx& MeasurementTdoa1Tx2Rx::operator =(
        const MeasurementTdoa1Tx2Rx& x)
{

    m_header = x.m_header;
    m_time_of_validity = x.m_time_of_validity;
    m_tx_position_and_covariance = x.m_tx_position_and_covariance;
    m_rx1_position_and_covariance = x.m_rx1_position_and_covariance;
    m_obs = x.m_obs;
    m_variance = x.m_variance;
    m_error_model = x.m_error_model;
    m_num_error_model_params = x.m_num_error_model_params;
    m_error_model_params = x.m_error_model_params;
    m_num_integrity = x.m_num_integrity;
    m_integrity = x.m_integrity;
    return *this;
}

MeasurementTdoa1Tx2Rx& MeasurementTdoa1Tx2Rx::operator =(
        MeasurementTdoa1Tx2Rx&& x) noexcept
{

    m_header = std::move(x.m_header);
    m_time_of_validity = std::move(x.m_time_of_validity);
    m_tx_position_and_covariance = std::move(x.m_tx_position_and_covariance);
    m_rx1_position_and_covariance = std::move(x.m_rx1_position_and_covariance);
    m_obs = x.m_obs;
    m_variance = x.m_variance;
    m_error_model = x.m_error_model;
    m_num_error_model_params = x.m_num_error_model_params;
    m_error_model_params = std::move(x.m_error_model_params);
    m_num_integrity = x.m_num_integrity;
    m_integrity = std::move(x.m_integrity);
    return *this;
}

bool MeasurementTdoa1Tx2Rx::operator ==(
        const MeasurementTdoa1Tx2Rx& x) const
{
    return (m_header == x.m_header &&
           m_time_of_validity == x.m_time_of_validity &&
           m_tx_position_and_covariance == x.m_tx_position_and_covariance &&
           m_rx1_position_and_covariance == x.m_rx1_position_and_covariance &&
           m_obs == x.m_obs &&
           m_variance == x.m_variance &&
           m_error_model == x.m_error_model &&
           m_num_error_model_params == x.m_num_error_model_params &&
           m_error_model_params == x.m_error_model_params &&
           m_num_integrity == x.m_num_integrity &&
           m_integrity == x.m_integrity);
}

bool MeasurementTdoa1Tx2Rx::operator !=(
        const MeasurementTdoa1Tx2Rx& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function copies the value in member header
 * @param _header New value to be copied in member header
 */
void MeasurementTdoa1Tx2Rx::header(
        const aspn23_dds::TypeHeader& _header)
{
    m_header = _header;
}

/*!
 * @brief This function moves the value in member header
 * @param _header New value to be moved in member header
 */
void MeasurementTdoa1Tx2Rx::header(
        aspn23_dds::TypeHeader&& _header)
{
    m_header = std::move(_header);
}

/*!
 * @brief This function returns a constant reference to member header
 * @return Constant reference to member header
 */
const aspn23_dds::TypeHeader& MeasurementTdoa1Tx2Rx::header() const
{
    return m_header;
}

/*!
 * @brief This function returns a reference to member header
 * @return Reference to member header
 */
aspn23_dds::TypeHeader& MeasurementTdoa1Tx2Rx::header()
{
    return m_header;
}


/*!
 * @brief This function copies the value in member time_of_validity
 * @param _time_of_validity New value to be copied in member time_of_validity
 */
void MeasurementTdoa1Tx2Rx::time_of_validity(
        const aspn23_dds::TypeTimestamp& _time_of_validity)
{
    m_time_of_validity = _time_of_validity;
}

/*!
 * @brief This function moves the value in member time_of_validity
 * @param _time_of_validity New value to be moved in member time_of_validity
 */
void MeasurementTdoa1Tx2Rx::time_of_validity(
        aspn23_dds::TypeTimestamp&& _time_of_validity)
{
    m_time_of_validity = std::move(_time_of_validity);
}

/*!
 * @brief This function returns a constant reference to member time_of_validity
 * @return Constant reference to member time_of_validity
 */
const aspn23_dds::TypeTimestamp& MeasurementTdoa1Tx2Rx::time_of_validity() const
{
    return m_time_of_validity;
}

/*!
 * @brief This function returns a reference to member time_of_validity
 * @return Reference to member time_of_validity
 */
aspn23_dds::TypeTimestamp& MeasurementTdoa1Tx2Rx::time_of_validity()
{
    return m_time_of_validity;
}


/*!
 * @brief This function copies the value in member tx_position_and_covariance
 * @param _tx_position_and_covariance New value to be copied in member tx_position_and_covariance
 */
void MeasurementTdoa1Tx2Rx::tx_position_and_covariance(
        const aspn23_dds::TypeRemotePoint& _tx_position_and_covariance)
{
    m_tx_position_and_covariance = _tx_position_and_covariance;
}

/*!
 * @brief This function moves the value in member tx_position_and_covariance
 * @param _tx_position_and_covariance New value to be moved in member tx_position_and_covariance
 */
void MeasurementTdoa1Tx2Rx::tx_position_and_covariance(
        aspn23_dds::TypeRemotePoint&& _tx_position_and_covariance)
{
    m_tx_position_and_covariance = std::move(_tx_position_and_covariance);
}

/*!
 * @brief This function returns a constant reference to member tx_position_and_covariance
 * @return Constant reference to member tx_position_and_covariance
 */
const aspn23_dds::TypeRemotePoint& MeasurementTdoa1Tx2Rx::tx_position_and_covariance() const
{
    return m_tx_position_and_covariance;
}

/*!
 * @brief This function returns a reference to member tx_position_and_covariance
 * @return Reference to member tx_position_and_covariance
 */
aspn23_dds::TypeRemotePoint& MeasurementTdoa1Tx2Rx::tx_position_and_covariance()
{
    return m_tx_position_and_covariance;
}


/*!
 * @brief This function copies the value in member rx1_position_and_covariance
 * @param _rx1_position_and_covariance New value to be copied in member rx1_position_and_covariance
 */
void MeasurementTdoa1Tx2Rx::rx1_position_and_covariance(
        const aspn23_dds::TypeRemotePoint& _rx1_position_and_covariance)
{
    m_rx1_position_and_covariance = _rx1_position_and_covariance;
}

/*!
 * @brief This function moves the value in member rx1_position_and_covariance
 * @param _rx1_position_and_covariance New value to be moved in member rx1_position_and_covariance
 */
void MeasurementTdoa1Tx2Rx::rx1_position_and_covariance(
        aspn23_dds::TypeRemotePoint&& _rx1_position_and_covariance)
{
    m_rx1_position_and_covariance = std::move(_rx1_position_and_covariance);
}

/*!
 * @brief This function returns a constant reference to member rx1_position_and_covariance
 * @return Constant reference to member rx1_position_and_covariance
 */
const aspn23_dds::TypeRemotePoint& MeasurementTdoa1Tx2Rx::rx1_position_and_covariance() const
{
    return m_rx1_position_and_covariance;
}

/*!
 * @brief This function returns a reference to member rx1_position_and_covariance
 * @return Reference to member rx1_position_and_covariance
 */
aspn23_dds::TypeRemotePoint& MeasurementTdoa1Tx2Rx::rx1_position_and_covariance()
{
    return m_rx1_position_and_covariance;
}


/*!
 * @brief This function sets a value in member obs
 * @param _obs New value for member obs
 */
void MeasurementTdoa1Tx2Rx::obs(
        double _obs)
{
    m_obs = _obs;
}

/*!
 * @brief This function returns the value of member obs
 * @return Value of member obs
 */
double MeasurementTdoa1Tx2Rx::obs() const
{
    return m_obs;
}

/*!
 * @brief This function returns a reference to member obs
 * @return Reference to member obs
 */
double& MeasurementTdoa1Tx2Rx::obs()
{
    return m_obs;
}


/*!
 * @brief This function sets a value in member variance
 * @param _variance New value for member variance
 */
void MeasurementTdoa1Tx2Rx::variance(
        double _variance)
{
    m_variance = _variance;
}

/*!
 * @brief This function returns the value of member variance
 * @return Value of member variance
 */
double MeasurementTdoa1Tx2Rx::variance() const
{
    return m_variance;
}

/*!
 * @brief This function returns a reference to member variance
 * @return Reference to member variance
 */
double& MeasurementTdoa1Tx2Rx::variance()
{
    return m_variance;
}


/*!
 * @brief This function sets a value in member error_model
 * @param _error_model New value for member error_model
 */
void MeasurementTdoa1Tx2Rx::error_model(
        aspn23_dds::MeasurementTdoa1Tx2RxErrorModelValue _error_model)
{
    m_error_model = _error_model;
}

/*!
 * @brief This function returns the value of member error_model
 * @return Value of member error_model
 */
aspn23_dds::MeasurementTdoa1Tx2RxErrorModelValue MeasurementTdoa1Tx2Rx::error_model() const
{
    return m_error_model;
}

/*!
 * @brief This function returns a reference to member error_model
 * @return Reference to member error_model
 */
aspn23_dds::MeasurementTdoa1Tx2RxErrorModelValue& MeasurementTdoa1Tx2Rx::error_model()
{
    return m_error_model;
}


/*!
 * @brief This function sets a value in member num_error_model_params
 * @param _num_error_model_params New value for member num_error_model_params
 */
void MeasurementTdoa1Tx2Rx::num_error_model_params(
        uint16_t _num_error_model_params)
{
    m_num_error_model_params = _num_error_model_params;
}

/*!
 * @brief This function returns the value of member num_error_model_params
 * @return Value of member num_error_model_params
 */
uint16_t MeasurementTdoa1Tx2Rx::num_error_model_params() const
{
    return m_num_error_model_params;
}

/*!
 * @brief This function returns a reference to member num_error_model_params
 * @return Reference to member num_error_model_params
 */
uint16_t& MeasurementTdoa1Tx2Rx::num_error_model_params()
{
    return m_num_error_model_params;
}


/*!
 * @brief This function copies the value in member error_model_params
 * @param _error_model_params New value to be copied in member error_model_params
 */
void MeasurementTdoa1Tx2Rx::error_model_params(
        const std::vector<double>& _error_model_params)
{
    m_error_model_params = _error_model_params;
}

/*!
 * @brief This function moves the value in member error_model_params
 * @param _error_model_params New value to be moved in member error_model_params
 */
void MeasurementTdoa1Tx2Rx::error_model_params(
        std::vector<double>&& _error_model_params)
{
    m_error_model_params = std::move(_error_model_params);
}

/*!
 * @brief This function returns a constant reference to member error_model_params
 * @return Constant reference to member error_model_params
 */
const std::vector<double>& MeasurementTdoa1Tx2Rx::error_model_params() const
{
    return m_error_model_params;
}

/*!
 * @brief This function returns a reference to member error_model_params
 * @return Reference to member error_model_params
 */
std::vector<double>& MeasurementTdoa1Tx2Rx::error_model_params()
{
    return m_error_model_params;
}


/*!
 * @brief This function sets a value in member num_integrity
 * @param _num_integrity New value for member num_integrity
 */
void MeasurementTdoa1Tx2Rx::num_integrity(
        uint8_t _num_integrity)
{
    m_num_integrity = _num_integrity;
}

/*!
 * @brief This function returns the value of member num_integrity
 * @return Value of member num_integrity
 */
uint8_t MeasurementTdoa1Tx2Rx::num_integrity() const
{
    return m_num_integrity;
}

/*!
 * @brief This function returns a reference to member num_integrity
 * @return Reference to member num_integrity
 */
uint8_t& MeasurementTdoa1Tx2Rx::num_integrity()
{
    return m_num_integrity;
}


/*!
 * @brief This function copies the value in member integrity
 * @param _integrity New value to be copied in member integrity
 */
void MeasurementTdoa1Tx2Rx::integrity(
        const std::vector<aspn23_dds::TypeIntegrity>& _integrity)
{
    m_integrity = _integrity;
}

/*!
 * @brief This function moves the value in member integrity
 * @param _integrity New value to be moved in member integrity
 */
void MeasurementTdoa1Tx2Rx::integrity(
        std::vector<aspn23_dds::TypeIntegrity>&& _integrity)
{
    m_integrity = std::move(_integrity);
}

/*!
 * @brief This function returns a constant reference to member integrity
 * @return Constant reference to member integrity
 */
const std::vector<aspn23_dds::TypeIntegrity>& MeasurementTdoa1Tx2Rx::integrity() const
{
    return m_integrity;
}

/*!
 * @brief This function returns a reference to member integrity
 * @return Reference to member integrity
 */
std::vector<aspn23_dds::TypeIntegrity>& MeasurementTdoa1Tx2Rx::integrity()
{
    return m_integrity;
}




} // namespace aspn23_dds
// Include auxiliary functions like for serializing/deserializing.
#include "MeasurementTdoa1Tx2RxCdrAux.ipp"

