// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file MeasurementMagneticField.cpp
 * This source file contains the implementation of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "MeasurementMagneticField.h"

#include <fastcdr/Cdr.h>


#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>


namespace aspn23_dds {





MeasurementMagneticField::MeasurementMagneticField()
{
}

MeasurementMagneticField::~MeasurementMagneticField()
{
}

MeasurementMagneticField::MeasurementMagneticField(
        const MeasurementMagneticField& x)
{
    m_header = x.m_header;
    m_time_of_validity = x.m_time_of_validity;
    m_num_meas = x.m_num_meas;
    m_x_field_strength = x.m_x_field_strength;
    m_y_field_strength = x.m_y_field_strength;
    m_z_field_strength = x.m_z_field_strength;
    m_covariance = x.m_covariance;
    m_error_model = x.m_error_model;
    m_num_error_model_params = x.m_num_error_model_params;
    m_error_model_params = x.m_error_model_params;
    m_num_integrity = x.m_num_integrity;
    m_integrity = x.m_integrity;
}

MeasurementMagneticField::MeasurementMagneticField(
        MeasurementMagneticField&& x) noexcept
{
    m_header = std::move(x.m_header);
    m_time_of_validity = std::move(x.m_time_of_validity);
    m_num_meas = x.m_num_meas;
    m_x_field_strength = x.m_x_field_strength;
    m_y_field_strength = x.m_y_field_strength;
    m_z_field_strength = x.m_z_field_strength;
    m_covariance = std::move(x.m_covariance);
    m_error_model = x.m_error_model;
    m_num_error_model_params = x.m_num_error_model_params;
    m_error_model_params = std::move(x.m_error_model_params);
    m_num_integrity = x.m_num_integrity;
    m_integrity = std::move(x.m_integrity);
}

MeasurementMagneticField& MeasurementMagneticField::operator =(
        const MeasurementMagneticField& x)
{

    m_header = x.m_header;
    m_time_of_validity = x.m_time_of_validity;
    m_num_meas = x.m_num_meas;
    m_x_field_strength = x.m_x_field_strength;
    m_y_field_strength = x.m_y_field_strength;
    m_z_field_strength = x.m_z_field_strength;
    m_covariance = x.m_covariance;
    m_error_model = x.m_error_model;
    m_num_error_model_params = x.m_num_error_model_params;
    m_error_model_params = x.m_error_model_params;
    m_num_integrity = x.m_num_integrity;
    m_integrity = x.m_integrity;
    return *this;
}

MeasurementMagneticField& MeasurementMagneticField::operator =(
        MeasurementMagneticField&& x) noexcept
{

    m_header = std::move(x.m_header);
    m_time_of_validity = std::move(x.m_time_of_validity);
    m_num_meas = x.m_num_meas;
    m_x_field_strength = x.m_x_field_strength;
    m_y_field_strength = x.m_y_field_strength;
    m_z_field_strength = x.m_z_field_strength;
    m_covariance = std::move(x.m_covariance);
    m_error_model = x.m_error_model;
    m_num_error_model_params = x.m_num_error_model_params;
    m_error_model_params = std::move(x.m_error_model_params);
    m_num_integrity = x.m_num_integrity;
    m_integrity = std::move(x.m_integrity);
    return *this;
}

bool MeasurementMagneticField::operator ==(
        const MeasurementMagneticField& x) const
{
    return (m_header == x.m_header &&
           m_time_of_validity == x.m_time_of_validity &&
           m_num_meas == x.m_num_meas &&
           m_x_field_strength == x.m_x_field_strength &&
           m_y_field_strength == x.m_y_field_strength &&
           m_z_field_strength == x.m_z_field_strength &&
           m_covariance == x.m_covariance &&
           m_error_model == x.m_error_model &&
           m_num_error_model_params == x.m_num_error_model_params &&
           m_error_model_params == x.m_error_model_params &&
           m_num_integrity == x.m_num_integrity &&
           m_integrity == x.m_integrity);
}

bool MeasurementMagneticField::operator !=(
        const MeasurementMagneticField& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function copies the value in member header
 * @param _header New value to be copied in member header
 */
void MeasurementMagneticField::header(
        const aspn23_dds::TypeHeader& _header)
{
    m_header = _header;
}

/*!
 * @brief This function moves the value in member header
 * @param _header New value to be moved in member header
 */
void MeasurementMagneticField::header(
        aspn23_dds::TypeHeader&& _header)
{
    m_header = std::move(_header);
}

/*!
 * @brief This function returns a constant reference to member header
 * @return Constant reference to member header
 */
const aspn23_dds::TypeHeader& MeasurementMagneticField::header() const
{
    return m_header;
}

/*!
 * @brief This function returns a reference to member header
 * @return Reference to member header
 */
aspn23_dds::TypeHeader& MeasurementMagneticField::header()
{
    return m_header;
}


/*!
 * @brief This function copies the value in member time_of_validity
 * @param _time_of_validity New value to be copied in member time_of_validity
 */
void MeasurementMagneticField::time_of_validity(
        const aspn23_dds::TypeTimestamp& _time_of_validity)
{
    m_time_of_validity = _time_of_validity;
}

/*!
 * @brief This function moves the value in member time_of_validity
 * @param _time_of_validity New value to be moved in member time_of_validity
 */
void MeasurementMagneticField::time_of_validity(
        aspn23_dds::TypeTimestamp&& _time_of_validity)
{
    m_time_of_validity = std::move(_time_of_validity);
}

/*!
 * @brief This function returns a constant reference to member time_of_validity
 * @return Constant reference to member time_of_validity
 */
const aspn23_dds::TypeTimestamp& MeasurementMagneticField::time_of_validity() const
{
    return m_time_of_validity;
}

/*!
 * @brief This function returns a reference to member time_of_validity
 * @return Reference to member time_of_validity
 */
aspn23_dds::TypeTimestamp& MeasurementMagneticField::time_of_validity()
{
    return m_time_of_validity;
}


/*!
 * @brief This function sets a value in member num_meas
 * @param _num_meas New value for member num_meas
 */
void MeasurementMagneticField::num_meas(
        uint8_t _num_meas)
{
    m_num_meas = _num_meas;
}

/*!
 * @brief This function returns the value of member num_meas
 * @return Value of member num_meas
 */
uint8_t MeasurementMagneticField::num_meas() const
{
    return m_num_meas;
}

/*!
 * @brief This function returns a reference to member num_meas
 * @return Reference to member num_meas
 */
uint8_t& MeasurementMagneticField::num_meas()
{
    return m_num_meas;
}


/*!
 * @brief This function copies the value in member x_field_strength
 * @param _x_field_strength New value to be copied in member x_field_strength
 */
void MeasurementMagneticField::x_field_strength(
        const eprosima::fastcdr::optional<double>& _x_field_strength)
{
    m_x_field_strength = _x_field_strength;
}

/*!
 * @brief This function moves the value in member x_field_strength
 * @param _x_field_strength New value to be moved in member x_field_strength
 */
void MeasurementMagneticField::x_field_strength(
        eprosima::fastcdr::optional<double>&& _x_field_strength)
{
    m_x_field_strength = std::move(_x_field_strength);
}

/*!
 * @brief This function returns a constant reference to member x_field_strength
 * @return Constant reference to member x_field_strength
 */
const eprosima::fastcdr::optional<double>& MeasurementMagneticField::x_field_strength() const
{
    return m_x_field_strength;
}

/*!
 * @brief This function returns a reference to member x_field_strength
 * @return Reference to member x_field_strength
 */
eprosima::fastcdr::optional<double>& MeasurementMagneticField::x_field_strength()
{
    return m_x_field_strength;
}


/*!
 * @brief This function copies the value in member y_field_strength
 * @param _y_field_strength New value to be copied in member y_field_strength
 */
void MeasurementMagneticField::y_field_strength(
        const eprosima::fastcdr::optional<double>& _y_field_strength)
{
    m_y_field_strength = _y_field_strength;
}

/*!
 * @brief This function moves the value in member y_field_strength
 * @param _y_field_strength New value to be moved in member y_field_strength
 */
void MeasurementMagneticField::y_field_strength(
        eprosima::fastcdr::optional<double>&& _y_field_strength)
{
    m_y_field_strength = std::move(_y_field_strength);
}

/*!
 * @brief This function returns a constant reference to member y_field_strength
 * @return Constant reference to member y_field_strength
 */
const eprosima::fastcdr::optional<double>& MeasurementMagneticField::y_field_strength() const
{
    return m_y_field_strength;
}

/*!
 * @brief This function returns a reference to member y_field_strength
 * @return Reference to member y_field_strength
 */
eprosima::fastcdr::optional<double>& MeasurementMagneticField::y_field_strength()
{
    return m_y_field_strength;
}


/*!
 * @brief This function copies the value in member z_field_strength
 * @param _z_field_strength New value to be copied in member z_field_strength
 */
void MeasurementMagneticField::z_field_strength(
        const eprosima::fastcdr::optional<double>& _z_field_strength)
{
    m_z_field_strength = _z_field_strength;
}

/*!
 * @brief This function moves the value in member z_field_strength
 * @param _z_field_strength New value to be moved in member z_field_strength
 */
void MeasurementMagneticField::z_field_strength(
        eprosima::fastcdr::optional<double>&& _z_field_strength)
{
    m_z_field_strength = std::move(_z_field_strength);
}

/*!
 * @brief This function returns a constant reference to member z_field_strength
 * @return Constant reference to member z_field_strength
 */
const eprosima::fastcdr::optional<double>& MeasurementMagneticField::z_field_strength() const
{
    return m_z_field_strength;
}

/*!
 * @brief This function returns a reference to member z_field_strength
 * @return Reference to member z_field_strength
 */
eprosima::fastcdr::optional<double>& MeasurementMagneticField::z_field_strength()
{
    return m_z_field_strength;
}


/*!
 * @brief This function copies the value in member covariance
 * @param _covariance New value to be copied in member covariance
 */
void MeasurementMagneticField::covariance(
        const std::vector<double>& _covariance)
{
    m_covariance = _covariance;
}

/*!
 * @brief This function moves the value in member covariance
 * @param _covariance New value to be moved in member covariance
 */
void MeasurementMagneticField::covariance(
        std::vector<double>&& _covariance)
{
    m_covariance = std::move(_covariance);
}

/*!
 * @brief This function returns a constant reference to member covariance
 * @return Constant reference to member covariance
 */
const std::vector<double>& MeasurementMagneticField::covariance() const
{
    return m_covariance;
}

/*!
 * @brief This function returns a reference to member covariance
 * @return Reference to member covariance
 */
std::vector<double>& MeasurementMagneticField::covariance()
{
    return m_covariance;
}


/*!
 * @brief This function sets a value in member error_model
 * @param _error_model New value for member error_model
 */
void MeasurementMagneticField::error_model(
        aspn23_dds::MeasurementMagneticFieldErrorModelValue _error_model)
{
    m_error_model = _error_model;
}

/*!
 * @brief This function returns the value of member error_model
 * @return Value of member error_model
 */
aspn23_dds::MeasurementMagneticFieldErrorModelValue MeasurementMagneticField::error_model() const
{
    return m_error_model;
}

/*!
 * @brief This function returns a reference to member error_model
 * @return Reference to member error_model
 */
aspn23_dds::MeasurementMagneticFieldErrorModelValue& MeasurementMagneticField::error_model()
{
    return m_error_model;
}


/*!
 * @brief This function sets a value in member num_error_model_params
 * @param _num_error_model_params New value for member num_error_model_params
 */
void MeasurementMagneticField::num_error_model_params(
        uint16_t _num_error_model_params)
{
    m_num_error_model_params = _num_error_model_params;
}

/*!
 * @brief This function returns the value of member num_error_model_params
 * @return Value of member num_error_model_params
 */
uint16_t MeasurementMagneticField::num_error_model_params() const
{
    return m_num_error_model_params;
}

/*!
 * @brief This function returns a reference to member num_error_model_params
 * @return Reference to member num_error_model_params
 */
uint16_t& MeasurementMagneticField::num_error_model_params()
{
    return m_num_error_model_params;
}


/*!
 * @brief This function copies the value in member error_model_params
 * @param _error_model_params New value to be copied in member error_model_params
 */
void MeasurementMagneticField::error_model_params(
        const std::vector<double>& _error_model_params)
{
    m_error_model_params = _error_model_params;
}

/*!
 * @brief This function moves the value in member error_model_params
 * @param _error_model_params New value to be moved in member error_model_params
 */
void MeasurementMagneticField::error_model_params(
        std::vector<double>&& _error_model_params)
{
    m_error_model_params = std::move(_error_model_params);
}

/*!
 * @brief This function returns a constant reference to member error_model_params
 * @return Constant reference to member error_model_params
 */
const std::vector<double>& MeasurementMagneticField::error_model_params() const
{
    return m_error_model_params;
}

/*!
 * @brief This function returns a reference to member error_model_params
 * @return Reference to member error_model_params
 */
std::vector<double>& MeasurementMagneticField::error_model_params()
{
    return m_error_model_params;
}


/*!
 * @brief This function sets a value in member num_integrity
 * @param _num_integrity New value for member num_integrity
 */
void MeasurementMagneticField::num_integrity(
        uint8_t _num_integrity)
{
    m_num_integrity = _num_integrity;
}

/*!
 * @brief This function returns the value of member num_integrity
 * @return Value of member num_integrity
 */
uint8_t MeasurementMagneticField::num_integrity() const
{
    return m_num_integrity;
}

/*!
 * @brief This function returns a reference to member num_integrity
 * @return Reference to member num_integrity
 */
uint8_t& MeasurementMagneticField::num_integrity()
{
    return m_num_integrity;
}


/*!
 * @brief This function copies the value in member integrity
 * @param _integrity New value to be copied in member integrity
 */
void MeasurementMagneticField::integrity(
        const std::vector<aspn23_dds::TypeIntegrity>& _integrity)
{
    m_integrity = _integrity;
}

/*!
 * @brief This function moves the value in member integrity
 * @param _integrity New value to be moved in member integrity
 */
void MeasurementMagneticField::integrity(
        std::vector<aspn23_dds::TypeIntegrity>&& _integrity)
{
    m_integrity = std::move(_integrity);
}

/*!
 * @brief This function returns a constant reference to member integrity
 * @return Constant reference to member integrity
 */
const std::vector<aspn23_dds::TypeIntegrity>& MeasurementMagneticField::integrity() const
{
    return m_integrity;
}

/*!
 * @brief This function returns a reference to member integrity
 * @return Reference to member integrity
 */
std::vector<aspn23_dds::TypeIntegrity>& MeasurementMagneticField::integrity()
{
    return m_integrity;
}




} // namespace aspn23_dds
// Include auxiliary functions like for serializing/deserializing.
#include "MeasurementMagneticFieldCdrAux.ipp"

