// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file MeasurementTimeFrequencyDifference.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_ASPN23_DDS_MEASUREMENTTIMEFREQUENCYDIFFERENCE_H_
#define _FAST_DDS_GENERATED_ASPN23_DDS_MEASUREMENTTIMEFREQUENCYDIFFERENCE_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>

#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>

#include "TypeHeader.h"
#include "TypeTimestamp.h"
#include "TypeIntegrity.h"


#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(MEASUREMENTTIMEFREQUENCYDIFFERENCE_SOURCE)
#define MEASUREMENTTIMEFREQUENCYDIFFERENCE_DllAPI __declspec( dllexport )
#else
#define MEASUREMENTTIMEFREQUENCYDIFFERENCE_DllAPI __declspec( dllimport )
#endif // MEASUREMENTTIMEFREQUENCYDIFFERENCE_SOURCE
#else
#define MEASUREMENTTIMEFREQUENCYDIFFERENCE_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define MEASUREMENTTIMEFREQUENCYDIFFERENCE_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima



namespace aspn23_dds {

/*!
 * @brief This class represents the enumeration MeasurementTimeFrequencyDifferenceErrorModelValue defined by the user in the IDL file.
 * @ingroup MeasurementTimeFrequencyDifference
 */
enum MeasurementTimeFrequencyDifferenceErrorModelValue : uint32_t
{
    ASPN23_MEASUREMENT_TIME_FREQUENCY_DIFFERENCE_ERROR_MODEL_NONE
};




/*!
 * @brief This class represents the structure MeasurementTimeFrequencyDifference defined by the user in the IDL file.
 * @ingroup MeasurementTimeFrequencyDifference
 */
class MeasurementTimeFrequencyDifference
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport MeasurementTimeFrequencyDifference();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~MeasurementTimeFrequencyDifference();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object aspn23_dds::MeasurementTimeFrequencyDifference that will be copied.
     */
    eProsima_user_DllExport MeasurementTimeFrequencyDifference(
            const MeasurementTimeFrequencyDifference& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object aspn23_dds::MeasurementTimeFrequencyDifference that will be copied.
     */
    eProsima_user_DllExport MeasurementTimeFrequencyDifference(
            MeasurementTimeFrequencyDifference&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object aspn23_dds::MeasurementTimeFrequencyDifference that will be copied.
     */
    eProsima_user_DllExport MeasurementTimeFrequencyDifference& operator =(
            const MeasurementTimeFrequencyDifference& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object aspn23_dds::MeasurementTimeFrequencyDifference that will be copied.
     */
    eProsima_user_DllExport MeasurementTimeFrequencyDifference& operator =(
            MeasurementTimeFrequencyDifference&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x aspn23_dds::MeasurementTimeFrequencyDifference object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const MeasurementTimeFrequencyDifference& x) const;

    /*!
     * @brief Comparison operator.
     * @param x aspn23_dds::MeasurementTimeFrequencyDifference object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const MeasurementTimeFrequencyDifference& x) const;

    /*!
     * @brief This function copies the value in member header
     * @param _header New value to be copied in member header
     */
    eProsima_user_DllExport void header(
            const aspn23_dds::TypeHeader& _header);

    /*!
     * @brief This function moves the value in member header
     * @param _header New value to be moved in member header
     */
    eProsima_user_DllExport void header(
            aspn23_dds::TypeHeader&& _header);

    /*!
     * @brief This function returns a constant reference to member header
     * @return Constant reference to member header
     */
    eProsima_user_DllExport const aspn23_dds::TypeHeader& header() const;

    /*!
     * @brief This function returns a reference to member header
     * @return Reference to member header
     */
    eProsima_user_DllExport aspn23_dds::TypeHeader& header();


    /*!
     * @brief This function copies the value in member time_of_validity
     * @param _time_of_validity New value to be copied in member time_of_validity
     */
    eProsima_user_DllExport void time_of_validity(
            const aspn23_dds::TypeTimestamp& _time_of_validity);

    /*!
     * @brief This function moves the value in member time_of_validity
     * @param _time_of_validity New value to be moved in member time_of_validity
     */
    eProsima_user_DllExport void time_of_validity(
            aspn23_dds::TypeTimestamp&& _time_of_validity);

    /*!
     * @brief This function returns a constant reference to member time_of_validity
     * @return Constant reference to member time_of_validity
     */
    eProsima_user_DllExport const aspn23_dds::TypeTimestamp& time_of_validity() const;

    /*!
     * @brief This function returns a reference to member time_of_validity
     * @return Reference to member time_of_validity
     */
    eProsima_user_DllExport aspn23_dds::TypeTimestamp& time_of_validity();


    /*!
     * @brief This function sets a value in member time_of_validity_attosec
     * @param _time_of_validity_attosec New value for member time_of_validity_attosec
     */
    eProsima_user_DllExport void time_of_validity_attosec(
            int32_t _time_of_validity_attosec);

    /*!
     * @brief This function returns the value of member time_of_validity_attosec
     * @return Value of member time_of_validity_attosec
     */
    eProsima_user_DllExport int32_t time_of_validity_attosec() const;

    /*!
     * @brief This function returns a reference to member time_of_validity_attosec
     * @return Reference to member time_of_validity_attosec
     */
    eProsima_user_DllExport int32_t& time_of_validity_attosec();


    /*!
     * @brief This function sets a value in member clock_id1
     * @param _clock_id1 New value for member clock_id1
     */
    eProsima_user_DllExport void clock_id1(
            uint8_t _clock_id1);

    /*!
     * @brief This function returns the value of member clock_id1
     * @return Value of member clock_id1
     */
    eProsima_user_DllExport uint8_t clock_id1() const;

    /*!
     * @brief This function returns a reference to member clock_id1
     * @return Reference to member clock_id1
     */
    eProsima_user_DllExport uint8_t& clock_id1();


    /*!
     * @brief This function sets a value in member clock_id2
     * @param _clock_id2 New value for member clock_id2
     */
    eProsima_user_DllExport void clock_id2(
            uint8_t _clock_id2);

    /*!
     * @brief This function returns the value of member clock_id2
     * @return Value of member clock_id2
     */
    eProsima_user_DllExport uint8_t clock_id2() const;

    /*!
     * @brief This function returns a reference to member clock_id2
     * @return Reference to member clock_id2
     */
    eProsima_user_DllExport uint8_t& clock_id2();


    /*!
     * @brief This function sets a value in member time_diff_nsec
     * @param _time_diff_nsec New value for member time_diff_nsec
     */
    eProsima_user_DllExport void time_diff_nsec(
            int64_t _time_diff_nsec);

    /*!
     * @brief This function returns the value of member time_diff_nsec
     * @return Value of member time_diff_nsec
     */
    eProsima_user_DllExport int64_t time_diff_nsec() const;

    /*!
     * @brief This function returns a reference to member time_diff_nsec
     * @return Reference to member time_diff_nsec
     */
    eProsima_user_DllExport int64_t& time_diff_nsec();


    /*!
     * @brief This function sets a value in member time_diff_attosec
     * @param _time_diff_attosec New value for member time_diff_attosec
     */
    eProsima_user_DllExport void time_diff_attosec(
            int32_t _time_diff_attosec);

    /*!
     * @brief This function returns the value of member time_diff_attosec
     * @return Value of member time_diff_attosec
     */
    eProsima_user_DllExport int32_t time_diff_attosec() const;

    /*!
     * @brief This function returns a reference to member time_diff_attosec
     * @return Reference to member time_diff_attosec
     */
    eProsima_user_DllExport int32_t& time_diff_attosec();


    /*!
     * @brief This function sets a value in member digits_of_precision
     * @param _digits_of_precision New value for member digits_of_precision
     */
    eProsima_user_DllExport void digits_of_precision(
            uint8_t _digits_of_precision);

    /*!
     * @brief This function returns the value of member digits_of_precision
     * @return Value of member digits_of_precision
     */
    eProsima_user_DllExport uint8_t digits_of_precision() const;

    /*!
     * @brief This function returns a reference to member digits_of_precision
     * @return Reference to member digits_of_precision
     */
    eProsima_user_DllExport uint8_t& digits_of_precision();


    /*!
     * @brief This function sets a value in member freq_diff
     * @param _freq_diff New value for member freq_diff
     */
    eProsima_user_DllExport void freq_diff(
            double _freq_diff);

    /*!
     * @brief This function returns the value of member freq_diff
     * @return Value of member freq_diff
     */
    eProsima_user_DllExport double freq_diff() const;

    /*!
     * @brief This function returns a reference to member freq_diff
     * @return Reference to member freq_diff
     */
    eProsima_user_DllExport double& freq_diff();


    /*!
     * @brief This function copies the value in member covariance
     * @param _covariance New value to be copied in member covariance
     */
    eProsima_user_DllExport void covariance(
            const std::vector<double>& _covariance);

    /*!
     * @brief This function moves the value in member covariance
     * @param _covariance New value to be moved in member covariance
     */
    eProsima_user_DllExport void covariance(
            std::vector<double>&& _covariance);

    /*!
     * @brief This function returns a constant reference to member covariance
     * @return Constant reference to member covariance
     */
    eProsima_user_DllExport const std::vector<double>& covariance() const;

    /*!
     * @brief This function returns a reference to member covariance
     * @return Reference to member covariance
     */
    eProsima_user_DllExport std::vector<double>& covariance();


    /*!
     * @brief This function sets a value in member error_model
     * @param _error_model New value for member error_model
     */
    eProsima_user_DllExport void error_model(
            aspn23_dds::MeasurementTimeFrequencyDifferenceErrorModelValue _error_model);

    /*!
     * @brief This function returns the value of member error_model
     * @return Value of member error_model
     */
    eProsima_user_DllExport aspn23_dds::MeasurementTimeFrequencyDifferenceErrorModelValue error_model() const;

    /*!
     * @brief This function returns a reference to member error_model
     * @return Reference to member error_model
     */
    eProsima_user_DllExport aspn23_dds::MeasurementTimeFrequencyDifferenceErrorModelValue& error_model();


    /*!
     * @brief This function sets a value in member num_error_model_params
     * @param _num_error_model_params New value for member num_error_model_params
     */
    eProsima_user_DllExport void num_error_model_params(
            uint16_t _num_error_model_params);

    /*!
     * @brief This function returns the value of member num_error_model_params
     * @return Value of member num_error_model_params
     */
    eProsima_user_DllExport uint16_t num_error_model_params() const;

    /*!
     * @brief This function returns a reference to member num_error_model_params
     * @return Reference to member num_error_model_params
     */
    eProsima_user_DllExport uint16_t& num_error_model_params();


    /*!
     * @brief This function copies the value in member error_model_params
     * @param _error_model_params New value to be copied in member error_model_params
     */
    eProsima_user_DllExport void error_model_params(
            const std::vector<double>& _error_model_params);

    /*!
     * @brief This function moves the value in member error_model_params
     * @param _error_model_params New value to be moved in member error_model_params
     */
    eProsima_user_DllExport void error_model_params(
            std::vector<double>&& _error_model_params);

    /*!
     * @brief This function returns a constant reference to member error_model_params
     * @return Constant reference to member error_model_params
     */
    eProsima_user_DllExport const std::vector<double>& error_model_params() const;

    /*!
     * @brief This function returns a reference to member error_model_params
     * @return Reference to member error_model_params
     */
    eProsima_user_DllExport std::vector<double>& error_model_params();


    /*!
     * @brief This function sets a value in member num_integrity
     * @param _num_integrity New value for member num_integrity
     */
    eProsima_user_DllExport void num_integrity(
            uint8_t _num_integrity);

    /*!
     * @brief This function returns the value of member num_integrity
     * @return Value of member num_integrity
     */
    eProsima_user_DllExport uint8_t num_integrity() const;

    /*!
     * @brief This function returns a reference to member num_integrity
     * @return Reference to member num_integrity
     */
    eProsima_user_DllExport uint8_t& num_integrity();


    /*!
     * @brief This function copies the value in member integrity
     * @param _integrity New value to be copied in member integrity
     */
    eProsima_user_DllExport void integrity(
            const std::vector<aspn23_dds::TypeIntegrity>& _integrity);

    /*!
     * @brief This function moves the value in member integrity
     * @param _integrity New value to be moved in member integrity
     */
    eProsima_user_DllExport void integrity(
            std::vector<aspn23_dds::TypeIntegrity>&& _integrity);

    /*!
     * @brief This function returns a constant reference to member integrity
     * @return Constant reference to member integrity
     */
    eProsima_user_DllExport const std::vector<aspn23_dds::TypeIntegrity>& integrity() const;

    /*!
     * @brief This function returns a reference to member integrity
     * @return Reference to member integrity
     */
    eProsima_user_DllExport std::vector<aspn23_dds::TypeIntegrity>& integrity();

private:

    aspn23_dds::TypeHeader m_header;
    aspn23_dds::TypeTimestamp m_time_of_validity;
    int32_t m_time_of_validity_attosec{0};
    uint8_t m_clock_id1{0};
    uint8_t m_clock_id2{0};
    int64_t m_time_diff_nsec{0};
    int32_t m_time_diff_attosec{0};
    uint8_t m_digits_of_precision{0};
    double m_freq_diff{0.0};
    std::vector<double> m_covariance;
    aspn23_dds::MeasurementTimeFrequencyDifferenceErrorModelValue m_error_model{aspn23_dds::ASPN23_MEASUREMENT_TIME_FREQUENCY_DIFFERENCE_ERROR_MODEL_NONE};
    uint16_t m_num_error_model_params{0};
    std::vector<double> m_error_model_params;
    uint8_t m_num_integrity{0};
    std::vector<aspn23_dds::TypeIntegrity> m_integrity;

};

} // namespace aspn23_dds

#endif // _FAST_DDS_GENERATED_ASPN23_DDS_MEASUREMENTTIMEFREQUENCYDIFFERENCE_H_



