// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file MeasurementPositionAttitude.cpp
 * This source file contains the implementation of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "MeasurementPositionAttitude.h"

#include <fastcdr/Cdr.h>


#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>


namespace aspn23_dds {





MeasurementPositionAttitude::MeasurementPositionAttitude()
{
}

MeasurementPositionAttitude::~MeasurementPositionAttitude()
{
}

MeasurementPositionAttitude::MeasurementPositionAttitude(
        const MeasurementPositionAttitude& x)
{
    m_header = x.m_header;
    m_time_of_validity = x.m_time_of_validity;
    m_reference_frame = x.m_reference_frame;
    m_p1 = x.m_p1;
    m_p2 = x.m_p2;
    m_p3 = x.m_p3;
    m_quaternion = x.m_quaternion;
    m_covariance = x.m_covariance;
    m_error_model = x.m_error_model;
    m_num_error_model_params = x.m_num_error_model_params;
    m_error_model_params = x.m_error_model_params;
    m_num_integrity = x.m_num_integrity;
    m_integrity = x.m_integrity;
}

MeasurementPositionAttitude::MeasurementPositionAttitude(
        MeasurementPositionAttitude&& x) noexcept
{
    m_header = std::move(x.m_header);
    m_time_of_validity = std::move(x.m_time_of_validity);
    m_reference_frame = x.m_reference_frame;
    m_p1 = x.m_p1;
    m_p2 = x.m_p2;
    m_p3 = x.m_p3;
    m_quaternion = std::move(x.m_quaternion);
    m_covariance = std::move(x.m_covariance);
    m_error_model = x.m_error_model;
    m_num_error_model_params = x.m_num_error_model_params;
    m_error_model_params = std::move(x.m_error_model_params);
    m_num_integrity = x.m_num_integrity;
    m_integrity = std::move(x.m_integrity);
}

MeasurementPositionAttitude& MeasurementPositionAttitude::operator =(
        const MeasurementPositionAttitude& x)
{

    m_header = x.m_header;
    m_time_of_validity = x.m_time_of_validity;
    m_reference_frame = x.m_reference_frame;
    m_p1 = x.m_p1;
    m_p2 = x.m_p2;
    m_p3 = x.m_p3;
    m_quaternion = x.m_quaternion;
    m_covariance = x.m_covariance;
    m_error_model = x.m_error_model;
    m_num_error_model_params = x.m_num_error_model_params;
    m_error_model_params = x.m_error_model_params;
    m_num_integrity = x.m_num_integrity;
    m_integrity = x.m_integrity;
    return *this;
}

MeasurementPositionAttitude& MeasurementPositionAttitude::operator =(
        MeasurementPositionAttitude&& x) noexcept
{

    m_header = std::move(x.m_header);
    m_time_of_validity = std::move(x.m_time_of_validity);
    m_reference_frame = x.m_reference_frame;
    m_p1 = x.m_p1;
    m_p2 = x.m_p2;
    m_p3 = x.m_p3;
    m_quaternion = std::move(x.m_quaternion);
    m_covariance = std::move(x.m_covariance);
    m_error_model = x.m_error_model;
    m_num_error_model_params = x.m_num_error_model_params;
    m_error_model_params = std::move(x.m_error_model_params);
    m_num_integrity = x.m_num_integrity;
    m_integrity = std::move(x.m_integrity);
    return *this;
}

bool MeasurementPositionAttitude::operator ==(
        const MeasurementPositionAttitude& x) const
{
    return (m_header == x.m_header &&
           m_time_of_validity == x.m_time_of_validity &&
           m_reference_frame == x.m_reference_frame &&
           m_p1 == x.m_p1 &&
           m_p2 == x.m_p2 &&
           m_p3 == x.m_p3 &&
           m_quaternion == x.m_quaternion &&
           m_covariance == x.m_covariance &&
           m_error_model == x.m_error_model &&
           m_num_error_model_params == x.m_num_error_model_params &&
           m_error_model_params == x.m_error_model_params &&
           m_num_integrity == x.m_num_integrity &&
           m_integrity == x.m_integrity);
}

bool MeasurementPositionAttitude::operator !=(
        const MeasurementPositionAttitude& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function copies the value in member header
 * @param _header New value to be copied in member header
 */
void MeasurementPositionAttitude::header(
        const aspn23_dds::TypeHeader& _header)
{
    m_header = _header;
}

/*!
 * @brief This function moves the value in member header
 * @param _header New value to be moved in member header
 */
void MeasurementPositionAttitude::header(
        aspn23_dds::TypeHeader&& _header)
{
    m_header = std::move(_header);
}

/*!
 * @brief This function returns a constant reference to member header
 * @return Constant reference to member header
 */
const aspn23_dds::TypeHeader& MeasurementPositionAttitude::header() const
{
    return m_header;
}

/*!
 * @brief This function returns a reference to member header
 * @return Reference to member header
 */
aspn23_dds::TypeHeader& MeasurementPositionAttitude::header()
{
    return m_header;
}


/*!
 * @brief This function copies the value in member time_of_validity
 * @param _time_of_validity New value to be copied in member time_of_validity
 */
void MeasurementPositionAttitude::time_of_validity(
        const aspn23_dds::TypeTimestamp& _time_of_validity)
{
    m_time_of_validity = _time_of_validity;
}

/*!
 * @brief This function moves the value in member time_of_validity
 * @param _time_of_validity New value to be moved in member time_of_validity
 */
void MeasurementPositionAttitude::time_of_validity(
        aspn23_dds::TypeTimestamp&& _time_of_validity)
{
    m_time_of_validity = std::move(_time_of_validity);
}

/*!
 * @brief This function returns a constant reference to member time_of_validity
 * @return Constant reference to member time_of_validity
 */
const aspn23_dds::TypeTimestamp& MeasurementPositionAttitude::time_of_validity() const
{
    return m_time_of_validity;
}

/*!
 * @brief This function returns a reference to member time_of_validity
 * @return Reference to member time_of_validity
 */
aspn23_dds::TypeTimestamp& MeasurementPositionAttitude::time_of_validity()
{
    return m_time_of_validity;
}


/*!
 * @brief This function sets a value in member reference_frame
 * @param _reference_frame New value for member reference_frame
 */
void MeasurementPositionAttitude::reference_frame(
        aspn23_dds::MeasurementPositionAttitudeReferenceFrameValue _reference_frame)
{
    m_reference_frame = _reference_frame;
}

/*!
 * @brief This function returns the value of member reference_frame
 * @return Value of member reference_frame
 */
aspn23_dds::MeasurementPositionAttitudeReferenceFrameValue MeasurementPositionAttitude::reference_frame() const
{
    return m_reference_frame;
}

/*!
 * @brief This function returns a reference to member reference_frame
 * @return Reference to member reference_frame
 */
aspn23_dds::MeasurementPositionAttitudeReferenceFrameValue& MeasurementPositionAttitude::reference_frame()
{
    return m_reference_frame;
}


/*!
 * @brief This function sets a value in member p1
 * @param _p1 New value for member p1
 */
void MeasurementPositionAttitude::p1(
        double _p1)
{
    m_p1 = _p1;
}

/*!
 * @brief This function returns the value of member p1
 * @return Value of member p1
 */
double MeasurementPositionAttitude::p1() const
{
    return m_p1;
}

/*!
 * @brief This function returns a reference to member p1
 * @return Reference to member p1
 */
double& MeasurementPositionAttitude::p1()
{
    return m_p1;
}


/*!
 * @brief This function sets a value in member p2
 * @param _p2 New value for member p2
 */
void MeasurementPositionAttitude::p2(
        double _p2)
{
    m_p2 = _p2;
}

/*!
 * @brief This function returns the value of member p2
 * @return Value of member p2
 */
double MeasurementPositionAttitude::p2() const
{
    return m_p2;
}

/*!
 * @brief This function returns a reference to member p2
 * @return Reference to member p2
 */
double& MeasurementPositionAttitude::p2()
{
    return m_p2;
}


/*!
 * @brief This function sets a value in member p3
 * @param _p3 New value for member p3
 */
void MeasurementPositionAttitude::p3(
        double _p3)
{
    m_p3 = _p3;
}

/*!
 * @brief This function returns the value of member p3
 * @return Value of member p3
 */
double MeasurementPositionAttitude::p3() const
{
    return m_p3;
}

/*!
 * @brief This function returns a reference to member p3
 * @return Reference to member p3
 */
double& MeasurementPositionAttitude::p3()
{
    return m_p3;
}


/*!
 * @brief This function copies the value in member quaternion
 * @param _quaternion New value to be copied in member quaternion
 */
void MeasurementPositionAttitude::quaternion(
        const std::array<double, 4>& _quaternion)
{
    m_quaternion = _quaternion;
}

/*!
 * @brief This function moves the value in member quaternion
 * @param _quaternion New value to be moved in member quaternion
 */
void MeasurementPositionAttitude::quaternion(
        std::array<double, 4>&& _quaternion)
{
    m_quaternion = std::move(_quaternion);
}

/*!
 * @brief This function returns a constant reference to member quaternion
 * @return Constant reference to member quaternion
 */
const std::array<double, 4>& MeasurementPositionAttitude::quaternion() const
{
    return m_quaternion;
}

/*!
 * @brief This function returns a reference to member quaternion
 * @return Reference to member quaternion
 */
std::array<double, 4>& MeasurementPositionAttitude::quaternion()
{
    return m_quaternion;
}


/*!
 * @brief This function copies the value in member covariance
 * @param _covariance New value to be copied in member covariance
 */
void MeasurementPositionAttitude::covariance(
        const std::vector<double>& _covariance)
{
    m_covariance = _covariance;
}

/*!
 * @brief This function moves the value in member covariance
 * @param _covariance New value to be moved in member covariance
 */
void MeasurementPositionAttitude::covariance(
        std::vector<double>&& _covariance)
{
    m_covariance = std::move(_covariance);
}

/*!
 * @brief This function returns a constant reference to member covariance
 * @return Constant reference to member covariance
 */
const std::vector<double>& MeasurementPositionAttitude::covariance() const
{
    return m_covariance;
}

/*!
 * @brief This function returns a reference to member covariance
 * @return Reference to member covariance
 */
std::vector<double>& MeasurementPositionAttitude::covariance()
{
    return m_covariance;
}


/*!
 * @brief This function sets a value in member error_model
 * @param _error_model New value for member error_model
 */
void MeasurementPositionAttitude::error_model(
        aspn23_dds::MeasurementPositionAttitudeErrorModelValue _error_model)
{
    m_error_model = _error_model;
}

/*!
 * @brief This function returns the value of member error_model
 * @return Value of member error_model
 */
aspn23_dds::MeasurementPositionAttitudeErrorModelValue MeasurementPositionAttitude::error_model() const
{
    return m_error_model;
}

/*!
 * @brief This function returns a reference to member error_model
 * @return Reference to member error_model
 */
aspn23_dds::MeasurementPositionAttitudeErrorModelValue& MeasurementPositionAttitude::error_model()
{
    return m_error_model;
}


/*!
 * @brief This function sets a value in member num_error_model_params
 * @param _num_error_model_params New value for member num_error_model_params
 */
void MeasurementPositionAttitude::num_error_model_params(
        uint16_t _num_error_model_params)
{
    m_num_error_model_params = _num_error_model_params;
}

/*!
 * @brief This function returns the value of member num_error_model_params
 * @return Value of member num_error_model_params
 */
uint16_t MeasurementPositionAttitude::num_error_model_params() const
{
    return m_num_error_model_params;
}

/*!
 * @brief This function returns a reference to member num_error_model_params
 * @return Reference to member num_error_model_params
 */
uint16_t& MeasurementPositionAttitude::num_error_model_params()
{
    return m_num_error_model_params;
}


/*!
 * @brief This function copies the value in member error_model_params
 * @param _error_model_params New value to be copied in member error_model_params
 */
void MeasurementPositionAttitude::error_model_params(
        const std::vector<double>& _error_model_params)
{
    m_error_model_params = _error_model_params;
}

/*!
 * @brief This function moves the value in member error_model_params
 * @param _error_model_params New value to be moved in member error_model_params
 */
void MeasurementPositionAttitude::error_model_params(
        std::vector<double>&& _error_model_params)
{
    m_error_model_params = std::move(_error_model_params);
}

/*!
 * @brief This function returns a constant reference to member error_model_params
 * @return Constant reference to member error_model_params
 */
const std::vector<double>& MeasurementPositionAttitude::error_model_params() const
{
    return m_error_model_params;
}

/*!
 * @brief This function returns a reference to member error_model_params
 * @return Reference to member error_model_params
 */
std::vector<double>& MeasurementPositionAttitude::error_model_params()
{
    return m_error_model_params;
}


/*!
 * @brief This function sets a value in member num_integrity
 * @param _num_integrity New value for member num_integrity
 */
void MeasurementPositionAttitude::num_integrity(
        uint8_t _num_integrity)
{
    m_num_integrity = _num_integrity;
}

/*!
 * @brief This function returns the value of member num_integrity
 * @return Value of member num_integrity
 */
uint8_t MeasurementPositionAttitude::num_integrity() const
{
    return m_num_integrity;
}

/*!
 * @brief This function returns a reference to member num_integrity
 * @return Reference to member num_integrity
 */
uint8_t& MeasurementPositionAttitude::num_integrity()
{
    return m_num_integrity;
}


/*!
 * @brief This function copies the value in member integrity
 * @param _integrity New value to be copied in member integrity
 */
void MeasurementPositionAttitude::integrity(
        const std::vector<aspn23_dds::TypeIntegrity>& _integrity)
{
    m_integrity = _integrity;
}

/*!
 * @brief This function moves the value in member integrity
 * @param _integrity New value to be moved in member integrity
 */
void MeasurementPositionAttitude::integrity(
        std::vector<aspn23_dds::TypeIntegrity>&& _integrity)
{
    m_integrity = std::move(_integrity);
}

/*!
 * @brief This function returns a constant reference to member integrity
 * @return Constant reference to member integrity
 */
const std::vector<aspn23_dds::TypeIntegrity>& MeasurementPositionAttitude::integrity() const
{
    return m_integrity;
}

/*!
 * @brief This function returns a reference to member integrity
 * @return Reference to member integrity
 */
std::vector<aspn23_dds::TypeIntegrity>& MeasurementPositionAttitude::integrity()
{
    return m_integrity;
}




} // namespace aspn23_dds
// Include auxiliary functions like for serializing/deserializing.
#include "MeasurementPositionAttitudeCdrAux.ipp"

