// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file MeasurementAttitude3D.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_ASPN23_DDS_MEASUREMENTATTITUDE3D_H_
#define _FAST_DDS_GENERATED_ASPN23_DDS_MEASUREMENTATTITUDE3D_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>

#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>

#include "TypeHeader.h"
#include "TypeTimestamp.h"
#include "TypeIntegrity.h"


#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(MEASUREMENTATTITUDE3D_SOURCE)
#define MEASUREMENTATTITUDE3D_DllAPI __declspec( dllexport )
#else
#define MEASUREMENTATTITUDE3D_DllAPI __declspec( dllimport )
#endif // MEASUREMENTATTITUDE3D_SOURCE
#else
#define MEASUREMENTATTITUDE3D_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define MEASUREMENTATTITUDE3D_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima



namespace aspn23_dds {

/*!
 * @brief This class represents the enumeration MeasurementAttitude3DReferenceFrameValue defined by the user in the IDL file.
 * @ingroup MeasurementAttitude3D
 */
enum MeasurementAttitude3DReferenceFrameValue : uint32_t
{
    ASPN23_MEASUREMENT_ATTITUDE_3D_REFERENCE_FRAME_ECI,
    ASPN23_MEASUREMENT_ATTITUDE_3D_REFERENCE_FRAME_ECEF,
    ASPN23_MEASUREMENT_ATTITUDE_3D_REFERENCE_FRAME_NED
};
/*!
 * @brief This class represents the enumeration MeasurementAttitude3DErrorModelValue defined by the user in the IDL file.
 * @ingroup MeasurementAttitude3D
 */
enum MeasurementAttitude3DErrorModelValue : uint32_t
{
    ASPN23_MEASUREMENT_ATTITUDE_3D_ERROR_MODEL_NONE
};




/*!
 * @brief This class represents the structure MeasurementAttitude3D defined by the user in the IDL file.
 * @ingroup MeasurementAttitude3D
 */
class MeasurementAttitude3D
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport MeasurementAttitude3D();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~MeasurementAttitude3D();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object aspn23_dds::MeasurementAttitude3D that will be copied.
     */
    eProsima_user_DllExport MeasurementAttitude3D(
            const MeasurementAttitude3D& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object aspn23_dds::MeasurementAttitude3D that will be copied.
     */
    eProsima_user_DllExport MeasurementAttitude3D(
            MeasurementAttitude3D&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object aspn23_dds::MeasurementAttitude3D that will be copied.
     */
    eProsima_user_DllExport MeasurementAttitude3D& operator =(
            const MeasurementAttitude3D& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object aspn23_dds::MeasurementAttitude3D that will be copied.
     */
    eProsima_user_DllExport MeasurementAttitude3D& operator =(
            MeasurementAttitude3D&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x aspn23_dds::MeasurementAttitude3D object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const MeasurementAttitude3D& x) const;

    /*!
     * @brief Comparison operator.
     * @param x aspn23_dds::MeasurementAttitude3D object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const MeasurementAttitude3D& x) const;

    /*!
     * @brief This function copies the value in member header
     * @param _header New value to be copied in member header
     */
    eProsima_user_DllExport void header(
            const aspn23_dds::TypeHeader& _header);

    /*!
     * @brief This function moves the value in member header
     * @param _header New value to be moved in member header
     */
    eProsima_user_DllExport void header(
            aspn23_dds::TypeHeader&& _header);

    /*!
     * @brief This function returns a constant reference to member header
     * @return Constant reference to member header
     */
    eProsima_user_DllExport const aspn23_dds::TypeHeader& header() const;

    /*!
     * @brief This function returns a reference to member header
     * @return Reference to member header
     */
    eProsima_user_DllExport aspn23_dds::TypeHeader& header();


    /*!
     * @brief This function copies the value in member time_of_validity
     * @param _time_of_validity New value to be copied in member time_of_validity
     */
    eProsima_user_DllExport void time_of_validity(
            const aspn23_dds::TypeTimestamp& _time_of_validity);

    /*!
     * @brief This function moves the value in member time_of_validity
     * @param _time_of_validity New value to be moved in member time_of_validity
     */
    eProsima_user_DllExport void time_of_validity(
            aspn23_dds::TypeTimestamp&& _time_of_validity);

    /*!
     * @brief This function returns a constant reference to member time_of_validity
     * @return Constant reference to member time_of_validity
     */
    eProsima_user_DllExport const aspn23_dds::TypeTimestamp& time_of_validity() const;

    /*!
     * @brief This function returns a reference to member time_of_validity
     * @return Reference to member time_of_validity
     */
    eProsima_user_DllExport aspn23_dds::TypeTimestamp& time_of_validity();


    /*!
     * @brief This function sets a value in member reference_frame
     * @param _reference_frame New value for member reference_frame
     */
    eProsima_user_DllExport void reference_frame(
            aspn23_dds::MeasurementAttitude3DReferenceFrameValue _reference_frame);

    /*!
     * @brief This function returns the value of member reference_frame
     * @return Value of member reference_frame
     */
    eProsima_user_DllExport aspn23_dds::MeasurementAttitude3DReferenceFrameValue reference_frame() const;

    /*!
     * @brief This function returns a reference to member reference_frame
     * @return Reference to member reference_frame
     */
    eProsima_user_DllExport aspn23_dds::MeasurementAttitude3DReferenceFrameValue& reference_frame();


    /*!
     * @brief This function copies the value in member quaternion
     * @param _quaternion New value to be copied in member quaternion
     */
    eProsima_user_DllExport void quaternion(
            const std::array<double, 4>& _quaternion);

    /*!
     * @brief This function moves the value in member quaternion
     * @param _quaternion New value to be moved in member quaternion
     */
    eProsima_user_DllExport void quaternion(
            std::array<double, 4>&& _quaternion);

    /*!
     * @brief This function returns a constant reference to member quaternion
     * @return Constant reference to member quaternion
     */
    eProsima_user_DllExport const std::array<double, 4>& quaternion() const;

    /*!
     * @brief This function returns a reference to member quaternion
     * @return Reference to member quaternion
     */
    eProsima_user_DllExport std::array<double, 4>& quaternion();


    /*!
     * @brief This function copies the value in member tilt_error_covariance
     * @param _tilt_error_covariance New value to be copied in member tilt_error_covariance
     */
    eProsima_user_DllExport void tilt_error_covariance(
            const std::vector<double>& _tilt_error_covariance);

    /*!
     * @brief This function moves the value in member tilt_error_covariance
     * @param _tilt_error_covariance New value to be moved in member tilt_error_covariance
     */
    eProsima_user_DllExport void tilt_error_covariance(
            std::vector<double>&& _tilt_error_covariance);

    /*!
     * @brief This function returns a constant reference to member tilt_error_covariance
     * @return Constant reference to member tilt_error_covariance
     */
    eProsima_user_DllExport const std::vector<double>& tilt_error_covariance() const;

    /*!
     * @brief This function returns a reference to member tilt_error_covariance
     * @return Reference to member tilt_error_covariance
     */
    eProsima_user_DllExport std::vector<double>& tilt_error_covariance();


    /*!
     * @brief This function sets a value in member error_model
     * @param _error_model New value for member error_model
     */
    eProsima_user_DllExport void error_model(
            aspn23_dds::MeasurementAttitude3DErrorModelValue _error_model);

    /*!
     * @brief This function returns the value of member error_model
     * @return Value of member error_model
     */
    eProsima_user_DllExport aspn23_dds::MeasurementAttitude3DErrorModelValue error_model() const;

    /*!
     * @brief This function returns a reference to member error_model
     * @return Reference to member error_model
     */
    eProsima_user_DllExport aspn23_dds::MeasurementAttitude3DErrorModelValue& error_model();


    /*!
     * @brief This function sets a value in member num_error_model_params
     * @param _num_error_model_params New value for member num_error_model_params
     */
    eProsima_user_DllExport void num_error_model_params(
            uint16_t _num_error_model_params);

    /*!
     * @brief This function returns the value of member num_error_model_params
     * @return Value of member num_error_model_params
     */
    eProsima_user_DllExport uint16_t num_error_model_params() const;

    /*!
     * @brief This function returns a reference to member num_error_model_params
     * @return Reference to member num_error_model_params
     */
    eProsima_user_DllExport uint16_t& num_error_model_params();


    /*!
     * @brief This function copies the value in member error_model_params
     * @param _error_model_params New value to be copied in member error_model_params
     */
    eProsima_user_DllExport void error_model_params(
            const std::vector<double>& _error_model_params);

    /*!
     * @brief This function moves the value in member error_model_params
     * @param _error_model_params New value to be moved in member error_model_params
     */
    eProsima_user_DllExport void error_model_params(
            std::vector<double>&& _error_model_params);

    /*!
     * @brief This function returns a constant reference to member error_model_params
     * @return Constant reference to member error_model_params
     */
    eProsima_user_DllExport const std::vector<double>& error_model_params() const;

    /*!
     * @brief This function returns a reference to member error_model_params
     * @return Reference to member error_model_params
     */
    eProsima_user_DllExport std::vector<double>& error_model_params();


    /*!
     * @brief This function sets a value in member num_integrity
     * @param _num_integrity New value for member num_integrity
     */
    eProsima_user_DllExport void num_integrity(
            uint8_t _num_integrity);

    /*!
     * @brief This function returns the value of member num_integrity
     * @return Value of member num_integrity
     */
    eProsima_user_DllExport uint8_t num_integrity() const;

    /*!
     * @brief This function returns a reference to member num_integrity
     * @return Reference to member num_integrity
     */
    eProsima_user_DllExport uint8_t& num_integrity();


    /*!
     * @brief This function copies the value in member integrity
     * @param _integrity New value to be copied in member integrity
     */
    eProsima_user_DllExport void integrity(
            const std::vector<aspn23_dds::TypeIntegrity>& _integrity);

    /*!
     * @brief This function moves the value in member integrity
     * @param _integrity New value to be moved in member integrity
     */
    eProsima_user_DllExport void integrity(
            std::vector<aspn23_dds::TypeIntegrity>&& _integrity);

    /*!
     * @brief This function returns a constant reference to member integrity
     * @return Constant reference to member integrity
     */
    eProsima_user_DllExport const std::vector<aspn23_dds::TypeIntegrity>& integrity() const;

    /*!
     * @brief This function returns a reference to member integrity
     * @return Reference to member integrity
     */
    eProsima_user_DllExport std::vector<aspn23_dds::TypeIntegrity>& integrity();

private:

    aspn23_dds::TypeHeader m_header;
    aspn23_dds::TypeTimestamp m_time_of_validity;
    aspn23_dds::MeasurementAttitude3DReferenceFrameValue m_reference_frame{aspn23_dds::ASPN23_MEASUREMENT_ATTITUDE_3D_REFERENCE_FRAME_ECI};
    std::array<double, 4> m_quaternion{0.0};
    std::vector<double> m_tilt_error_covariance;
    aspn23_dds::MeasurementAttitude3DErrorModelValue m_error_model{aspn23_dds::ASPN23_MEASUREMENT_ATTITUDE_3D_ERROR_MODEL_NONE};
    uint16_t m_num_error_model_params{0};
    std::vector<double> m_error_model_params;
    uint8_t m_num_integrity{0};
    std::vector<aspn23_dds::TypeIntegrity> m_integrity;

};

} // namespace aspn23_dds

#endif // _FAST_DDS_GENERATED_ASPN23_DDS_MEASUREMENTATTITUDE3D_H_



