// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file MetadataImu.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_ASPN23_DDS_METADATAIMU_H_
#define _FAST_DDS_GENERATED_ASPN23_DDS_METADATAIMU_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>

#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>

#include "TypeTimestamp.h"
#include "TypeMetadataheader.h"
#include "TypeMounting.h"


#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(METADATAIMU_SOURCE)
#define METADATAIMU_DllAPI __declspec( dllexport )
#else
#define METADATAIMU_DllAPI __declspec( dllimport )
#endif // METADATAIMU_SOURCE
#else
#define METADATAIMU_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define METADATAIMU_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima



namespace aspn23_dds {

/*!
 * @brief This class represents the enumeration MetadataImuErrorModelValue defined by the user in the IDL file.
 * @ingroup MetadataImu
 */
enum MetadataImuErrorModelValue : uint32_t
{
    ASPN23_METADATA_IMU_ERROR_MODEL_BASIC
};




/*!
 * @brief This class represents the structure MetadataImu defined by the user in the IDL file.
 * @ingroup MetadataImu
 */
class MetadataImu
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport MetadataImu();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~MetadataImu();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object aspn23_dds::MetadataImu that will be copied.
     */
    eProsima_user_DllExport MetadataImu(
            const MetadataImu& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object aspn23_dds::MetadataImu that will be copied.
     */
    eProsima_user_DllExport MetadataImu(
            MetadataImu&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object aspn23_dds::MetadataImu that will be copied.
     */
    eProsima_user_DllExport MetadataImu& operator =(
            const MetadataImu& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object aspn23_dds::MetadataImu that will be copied.
     */
    eProsima_user_DllExport MetadataImu& operator =(
            MetadataImu&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x aspn23_dds::MetadataImu object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const MetadataImu& x) const;

    /*!
     * @brief Comparison operator.
     * @param x aspn23_dds::MetadataImu object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const MetadataImu& x) const;

    /*!
     * @brief This function copies the value in member info
     * @param _info New value to be copied in member info
     */
    eProsima_user_DllExport void info(
            const aspn23_dds::TypeMetadataheader& _info);

    /*!
     * @brief This function moves the value in member info
     * @param _info New value to be moved in member info
     */
    eProsima_user_DllExport void info(
            aspn23_dds::TypeMetadataheader&& _info);

    /*!
     * @brief This function returns a constant reference to member info
     * @return Constant reference to member info
     */
    eProsima_user_DllExport const aspn23_dds::TypeMetadataheader& info() const;

    /*!
     * @brief This function returns a reference to member info
     * @return Reference to member info
     */
    eProsima_user_DllExport aspn23_dds::TypeMetadataheader& info();


    /*!
     * @brief This function copies the value in member time_of_validity
     * @param _time_of_validity New value to be copied in member time_of_validity
     */
    eProsima_user_DllExport void time_of_validity(
            const aspn23_dds::TypeTimestamp& _time_of_validity);

    /*!
     * @brief This function moves the value in member time_of_validity
     * @param _time_of_validity New value to be moved in member time_of_validity
     */
    eProsima_user_DllExport void time_of_validity(
            aspn23_dds::TypeTimestamp&& _time_of_validity);

    /*!
     * @brief This function returns a constant reference to member time_of_validity
     * @return Constant reference to member time_of_validity
     */
    eProsima_user_DllExport const aspn23_dds::TypeTimestamp& time_of_validity() const;

    /*!
     * @brief This function returns a reference to member time_of_validity
     * @return Reference to member time_of_validity
     */
    eProsima_user_DllExport aspn23_dds::TypeTimestamp& time_of_validity();


    /*!
     * @brief This function copies the value in member mounting
     * @param _mounting New value to be copied in member mounting
     */
    eProsima_user_DllExport void mounting(
            const aspn23_dds::TypeMounting& _mounting);

    /*!
     * @brief This function moves the value in member mounting
     * @param _mounting New value to be moved in member mounting
     */
    eProsima_user_DllExport void mounting(
            aspn23_dds::TypeMounting&& _mounting);

    /*!
     * @brief This function returns a constant reference to member mounting
     * @return Constant reference to member mounting
     */
    eProsima_user_DllExport const aspn23_dds::TypeMounting& mounting() const;

    /*!
     * @brief This function returns a reference to member mounting
     * @return Reference to member mounting
     */
    eProsima_user_DllExport aspn23_dds::TypeMounting& mounting();


    /*!
     * @brief This function sets a value in member error_model
     * @param _error_model New value for member error_model
     */
    eProsima_user_DllExport void error_model(
            aspn23_dds::MetadataImuErrorModelValue _error_model);

    /*!
     * @brief This function returns the value of member error_model
     * @return Value of member error_model
     */
    eProsima_user_DllExport aspn23_dds::MetadataImuErrorModelValue error_model() const;

    /*!
     * @brief This function returns a reference to member error_model
     * @return Reference to member error_model
     */
    eProsima_user_DllExport aspn23_dds::MetadataImuErrorModelValue& error_model();


    /*!
     * @brief This function sets a value in member num_error_model_params
     * @param _num_error_model_params New value for member num_error_model_params
     */
    eProsima_user_DllExport void num_error_model_params(
            uint16_t _num_error_model_params);

    /*!
     * @brief This function returns the value of member num_error_model_params
     * @return Value of member num_error_model_params
     */
    eProsima_user_DllExport uint16_t num_error_model_params() const;

    /*!
     * @brief This function returns a reference to member num_error_model_params
     * @return Reference to member num_error_model_params
     */
    eProsima_user_DllExport uint16_t& num_error_model_params();


    /*!
     * @brief This function copies the value in member error_model_params
     * @param _error_model_params New value to be copied in member error_model_params
     */
    eProsima_user_DllExport void error_model_params(
            const std::vector<double>& _error_model_params);

    /*!
     * @brief This function moves the value in member error_model_params
     * @param _error_model_params New value to be moved in member error_model_params
     */
    eProsima_user_DllExport void error_model_params(
            std::vector<double>&& _error_model_params);

    /*!
     * @brief This function returns a constant reference to member error_model_params
     * @return Constant reference to member error_model_params
     */
    eProsima_user_DllExport const std::vector<double>& error_model_params() const;

    /*!
     * @brief This function returns a reference to member error_model_params
     * @return Reference to member error_model_params
     */
    eProsima_user_DllExport std::vector<double>& error_model_params();

private:

    aspn23_dds::TypeMetadataheader m_info;
    aspn23_dds::TypeTimestamp m_time_of_validity;
    aspn23_dds::TypeMounting m_mounting;
    aspn23_dds::MetadataImuErrorModelValue m_error_model{aspn23_dds::ASPN23_METADATA_IMU_ERROR_MODEL_BASIC};
    uint16_t m_num_error_model_params{0};
    std::vector<double> m_error_model_params;

};

} // namespace aspn23_dds

#endif // _FAST_DDS_GENERATED_ASPN23_DDS_METADATAIMU_H_



