// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file MetadataGlonassEphemeris.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_ASPN23_DDS_METADATAGLONASSEPHEMERIS_H_
#define _FAST_DDS_GENERATED_ASPN23_DDS_METADATAGLONASSEPHEMERIS_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>

#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>

#include "TypeTimestamp.h"
#include "TypeMetadataheader.h"


#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(METADATAGLONASSEPHEMERIS_SOURCE)
#define METADATAGLONASSEPHEMERIS_DllAPI __declspec( dllexport )
#else
#define METADATAGLONASSEPHEMERIS_DllAPI __declspec( dllimport )
#endif // METADATAGLONASSEPHEMERIS_SOURCE
#else
#define METADATAGLONASSEPHEMERIS_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define METADATAGLONASSEPHEMERIS_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima



namespace aspn23_dds {



/*!
 * @brief This class represents the structure MetadataGlonassEphemeris defined by the user in the IDL file.
 * @ingroup MetadataGlonassEphemeris
 */
class MetadataGlonassEphemeris
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport MetadataGlonassEphemeris();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~MetadataGlonassEphemeris();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object aspn23_dds::MetadataGlonassEphemeris that will be copied.
     */
    eProsima_user_DllExport MetadataGlonassEphemeris(
            const MetadataGlonassEphemeris& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object aspn23_dds::MetadataGlonassEphemeris that will be copied.
     */
    eProsima_user_DllExport MetadataGlonassEphemeris(
            MetadataGlonassEphemeris&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object aspn23_dds::MetadataGlonassEphemeris that will be copied.
     */
    eProsima_user_DllExport MetadataGlonassEphemeris& operator =(
            const MetadataGlonassEphemeris& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object aspn23_dds::MetadataGlonassEphemeris that will be copied.
     */
    eProsima_user_DllExport MetadataGlonassEphemeris& operator =(
            MetadataGlonassEphemeris&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x aspn23_dds::MetadataGlonassEphemeris object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const MetadataGlonassEphemeris& x) const;

    /*!
     * @brief Comparison operator.
     * @param x aspn23_dds::MetadataGlonassEphemeris object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const MetadataGlonassEphemeris& x) const;

    /*!
     * @brief This function copies the value in member info
     * @param _info New value to be copied in member info
     */
    eProsima_user_DllExport void info(
            const aspn23_dds::TypeMetadataheader& _info);

    /*!
     * @brief This function moves the value in member info
     * @param _info New value to be moved in member info
     */
    eProsima_user_DllExport void info(
            aspn23_dds::TypeMetadataheader&& _info);

    /*!
     * @brief This function returns a constant reference to member info
     * @return Constant reference to member info
     */
    eProsima_user_DllExport const aspn23_dds::TypeMetadataheader& info() const;

    /*!
     * @brief This function returns a reference to member info
     * @return Reference to member info
     */
    eProsima_user_DllExport aspn23_dds::TypeMetadataheader& info();


    /*!
     * @brief This function copies the value in member time_of_validity
     * @param _time_of_validity New value to be copied in member time_of_validity
     */
    eProsima_user_DllExport void time_of_validity(
            const aspn23_dds::TypeTimestamp& _time_of_validity);

    /*!
     * @brief This function moves the value in member time_of_validity
     * @param _time_of_validity New value to be moved in member time_of_validity
     */
    eProsima_user_DllExport void time_of_validity(
            aspn23_dds::TypeTimestamp&& _time_of_validity);

    /*!
     * @brief This function returns a constant reference to member time_of_validity
     * @return Constant reference to member time_of_validity
     */
    eProsima_user_DllExport const aspn23_dds::TypeTimestamp& time_of_validity() const;

    /*!
     * @brief This function returns a reference to member time_of_validity
     * @return Reference to member time_of_validity
     */
    eProsima_user_DllExport aspn23_dds::TypeTimestamp& time_of_validity();


    /*!
     * @brief This function sets a value in member slot_number
     * @param _slot_number New value for member slot_number
     */
    eProsima_user_DllExport void slot_number(
            int32_t _slot_number);

    /*!
     * @brief This function returns the value of member slot_number
     * @return Value of member slot_number
     */
    eProsima_user_DllExport int32_t slot_number() const;

    /*!
     * @brief This function returns a reference to member slot_number
     * @return Reference to member slot_number
     */
    eProsima_user_DllExport int32_t& slot_number();


    /*!
     * @brief This function sets a value in member freq_o
     * @param _freq_o New value for member freq_o
     */
    eProsima_user_DllExport void freq_o(
            int32_t _freq_o);

    /*!
     * @brief This function returns the value of member freq_o
     * @return Value of member freq_o
     */
    eProsima_user_DllExport int32_t freq_o() const;

    /*!
     * @brief This function returns a reference to member freq_o
     * @return Reference to member freq_o
     */
    eProsima_user_DllExport int32_t& freq_o();


    /*!
     * @brief This function sets a value in member n_t
     * @param _n_t New value for member n_t
     */
    eProsima_user_DllExport void n_t(
            int32_t _n_t);

    /*!
     * @brief This function returns the value of member n_t
     * @return Value of member n_t
     */
    eProsima_user_DllExport int32_t n_t() const;

    /*!
     * @brief This function returns a reference to member n_t
     * @return Reference to member n_t
     */
    eProsima_user_DllExport int32_t& n_t();


    /*!
     * @brief This function sets a value in member t_k
     * @param _t_k New value for member t_k
     */
    eProsima_user_DllExport void t_k(
            double _t_k);

    /*!
     * @brief This function returns the value of member t_k
     * @return Value of member t_k
     */
    eProsima_user_DllExport double t_k() const;

    /*!
     * @brief This function returns a reference to member t_k
     * @return Reference to member t_k
     */
    eProsima_user_DllExport double& t_k();


    /*!
     * @brief This function sets a value in member t_b
     * @param _t_b New value for member t_b
     */
    eProsima_user_DllExport void t_b(
            double _t_b);

    /*!
     * @brief This function returns the value of member t_b
     * @return Value of member t_b
     */
    eProsima_user_DllExport double t_b() const;

    /*!
     * @brief This function returns a reference to member t_b
     * @return Reference to member t_b
     */
    eProsima_user_DllExport double& t_b();


    /*!
     * @brief This function sets a value in member gamma_n
     * @param _gamma_n New value for member gamma_n
     */
    eProsima_user_DllExport void gamma_n(
            double _gamma_n);

    /*!
     * @brief This function returns the value of member gamma_n
     * @return Value of member gamma_n
     */
    eProsima_user_DllExport double gamma_n() const;

    /*!
     * @brief This function returns a reference to member gamma_n
     * @return Reference to member gamma_n
     */
    eProsima_user_DllExport double& gamma_n();


    /*!
     * @brief This function sets a value in member tau_n
     * @param _tau_n New value for member tau_n
     */
    eProsima_user_DllExport void tau_n(
            double _tau_n);

    /*!
     * @brief This function returns the value of member tau_n
     * @return Value of member tau_n
     */
    eProsima_user_DllExport double tau_n() const;

    /*!
     * @brief This function returns a reference to member tau_n
     * @return Reference to member tau_n
     */
    eProsima_user_DllExport double& tau_n();


    /*!
     * @brief This function sets a value in member sv_pos_x
     * @param _sv_pos_x New value for member sv_pos_x
     */
    eProsima_user_DllExport void sv_pos_x(
            double _sv_pos_x);

    /*!
     * @brief This function returns the value of member sv_pos_x
     * @return Value of member sv_pos_x
     */
    eProsima_user_DllExport double sv_pos_x() const;

    /*!
     * @brief This function returns a reference to member sv_pos_x
     * @return Reference to member sv_pos_x
     */
    eProsima_user_DllExport double& sv_pos_x();


    /*!
     * @brief This function sets a value in member sv_vel_x
     * @param _sv_vel_x New value for member sv_vel_x
     */
    eProsima_user_DllExport void sv_vel_x(
            double _sv_vel_x);

    /*!
     * @brief This function returns the value of member sv_vel_x
     * @return Value of member sv_vel_x
     */
    eProsima_user_DllExport double sv_vel_x() const;

    /*!
     * @brief This function returns a reference to member sv_vel_x
     * @return Reference to member sv_vel_x
     */
    eProsima_user_DllExport double& sv_vel_x();


    /*!
     * @brief This function sets a value in member sv_accel_x
     * @param _sv_accel_x New value for member sv_accel_x
     */
    eProsima_user_DllExport void sv_accel_x(
            double _sv_accel_x);

    /*!
     * @brief This function returns the value of member sv_accel_x
     * @return Value of member sv_accel_x
     */
    eProsima_user_DllExport double sv_accel_x() const;

    /*!
     * @brief This function returns a reference to member sv_accel_x
     * @return Reference to member sv_accel_x
     */
    eProsima_user_DllExport double& sv_accel_x();


    /*!
     * @brief This function sets a value in member sv_pos_y
     * @param _sv_pos_y New value for member sv_pos_y
     */
    eProsima_user_DllExport void sv_pos_y(
            double _sv_pos_y);

    /*!
     * @brief This function returns the value of member sv_pos_y
     * @return Value of member sv_pos_y
     */
    eProsima_user_DllExport double sv_pos_y() const;

    /*!
     * @brief This function returns a reference to member sv_pos_y
     * @return Reference to member sv_pos_y
     */
    eProsima_user_DllExport double& sv_pos_y();


    /*!
     * @brief This function sets a value in member sv_vel_y
     * @param _sv_vel_y New value for member sv_vel_y
     */
    eProsima_user_DllExport void sv_vel_y(
            double _sv_vel_y);

    /*!
     * @brief This function returns the value of member sv_vel_y
     * @return Value of member sv_vel_y
     */
    eProsima_user_DllExport double sv_vel_y() const;

    /*!
     * @brief This function returns a reference to member sv_vel_y
     * @return Reference to member sv_vel_y
     */
    eProsima_user_DllExport double& sv_vel_y();


    /*!
     * @brief This function sets a value in member sv_accel_y
     * @param _sv_accel_y New value for member sv_accel_y
     */
    eProsima_user_DllExport void sv_accel_y(
            double _sv_accel_y);

    /*!
     * @brief This function returns the value of member sv_accel_y
     * @return Value of member sv_accel_y
     */
    eProsima_user_DllExport double sv_accel_y() const;

    /*!
     * @brief This function returns a reference to member sv_accel_y
     * @return Reference to member sv_accel_y
     */
    eProsima_user_DllExport double& sv_accel_y();


    /*!
     * @brief This function sets a value in member sv_pos_z
     * @param _sv_pos_z New value for member sv_pos_z
     */
    eProsima_user_DllExport void sv_pos_z(
            double _sv_pos_z);

    /*!
     * @brief This function returns the value of member sv_pos_z
     * @return Value of member sv_pos_z
     */
    eProsima_user_DllExport double sv_pos_z() const;

    /*!
     * @brief This function returns a reference to member sv_pos_z
     * @return Reference to member sv_pos_z
     */
    eProsima_user_DllExport double& sv_pos_z();


    /*!
     * @brief This function sets a value in member sv_vel_z
     * @param _sv_vel_z New value for member sv_vel_z
     */
    eProsima_user_DllExport void sv_vel_z(
            double _sv_vel_z);

    /*!
     * @brief This function returns the value of member sv_vel_z
     * @return Value of member sv_vel_z
     */
    eProsima_user_DllExport double sv_vel_z() const;

    /*!
     * @brief This function returns a reference to member sv_vel_z
     * @return Reference to member sv_vel_z
     */
    eProsima_user_DllExport double& sv_vel_z();


    /*!
     * @brief This function sets a value in member sv_accel_z
     * @param _sv_accel_z New value for member sv_accel_z
     */
    eProsima_user_DllExport void sv_accel_z(
            double _sv_accel_z);

    /*!
     * @brief This function returns the value of member sv_accel_z
     * @return Value of member sv_accel_z
     */
    eProsima_user_DllExport double sv_accel_z() const;

    /*!
     * @brief This function returns a reference to member sv_accel_z
     * @return Reference to member sv_accel_z
     */
    eProsima_user_DllExport double& sv_accel_z();

private:

    aspn23_dds::TypeMetadataheader m_info;
    aspn23_dds::TypeTimestamp m_time_of_validity;
    int32_t m_slot_number{0};
    int32_t m_freq_o{0};
    int32_t m_n_t{0};
    double m_t_k{0.0};
    double m_t_b{0.0};
    double m_gamma_n{0.0};
    double m_tau_n{0.0};
    double m_sv_pos_x{0.0};
    double m_sv_vel_x{0.0};
    double m_sv_accel_x{0.0};
    double m_sv_pos_y{0.0};
    double m_sv_vel_y{0.0};
    double m_sv_accel_y{0.0};
    double m_sv_pos_z{0.0};
    double m_sv_vel_z{0.0};
    double m_sv_accel_z{0.0};

};

} // namespace aspn23_dds

#endif // _FAST_DDS_GENERATED_ASPN23_DDS_METADATAGLONASSEPHEMERIS_H_



