// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file MetadataGalileoEphemeris.cpp
 * This source file contains the implementation of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "MetadataGalileoEphemeris.h"

#include <fastcdr/Cdr.h>


#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>


namespace aspn23_dds {



MetadataGalileoEphemeris::MetadataGalileoEphemeris()
{
}

MetadataGalileoEphemeris::~MetadataGalileoEphemeris()
{
}

MetadataGalileoEphemeris::MetadataGalileoEphemeris(
        const MetadataGalileoEphemeris& x)
{
    m_info = x.m_info;
    m_time_of_validity = x.m_time_of_validity;
    m_nav_msg_type = x.m_nav_msg_type;
    m_prn = x.m_prn;
    m_clock = x.m_clock;
    m_orbit = x.m_orbit;
    m_bgd = x.m_bgd;
}

MetadataGalileoEphemeris::MetadataGalileoEphemeris(
        MetadataGalileoEphemeris&& x) noexcept
{
    m_info = std::move(x.m_info);
    m_time_of_validity = std::move(x.m_time_of_validity);
    m_nav_msg_type = x.m_nav_msg_type;
    m_prn = x.m_prn;
    m_clock = std::move(x.m_clock);
    m_orbit = std::move(x.m_orbit);
    m_bgd = x.m_bgd;
}

MetadataGalileoEphemeris& MetadataGalileoEphemeris::operator =(
        const MetadataGalileoEphemeris& x)
{

    m_info = x.m_info;
    m_time_of_validity = x.m_time_of_validity;
    m_nav_msg_type = x.m_nav_msg_type;
    m_prn = x.m_prn;
    m_clock = x.m_clock;
    m_orbit = x.m_orbit;
    m_bgd = x.m_bgd;
    return *this;
}

MetadataGalileoEphemeris& MetadataGalileoEphemeris::operator =(
        MetadataGalileoEphemeris&& x) noexcept
{

    m_info = std::move(x.m_info);
    m_time_of_validity = std::move(x.m_time_of_validity);
    m_nav_msg_type = x.m_nav_msg_type;
    m_prn = x.m_prn;
    m_clock = std::move(x.m_clock);
    m_orbit = std::move(x.m_orbit);
    m_bgd = x.m_bgd;
    return *this;
}

bool MetadataGalileoEphemeris::operator ==(
        const MetadataGalileoEphemeris& x) const
{
    return (m_info == x.m_info &&
           m_time_of_validity == x.m_time_of_validity &&
           m_nav_msg_type == x.m_nav_msg_type &&
           m_prn == x.m_prn &&
           m_clock == x.m_clock &&
           m_orbit == x.m_orbit &&
           m_bgd == x.m_bgd);
}

bool MetadataGalileoEphemeris::operator !=(
        const MetadataGalileoEphemeris& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function copies the value in member info
 * @param _info New value to be copied in member info
 */
void MetadataGalileoEphemeris::info(
        const aspn23_dds::TypeMetadataheader& _info)
{
    m_info = _info;
}

/*!
 * @brief This function moves the value in member info
 * @param _info New value to be moved in member info
 */
void MetadataGalileoEphemeris::info(
        aspn23_dds::TypeMetadataheader&& _info)
{
    m_info = std::move(_info);
}

/*!
 * @brief This function returns a constant reference to member info
 * @return Constant reference to member info
 */
const aspn23_dds::TypeMetadataheader& MetadataGalileoEphemeris::info() const
{
    return m_info;
}

/*!
 * @brief This function returns a reference to member info
 * @return Reference to member info
 */
aspn23_dds::TypeMetadataheader& MetadataGalileoEphemeris::info()
{
    return m_info;
}


/*!
 * @brief This function copies the value in member time_of_validity
 * @param _time_of_validity New value to be copied in member time_of_validity
 */
void MetadataGalileoEphemeris::time_of_validity(
        const aspn23_dds::TypeTimestamp& _time_of_validity)
{
    m_time_of_validity = _time_of_validity;
}

/*!
 * @brief This function moves the value in member time_of_validity
 * @param _time_of_validity New value to be moved in member time_of_validity
 */
void MetadataGalileoEphemeris::time_of_validity(
        aspn23_dds::TypeTimestamp&& _time_of_validity)
{
    m_time_of_validity = std::move(_time_of_validity);
}

/*!
 * @brief This function returns a constant reference to member time_of_validity
 * @return Constant reference to member time_of_validity
 */
const aspn23_dds::TypeTimestamp& MetadataGalileoEphemeris::time_of_validity() const
{
    return m_time_of_validity;
}

/*!
 * @brief This function returns a reference to member time_of_validity
 * @return Reference to member time_of_validity
 */
aspn23_dds::TypeTimestamp& MetadataGalileoEphemeris::time_of_validity()
{
    return m_time_of_validity;
}


/*!
 * @brief This function sets a value in member nav_msg_type
 * @param _nav_msg_type New value for member nav_msg_type
 */
void MetadataGalileoEphemeris::nav_msg_type(
        aspn23_dds::MetadataGalileoEphemerisNavMsgTypeValue _nav_msg_type)
{
    m_nav_msg_type = _nav_msg_type;
}

/*!
 * @brief This function returns the value of member nav_msg_type
 * @return Value of member nav_msg_type
 */
aspn23_dds::MetadataGalileoEphemerisNavMsgTypeValue MetadataGalileoEphemeris::nav_msg_type() const
{
    return m_nav_msg_type;
}

/*!
 * @brief This function returns a reference to member nav_msg_type
 * @return Reference to member nav_msg_type
 */
aspn23_dds::MetadataGalileoEphemerisNavMsgTypeValue& MetadataGalileoEphemeris::nav_msg_type()
{
    return m_nav_msg_type;
}


/*!
 * @brief This function sets a value in member prn
 * @param _prn New value for member prn
 */
void MetadataGalileoEphemeris::prn(
        int32_t _prn)
{
    m_prn = _prn;
}

/*!
 * @brief This function returns the value of member prn
 * @return Value of member prn
 */
int32_t MetadataGalileoEphemeris::prn() const
{
    return m_prn;
}

/*!
 * @brief This function returns a reference to member prn
 * @return Reference to member prn
 */
int32_t& MetadataGalileoEphemeris::prn()
{
    return m_prn;
}


/*!
 * @brief This function copies the value in member clock
 * @param _clock New value to be copied in member clock
 */
void MetadataGalileoEphemeris::clock(
        const aspn23_dds::TypeSatnavClock& _clock)
{
    m_clock = _clock;
}

/*!
 * @brief This function moves the value in member clock
 * @param _clock New value to be moved in member clock
 */
void MetadataGalileoEphemeris::clock(
        aspn23_dds::TypeSatnavClock&& _clock)
{
    m_clock = std::move(_clock);
}

/*!
 * @brief This function returns a constant reference to member clock
 * @return Constant reference to member clock
 */
const aspn23_dds::TypeSatnavClock& MetadataGalileoEphemeris::clock() const
{
    return m_clock;
}

/*!
 * @brief This function returns a reference to member clock
 * @return Reference to member clock
 */
aspn23_dds::TypeSatnavClock& MetadataGalileoEphemeris::clock()
{
    return m_clock;
}


/*!
 * @brief This function copies the value in member orbit
 * @param _orbit New value to be copied in member orbit
 */
void MetadataGalileoEphemeris::orbit(
        const aspn23_dds::TypeKeplerOrbit& _orbit)
{
    m_orbit = _orbit;
}

/*!
 * @brief This function moves the value in member orbit
 * @param _orbit New value to be moved in member orbit
 */
void MetadataGalileoEphemeris::orbit(
        aspn23_dds::TypeKeplerOrbit&& _orbit)
{
    m_orbit = std::move(_orbit);
}

/*!
 * @brief This function returns a constant reference to member orbit
 * @return Constant reference to member orbit
 */
const aspn23_dds::TypeKeplerOrbit& MetadataGalileoEphemeris::orbit() const
{
    return m_orbit;
}

/*!
 * @brief This function returns a reference to member orbit
 * @return Reference to member orbit
 */
aspn23_dds::TypeKeplerOrbit& MetadataGalileoEphemeris::orbit()
{
    return m_orbit;
}


/*!
 * @brief This function sets a value in member bgd
 * @param _bgd New value for member bgd
 */
void MetadataGalileoEphemeris::bgd(
        double _bgd)
{
    m_bgd = _bgd;
}

/*!
 * @brief This function returns the value of member bgd
 * @return Value of member bgd
 */
double MetadataGalileoEphemeris::bgd() const
{
    return m_bgd;
}

/*!
 * @brief This function returns a reference to member bgd
 * @return Reference to member bgd
 */
double& MetadataGalileoEphemeris::bgd()
{
    return m_bgd;
}




} // namespace aspn23_dds
// Include auxiliary functions like for serializing/deserializing.
#include "MetadataGalileoEphemerisCdrAux.ipp"

