// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file TypeSatnavObs.cpp
 * This source file contains the implementation of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "TypeSatnavObs.h"

#include <fastcdr/Cdr.h>


#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>


namespace aspn23_dds {





TypeSatnavObs::TypeSatnavObs()
{
}

TypeSatnavObs::~TypeSatnavObs()
{
}

TypeSatnavObs::TypeSatnavObs(
        const TypeSatnavObs& x)
{
    m_satellite_system = x.m_satellite_system;
    m_signal_descriptor = x.m_signal_descriptor;
    m_prn = x.m_prn;
    m_frequency = x.m_frequency;
    m_pseudorange = x.m_pseudorange;
    m_pseudorange_variance = x.m_pseudorange_variance;
    m_pseudorange_rate_type = x.m_pseudorange_rate_type;
    m_pseudorange_rate = x.m_pseudorange_rate;
    m_pseudorange_rate_variance = x.m_pseudorange_rate_variance;
    m_carrier_phase = x.m_carrier_phase;
    m_carrier_phase_variance = x.m_carrier_phase_variance;
    m_c_n0 = x.m_c_n0;
    m_lock_count = x.m_lock_count;
    m_iono_correction_source = x.m_iono_correction_source;
    m_iono_correction_applied = x.m_iono_correction_applied;
    m_tropo_correction_applied = x.m_tropo_correction_applied;
    m_signal_bias_correction_applied = x.m_signal_bias_correction_applied;
    m_num_integrity = x.m_num_integrity;
    m_integrity = x.m_integrity;
}

TypeSatnavObs::TypeSatnavObs(
        TypeSatnavObs&& x) noexcept
{
    m_satellite_system = std::move(x.m_satellite_system);
    m_signal_descriptor = std::move(x.m_signal_descriptor);
    m_prn = x.m_prn;
    m_frequency = x.m_frequency;
    m_pseudorange = x.m_pseudorange;
    m_pseudorange_variance = x.m_pseudorange_variance;
    m_pseudorange_rate_type = x.m_pseudorange_rate_type;
    m_pseudorange_rate = x.m_pseudorange_rate;
    m_pseudorange_rate_variance = x.m_pseudorange_rate_variance;
    m_carrier_phase = x.m_carrier_phase;
    m_carrier_phase_variance = x.m_carrier_phase_variance;
    m_c_n0 = x.m_c_n0;
    m_lock_count = x.m_lock_count;
    m_iono_correction_source = x.m_iono_correction_source;
    m_iono_correction_applied = x.m_iono_correction_applied;
    m_tropo_correction_applied = x.m_tropo_correction_applied;
    m_signal_bias_correction_applied = x.m_signal_bias_correction_applied;
    m_num_integrity = x.m_num_integrity;
    m_integrity = std::move(x.m_integrity);
}

TypeSatnavObs& TypeSatnavObs::operator =(
        const TypeSatnavObs& x)
{

    m_satellite_system = x.m_satellite_system;
    m_signal_descriptor = x.m_signal_descriptor;
    m_prn = x.m_prn;
    m_frequency = x.m_frequency;
    m_pseudorange = x.m_pseudorange;
    m_pseudorange_variance = x.m_pseudorange_variance;
    m_pseudorange_rate_type = x.m_pseudorange_rate_type;
    m_pseudorange_rate = x.m_pseudorange_rate;
    m_pseudorange_rate_variance = x.m_pseudorange_rate_variance;
    m_carrier_phase = x.m_carrier_phase;
    m_carrier_phase_variance = x.m_carrier_phase_variance;
    m_c_n0 = x.m_c_n0;
    m_lock_count = x.m_lock_count;
    m_iono_correction_source = x.m_iono_correction_source;
    m_iono_correction_applied = x.m_iono_correction_applied;
    m_tropo_correction_applied = x.m_tropo_correction_applied;
    m_signal_bias_correction_applied = x.m_signal_bias_correction_applied;
    m_num_integrity = x.m_num_integrity;
    m_integrity = x.m_integrity;
    return *this;
}

TypeSatnavObs& TypeSatnavObs::operator =(
        TypeSatnavObs&& x) noexcept
{

    m_satellite_system = std::move(x.m_satellite_system);
    m_signal_descriptor = std::move(x.m_signal_descriptor);
    m_prn = x.m_prn;
    m_frequency = x.m_frequency;
    m_pseudorange = x.m_pseudorange;
    m_pseudorange_variance = x.m_pseudorange_variance;
    m_pseudorange_rate_type = x.m_pseudorange_rate_type;
    m_pseudorange_rate = x.m_pseudorange_rate;
    m_pseudorange_rate_variance = x.m_pseudorange_rate_variance;
    m_carrier_phase = x.m_carrier_phase;
    m_carrier_phase_variance = x.m_carrier_phase_variance;
    m_c_n0 = x.m_c_n0;
    m_lock_count = x.m_lock_count;
    m_iono_correction_source = x.m_iono_correction_source;
    m_iono_correction_applied = x.m_iono_correction_applied;
    m_tropo_correction_applied = x.m_tropo_correction_applied;
    m_signal_bias_correction_applied = x.m_signal_bias_correction_applied;
    m_num_integrity = x.m_num_integrity;
    m_integrity = std::move(x.m_integrity);
    return *this;
}

bool TypeSatnavObs::operator ==(
        const TypeSatnavObs& x) const
{
    return (m_satellite_system == x.m_satellite_system &&
           m_signal_descriptor == x.m_signal_descriptor &&
           m_prn == x.m_prn &&
           m_frequency == x.m_frequency &&
           m_pseudorange == x.m_pseudorange &&
           m_pseudorange_variance == x.m_pseudorange_variance &&
           m_pseudorange_rate_type == x.m_pseudorange_rate_type &&
           m_pseudorange_rate == x.m_pseudorange_rate &&
           m_pseudorange_rate_variance == x.m_pseudorange_rate_variance &&
           m_carrier_phase == x.m_carrier_phase &&
           m_carrier_phase_variance == x.m_carrier_phase_variance &&
           m_c_n0 == x.m_c_n0 &&
           m_lock_count == x.m_lock_count &&
           m_iono_correction_source == x.m_iono_correction_source &&
           m_iono_correction_applied == x.m_iono_correction_applied &&
           m_tropo_correction_applied == x.m_tropo_correction_applied &&
           m_signal_bias_correction_applied == x.m_signal_bias_correction_applied &&
           m_num_integrity == x.m_num_integrity &&
           m_integrity == x.m_integrity);
}

bool TypeSatnavObs::operator !=(
        const TypeSatnavObs& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function copies the value in member satellite_system
 * @param _satellite_system New value to be copied in member satellite_system
 */
void TypeSatnavObs::satellite_system(
        const aspn23_dds::TypeSatnavSatelliteSystem& _satellite_system)
{
    m_satellite_system = _satellite_system;
}

/*!
 * @brief This function moves the value in member satellite_system
 * @param _satellite_system New value to be moved in member satellite_system
 */
void TypeSatnavObs::satellite_system(
        aspn23_dds::TypeSatnavSatelliteSystem&& _satellite_system)
{
    m_satellite_system = std::move(_satellite_system);
}

/*!
 * @brief This function returns a constant reference to member satellite_system
 * @return Constant reference to member satellite_system
 */
const aspn23_dds::TypeSatnavSatelliteSystem& TypeSatnavObs::satellite_system() const
{
    return m_satellite_system;
}

/*!
 * @brief This function returns a reference to member satellite_system
 * @return Reference to member satellite_system
 */
aspn23_dds::TypeSatnavSatelliteSystem& TypeSatnavObs::satellite_system()
{
    return m_satellite_system;
}


/*!
 * @brief This function copies the value in member signal_descriptor
 * @param _signal_descriptor New value to be copied in member signal_descriptor
 */
void TypeSatnavObs::signal_descriptor(
        const aspn23_dds::TypeSatnavSignalDescriptor& _signal_descriptor)
{
    m_signal_descriptor = _signal_descriptor;
}

/*!
 * @brief This function moves the value in member signal_descriptor
 * @param _signal_descriptor New value to be moved in member signal_descriptor
 */
void TypeSatnavObs::signal_descriptor(
        aspn23_dds::TypeSatnavSignalDescriptor&& _signal_descriptor)
{
    m_signal_descriptor = std::move(_signal_descriptor);
}

/*!
 * @brief This function returns a constant reference to member signal_descriptor
 * @return Constant reference to member signal_descriptor
 */
const aspn23_dds::TypeSatnavSignalDescriptor& TypeSatnavObs::signal_descriptor() const
{
    return m_signal_descriptor;
}

/*!
 * @brief This function returns a reference to member signal_descriptor
 * @return Reference to member signal_descriptor
 */
aspn23_dds::TypeSatnavSignalDescriptor& TypeSatnavObs::signal_descriptor()
{
    return m_signal_descriptor;
}


/*!
 * @brief This function sets a value in member prn
 * @param _prn New value for member prn
 */
void TypeSatnavObs::prn(
        int16_t _prn)
{
    m_prn = _prn;
}

/*!
 * @brief This function returns the value of member prn
 * @return Value of member prn
 */
int16_t TypeSatnavObs::prn() const
{
    return m_prn;
}

/*!
 * @brief This function returns a reference to member prn
 * @return Reference to member prn
 */
int16_t& TypeSatnavObs::prn()
{
    return m_prn;
}


/*!
 * @brief This function sets a value in member frequency
 * @param _frequency New value for member frequency
 */
void TypeSatnavObs::frequency(
        double _frequency)
{
    m_frequency = _frequency;
}

/*!
 * @brief This function returns the value of member frequency
 * @return Value of member frequency
 */
double TypeSatnavObs::frequency() const
{
    return m_frequency;
}

/*!
 * @brief This function returns a reference to member frequency
 * @return Reference to member frequency
 */
double& TypeSatnavObs::frequency()
{
    return m_frequency;
}


/*!
 * @brief This function copies the value in member pseudorange
 * @param _pseudorange New value to be copied in member pseudorange
 */
void TypeSatnavObs::pseudorange(
        const eprosima::fastcdr::optional<double>& _pseudorange)
{
    m_pseudorange = _pseudorange;
}

/*!
 * @brief This function moves the value in member pseudorange
 * @param _pseudorange New value to be moved in member pseudorange
 */
void TypeSatnavObs::pseudorange(
        eprosima::fastcdr::optional<double>&& _pseudorange)
{
    m_pseudorange = std::move(_pseudorange);
}

/*!
 * @brief This function returns a constant reference to member pseudorange
 * @return Constant reference to member pseudorange
 */
const eprosima::fastcdr::optional<double>& TypeSatnavObs::pseudorange() const
{
    return m_pseudorange;
}

/*!
 * @brief This function returns a reference to member pseudorange
 * @return Reference to member pseudorange
 */
eprosima::fastcdr::optional<double>& TypeSatnavObs::pseudorange()
{
    return m_pseudorange;
}


/*!
 * @brief This function copies the value in member pseudorange_variance
 * @param _pseudorange_variance New value to be copied in member pseudorange_variance
 */
void TypeSatnavObs::pseudorange_variance(
        const eprosima::fastcdr::optional<float>& _pseudorange_variance)
{
    m_pseudorange_variance = _pseudorange_variance;
}

/*!
 * @brief This function moves the value in member pseudorange_variance
 * @param _pseudorange_variance New value to be moved in member pseudorange_variance
 */
void TypeSatnavObs::pseudorange_variance(
        eprosima::fastcdr::optional<float>&& _pseudorange_variance)
{
    m_pseudorange_variance = std::move(_pseudorange_variance);
}

/*!
 * @brief This function returns a constant reference to member pseudorange_variance
 * @return Constant reference to member pseudorange_variance
 */
const eprosima::fastcdr::optional<float>& TypeSatnavObs::pseudorange_variance() const
{
    return m_pseudorange_variance;
}

/*!
 * @brief This function returns a reference to member pseudorange_variance
 * @return Reference to member pseudorange_variance
 */
eprosima::fastcdr::optional<float>& TypeSatnavObs::pseudorange_variance()
{
    return m_pseudorange_variance;
}


/*!
 * @brief This function sets a value in member pseudorange_rate_type
 * @param _pseudorange_rate_type New value for member pseudorange_rate_type
 */
void TypeSatnavObs::pseudorange_rate_type(
        aspn23_dds::TypeSatnavObsPseudorangeRateTypeValue _pseudorange_rate_type)
{
    m_pseudorange_rate_type = _pseudorange_rate_type;
}

/*!
 * @brief This function returns the value of member pseudorange_rate_type
 * @return Value of member pseudorange_rate_type
 */
aspn23_dds::TypeSatnavObsPseudorangeRateTypeValue TypeSatnavObs::pseudorange_rate_type() const
{
    return m_pseudorange_rate_type;
}

/*!
 * @brief This function returns a reference to member pseudorange_rate_type
 * @return Reference to member pseudorange_rate_type
 */
aspn23_dds::TypeSatnavObsPseudorangeRateTypeValue& TypeSatnavObs::pseudorange_rate_type()
{
    return m_pseudorange_rate_type;
}


/*!
 * @brief This function copies the value in member pseudorange_rate
 * @param _pseudorange_rate New value to be copied in member pseudorange_rate
 */
void TypeSatnavObs::pseudorange_rate(
        const eprosima::fastcdr::optional<double>& _pseudorange_rate)
{
    m_pseudorange_rate = _pseudorange_rate;
}

/*!
 * @brief This function moves the value in member pseudorange_rate
 * @param _pseudorange_rate New value to be moved in member pseudorange_rate
 */
void TypeSatnavObs::pseudorange_rate(
        eprosima::fastcdr::optional<double>&& _pseudorange_rate)
{
    m_pseudorange_rate = std::move(_pseudorange_rate);
}

/*!
 * @brief This function returns a constant reference to member pseudorange_rate
 * @return Constant reference to member pseudorange_rate
 */
const eprosima::fastcdr::optional<double>& TypeSatnavObs::pseudorange_rate() const
{
    return m_pseudorange_rate;
}

/*!
 * @brief This function returns a reference to member pseudorange_rate
 * @return Reference to member pseudorange_rate
 */
eprosima::fastcdr::optional<double>& TypeSatnavObs::pseudorange_rate()
{
    return m_pseudorange_rate;
}


/*!
 * @brief This function copies the value in member pseudorange_rate_variance
 * @param _pseudorange_rate_variance New value to be copied in member pseudorange_rate_variance
 */
void TypeSatnavObs::pseudorange_rate_variance(
        const eprosima::fastcdr::optional<float>& _pseudorange_rate_variance)
{
    m_pseudorange_rate_variance = _pseudorange_rate_variance;
}

/*!
 * @brief This function moves the value in member pseudorange_rate_variance
 * @param _pseudorange_rate_variance New value to be moved in member pseudorange_rate_variance
 */
void TypeSatnavObs::pseudorange_rate_variance(
        eprosima::fastcdr::optional<float>&& _pseudorange_rate_variance)
{
    m_pseudorange_rate_variance = std::move(_pseudorange_rate_variance);
}

/*!
 * @brief This function returns a constant reference to member pseudorange_rate_variance
 * @return Constant reference to member pseudorange_rate_variance
 */
const eprosima::fastcdr::optional<float>& TypeSatnavObs::pseudorange_rate_variance() const
{
    return m_pseudorange_rate_variance;
}

/*!
 * @brief This function returns a reference to member pseudorange_rate_variance
 * @return Reference to member pseudorange_rate_variance
 */
eprosima::fastcdr::optional<float>& TypeSatnavObs::pseudorange_rate_variance()
{
    return m_pseudorange_rate_variance;
}


/*!
 * @brief This function copies the value in member carrier_phase
 * @param _carrier_phase New value to be copied in member carrier_phase
 */
void TypeSatnavObs::carrier_phase(
        const eprosima::fastcdr::optional<double>& _carrier_phase)
{
    m_carrier_phase = _carrier_phase;
}

/*!
 * @brief This function moves the value in member carrier_phase
 * @param _carrier_phase New value to be moved in member carrier_phase
 */
void TypeSatnavObs::carrier_phase(
        eprosima::fastcdr::optional<double>&& _carrier_phase)
{
    m_carrier_phase = std::move(_carrier_phase);
}

/*!
 * @brief This function returns a constant reference to member carrier_phase
 * @return Constant reference to member carrier_phase
 */
const eprosima::fastcdr::optional<double>& TypeSatnavObs::carrier_phase() const
{
    return m_carrier_phase;
}

/*!
 * @brief This function returns a reference to member carrier_phase
 * @return Reference to member carrier_phase
 */
eprosima::fastcdr::optional<double>& TypeSatnavObs::carrier_phase()
{
    return m_carrier_phase;
}


/*!
 * @brief This function copies the value in member carrier_phase_variance
 * @param _carrier_phase_variance New value to be copied in member carrier_phase_variance
 */
void TypeSatnavObs::carrier_phase_variance(
        const eprosima::fastcdr::optional<float>& _carrier_phase_variance)
{
    m_carrier_phase_variance = _carrier_phase_variance;
}

/*!
 * @brief This function moves the value in member carrier_phase_variance
 * @param _carrier_phase_variance New value to be moved in member carrier_phase_variance
 */
void TypeSatnavObs::carrier_phase_variance(
        eprosima::fastcdr::optional<float>&& _carrier_phase_variance)
{
    m_carrier_phase_variance = std::move(_carrier_phase_variance);
}

/*!
 * @brief This function returns a constant reference to member carrier_phase_variance
 * @return Constant reference to member carrier_phase_variance
 */
const eprosima::fastcdr::optional<float>& TypeSatnavObs::carrier_phase_variance() const
{
    return m_carrier_phase_variance;
}

/*!
 * @brief This function returns a reference to member carrier_phase_variance
 * @return Reference to member carrier_phase_variance
 */
eprosima::fastcdr::optional<float>& TypeSatnavObs::carrier_phase_variance()
{
    return m_carrier_phase_variance;
}


/*!
 * @brief This function copies the value in member c_n0
 * @param _c_n0 New value to be copied in member c_n0
 */
void TypeSatnavObs::c_n0(
        const eprosima::fastcdr::optional<float>& _c_n0)
{
    m_c_n0 = _c_n0;
}

/*!
 * @brief This function moves the value in member c_n0
 * @param _c_n0 New value to be moved in member c_n0
 */
void TypeSatnavObs::c_n0(
        eprosima::fastcdr::optional<float>&& _c_n0)
{
    m_c_n0 = std::move(_c_n0);
}

/*!
 * @brief This function returns a constant reference to member c_n0
 * @return Constant reference to member c_n0
 */
const eprosima::fastcdr::optional<float>& TypeSatnavObs::c_n0() const
{
    return m_c_n0;
}

/*!
 * @brief This function returns a reference to member c_n0
 * @return Reference to member c_n0
 */
eprosima::fastcdr::optional<float>& TypeSatnavObs::c_n0()
{
    return m_c_n0;
}


/*!
 * @brief This function sets a value in member lock_count
 * @param _lock_count New value for member lock_count
 */
void TypeSatnavObs::lock_count(
        int32_t _lock_count)
{
    m_lock_count = _lock_count;
}

/*!
 * @brief This function returns the value of member lock_count
 * @return Value of member lock_count
 */
int32_t TypeSatnavObs::lock_count() const
{
    return m_lock_count;
}

/*!
 * @brief This function returns a reference to member lock_count
 * @return Reference to member lock_count
 */
int32_t& TypeSatnavObs::lock_count()
{
    return m_lock_count;
}


/*!
 * @brief This function sets a value in member iono_correction_source
 * @param _iono_correction_source New value for member iono_correction_source
 */
void TypeSatnavObs::iono_correction_source(
        aspn23_dds::TypeSatnavObsIonoCorrectionSourceValue _iono_correction_source)
{
    m_iono_correction_source = _iono_correction_source;
}

/*!
 * @brief This function returns the value of member iono_correction_source
 * @return Value of member iono_correction_source
 */
aspn23_dds::TypeSatnavObsIonoCorrectionSourceValue TypeSatnavObs::iono_correction_source() const
{
    return m_iono_correction_source;
}

/*!
 * @brief This function returns a reference to member iono_correction_source
 * @return Reference to member iono_correction_source
 */
aspn23_dds::TypeSatnavObsIonoCorrectionSourceValue& TypeSatnavObs::iono_correction_source()
{
    return m_iono_correction_source;
}


/*!
 * @brief This function sets a value in member iono_correction_applied
 * @param _iono_correction_applied New value for member iono_correction_applied
 */
void TypeSatnavObs::iono_correction_applied(
        bool _iono_correction_applied)
{
    m_iono_correction_applied = _iono_correction_applied;
}

/*!
 * @brief This function returns the value of member iono_correction_applied
 * @return Value of member iono_correction_applied
 */
bool TypeSatnavObs::iono_correction_applied() const
{
    return m_iono_correction_applied;
}

/*!
 * @brief This function returns a reference to member iono_correction_applied
 * @return Reference to member iono_correction_applied
 */
bool& TypeSatnavObs::iono_correction_applied()
{
    return m_iono_correction_applied;
}


/*!
 * @brief This function sets a value in member tropo_correction_applied
 * @param _tropo_correction_applied New value for member tropo_correction_applied
 */
void TypeSatnavObs::tropo_correction_applied(
        bool _tropo_correction_applied)
{
    m_tropo_correction_applied = _tropo_correction_applied;
}

/*!
 * @brief This function returns the value of member tropo_correction_applied
 * @return Value of member tropo_correction_applied
 */
bool TypeSatnavObs::tropo_correction_applied() const
{
    return m_tropo_correction_applied;
}

/*!
 * @brief This function returns a reference to member tropo_correction_applied
 * @return Reference to member tropo_correction_applied
 */
bool& TypeSatnavObs::tropo_correction_applied()
{
    return m_tropo_correction_applied;
}


/*!
 * @brief This function sets a value in member signal_bias_correction_applied
 * @param _signal_bias_correction_applied New value for member signal_bias_correction_applied
 */
void TypeSatnavObs::signal_bias_correction_applied(
        bool _signal_bias_correction_applied)
{
    m_signal_bias_correction_applied = _signal_bias_correction_applied;
}

/*!
 * @brief This function returns the value of member signal_bias_correction_applied
 * @return Value of member signal_bias_correction_applied
 */
bool TypeSatnavObs::signal_bias_correction_applied() const
{
    return m_signal_bias_correction_applied;
}

/*!
 * @brief This function returns a reference to member signal_bias_correction_applied
 * @return Reference to member signal_bias_correction_applied
 */
bool& TypeSatnavObs::signal_bias_correction_applied()
{
    return m_signal_bias_correction_applied;
}


/*!
 * @brief This function sets a value in member num_integrity
 * @param _num_integrity New value for member num_integrity
 */
void TypeSatnavObs::num_integrity(
        uint8_t _num_integrity)
{
    m_num_integrity = _num_integrity;
}

/*!
 * @brief This function returns the value of member num_integrity
 * @return Value of member num_integrity
 */
uint8_t TypeSatnavObs::num_integrity() const
{
    return m_num_integrity;
}

/*!
 * @brief This function returns a reference to member num_integrity
 * @return Reference to member num_integrity
 */
uint8_t& TypeSatnavObs::num_integrity()
{
    return m_num_integrity;
}


/*!
 * @brief This function copies the value in member integrity
 * @param _integrity New value to be copied in member integrity
 */
void TypeSatnavObs::integrity(
        const std::vector<aspn23_dds::TypeIntegrity>& _integrity)
{
    m_integrity = _integrity;
}

/*!
 * @brief This function moves the value in member integrity
 * @param _integrity New value to be moved in member integrity
 */
void TypeSatnavObs::integrity(
        std::vector<aspn23_dds::TypeIntegrity>&& _integrity)
{
    m_integrity = std::move(_integrity);
}

/*!
 * @brief This function returns a constant reference to member integrity
 * @return Constant reference to member integrity
 */
const std::vector<aspn23_dds::TypeIntegrity>& TypeSatnavObs::integrity() const
{
    return m_integrity;
}

/*!
 * @brief This function returns a reference to member integrity
 * @return Reference to member integrity
 */
std::vector<aspn23_dds::TypeIntegrity>& TypeSatnavObs::integrity()
{
    return m_integrity;
}




} // namespace aspn23_dds
// Include auxiliary functions like for serializing/deserializing.
#include "TypeSatnavObsCdrAux.ipp"

