// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file TypeDirection3DToPoint.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_ASPN23_DDS_TYPEDIRECTION3DTOPOINT_H_
#define _FAST_DDS_GENERATED_ASPN23_DDS_TYPEDIRECTION3DTOPOINT_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>

#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>

#include "TypeRemotePoint.h"
#include "TypeImageFeature.h"
#include "TypeIntegrity.h"


#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(TYPEDIRECTION3DTOPOINT_SOURCE)
#define TYPEDIRECTION3DTOPOINT_DllAPI __declspec( dllexport )
#else
#define TYPEDIRECTION3DTOPOINT_DllAPI __declspec( dllimport )
#endif // TYPEDIRECTION3DTOPOINT_SOURCE
#else
#define TYPEDIRECTION3DTOPOINT_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define TYPEDIRECTION3DTOPOINT_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima



namespace aspn23_dds {

/*!
 * @brief This class represents the enumeration TypeDirection3DToPointReferenceFrameValue defined by the user in the IDL file.
 * @ingroup TypeDirection3DToPoint
 */
enum TypeDirection3DToPointReferenceFrameValue : uint32_t
{
    ASPN23_TYPE_DIRECTION_3D_TO_POINT_REFERENCE_FRAME_AZ_EL,
    ASPN23_TYPE_DIRECTION_3D_TO_POINT_REFERENCE_FRAME_PIXEL,
    ASPN23_TYPE_DIRECTION_3D_TO_POINT_REFERENCE_FRAME_NORMALIZED_IMAGE,
    ASPN23_TYPE_DIRECTION_3D_TO_POINT_REFERENCE_FRAME_SINE_SPACE
};
/*!
 * @brief This class represents the enumeration TypeDirection3DToPointErrorModelValue defined by the user in the IDL file.
 * @ingroup TypeDirection3DToPoint
 */
enum TypeDirection3DToPointErrorModelValue : uint32_t
{
    ASPN23_TYPE_DIRECTION_3D_TO_POINT_ERROR_MODEL_NONE
};




/*!
 * @brief This class represents the structure TypeDirection3DToPoint defined by the user in the IDL file.
 * @ingroup TypeDirection3DToPoint
 */
class TypeDirection3DToPoint
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport TypeDirection3DToPoint();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~TypeDirection3DToPoint();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object aspn23_dds::TypeDirection3DToPoint that will be copied.
     */
    eProsima_user_DllExport TypeDirection3DToPoint(
            const TypeDirection3DToPoint& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object aspn23_dds::TypeDirection3DToPoint that will be copied.
     */
    eProsima_user_DllExport TypeDirection3DToPoint(
            TypeDirection3DToPoint&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object aspn23_dds::TypeDirection3DToPoint that will be copied.
     */
    eProsima_user_DllExport TypeDirection3DToPoint& operator =(
            const TypeDirection3DToPoint& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object aspn23_dds::TypeDirection3DToPoint that will be copied.
     */
    eProsima_user_DllExport TypeDirection3DToPoint& operator =(
            TypeDirection3DToPoint&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x aspn23_dds::TypeDirection3DToPoint object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const TypeDirection3DToPoint& x) const;

    /*!
     * @brief Comparison operator.
     * @param x aspn23_dds::TypeDirection3DToPoint object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const TypeDirection3DToPoint& x) const;

    /*!
     * @brief This function copies the value in member remote_point
     * @param _remote_point New value to be copied in member remote_point
     */
    eProsima_user_DllExport void remote_point(
            const aspn23_dds::TypeRemotePoint& _remote_point);

    /*!
     * @brief This function moves the value in member remote_point
     * @param _remote_point New value to be moved in member remote_point
     */
    eProsima_user_DllExport void remote_point(
            aspn23_dds::TypeRemotePoint&& _remote_point);

    /*!
     * @brief This function returns a constant reference to member remote_point
     * @return Constant reference to member remote_point
     */
    eProsima_user_DllExport const aspn23_dds::TypeRemotePoint& remote_point() const;

    /*!
     * @brief This function returns a reference to member remote_point
     * @return Reference to member remote_point
     */
    eProsima_user_DllExport aspn23_dds::TypeRemotePoint& remote_point();


    /*!
     * @brief This function sets a value in member reference_frame
     * @param _reference_frame New value for member reference_frame
     */
    eProsima_user_DllExport void reference_frame(
            aspn23_dds::TypeDirection3DToPointReferenceFrameValue _reference_frame);

    /*!
     * @brief This function returns the value of member reference_frame
     * @return Value of member reference_frame
     */
    eProsima_user_DllExport aspn23_dds::TypeDirection3DToPointReferenceFrameValue reference_frame() const;

    /*!
     * @brief This function returns a reference to member reference_frame
     * @return Reference to member reference_frame
     */
    eProsima_user_DllExport aspn23_dds::TypeDirection3DToPointReferenceFrameValue& reference_frame();


    /*!
     * @brief This function copies the value in member obs
     * @param _obs New value to be copied in member obs
     */
    eProsima_user_DllExport void obs(
            const std::array<double, 2>& _obs);

    /*!
     * @brief This function moves the value in member obs
     * @param _obs New value to be moved in member obs
     */
    eProsima_user_DllExport void obs(
            std::array<double, 2>&& _obs);

    /*!
     * @brief This function returns a constant reference to member obs
     * @return Constant reference to member obs
     */
    eProsima_user_DllExport const std::array<double, 2>& obs() const;

    /*!
     * @brief This function returns a reference to member obs
     * @return Reference to member obs
     */
    eProsima_user_DllExport std::array<double, 2>& obs();


    /*!
     * @brief This function copies the value in member covariance
     * @param _covariance New value to be copied in member covariance
     */
    eProsima_user_DllExport void covariance(
            const std::vector<double>& _covariance);

    /*!
     * @brief This function moves the value in member covariance
     * @param _covariance New value to be moved in member covariance
     */
    eProsima_user_DllExport void covariance(
            std::vector<double>&& _covariance);

    /*!
     * @brief This function returns a constant reference to member covariance
     * @return Constant reference to member covariance
     */
    eProsima_user_DllExport const std::vector<double>& covariance() const;

    /*!
     * @brief This function returns a reference to member covariance
     * @return Reference to member covariance
     */
    eProsima_user_DllExport std::vector<double>& covariance();


    /*!
     * @brief This function sets a value in member has_observation_characteristics
     * @param _has_observation_characteristics New value for member has_observation_characteristics
     */
    eProsima_user_DllExport void has_observation_characteristics(
            bool _has_observation_characteristics);

    /*!
     * @brief This function returns the value of member has_observation_characteristics
     * @return Value of member has_observation_characteristics
     */
    eProsima_user_DllExport bool has_observation_characteristics() const;

    /*!
     * @brief This function returns a reference to member has_observation_characteristics
     * @return Reference to member has_observation_characteristics
     */
    eProsima_user_DllExport bool& has_observation_characteristics();


    /*!
     * @brief This function copies the value in member observation_characteristics
     * @param _observation_characteristics New value to be copied in member observation_characteristics
     */
    eProsima_user_DllExport void observation_characteristics(
            const aspn23_dds::TypeImageFeature& _observation_characteristics);

    /*!
     * @brief This function moves the value in member observation_characteristics
     * @param _observation_characteristics New value to be moved in member observation_characteristics
     */
    eProsima_user_DllExport void observation_characteristics(
            aspn23_dds::TypeImageFeature&& _observation_characteristics);

    /*!
     * @brief This function returns a constant reference to member observation_characteristics
     * @return Constant reference to member observation_characteristics
     */
    eProsima_user_DllExport const aspn23_dds::TypeImageFeature& observation_characteristics() const;

    /*!
     * @brief This function returns a reference to member observation_characteristics
     * @return Reference to member observation_characteristics
     */
    eProsima_user_DllExport aspn23_dds::TypeImageFeature& observation_characteristics();


    /*!
     * @brief This function sets a value in member error_model
     * @param _error_model New value for member error_model
     */
    eProsima_user_DllExport void error_model(
            aspn23_dds::TypeDirection3DToPointErrorModelValue _error_model);

    /*!
     * @brief This function returns the value of member error_model
     * @return Value of member error_model
     */
    eProsima_user_DllExport aspn23_dds::TypeDirection3DToPointErrorModelValue error_model() const;

    /*!
     * @brief This function returns a reference to member error_model
     * @return Reference to member error_model
     */
    eProsima_user_DllExport aspn23_dds::TypeDirection3DToPointErrorModelValue& error_model();


    /*!
     * @brief This function sets a value in member num_error_model_params
     * @param _num_error_model_params New value for member num_error_model_params
     */
    eProsima_user_DllExport void num_error_model_params(
            uint16_t _num_error_model_params);

    /*!
     * @brief This function returns the value of member num_error_model_params
     * @return Value of member num_error_model_params
     */
    eProsima_user_DllExport uint16_t num_error_model_params() const;

    /*!
     * @brief This function returns a reference to member num_error_model_params
     * @return Reference to member num_error_model_params
     */
    eProsima_user_DllExport uint16_t& num_error_model_params();


    /*!
     * @brief This function copies the value in member error_model_params
     * @param _error_model_params New value to be copied in member error_model_params
     */
    eProsima_user_DllExport void error_model_params(
            const std::vector<double>& _error_model_params);

    /*!
     * @brief This function moves the value in member error_model_params
     * @param _error_model_params New value to be moved in member error_model_params
     */
    eProsima_user_DllExport void error_model_params(
            std::vector<double>&& _error_model_params);

    /*!
     * @brief This function returns a constant reference to member error_model_params
     * @return Constant reference to member error_model_params
     */
    eProsima_user_DllExport const std::vector<double>& error_model_params() const;

    /*!
     * @brief This function returns a reference to member error_model_params
     * @return Reference to member error_model_params
     */
    eProsima_user_DllExport std::vector<double>& error_model_params();


    /*!
     * @brief This function sets a value in member num_integrity
     * @param _num_integrity New value for member num_integrity
     */
    eProsima_user_DllExport void num_integrity(
            uint8_t _num_integrity);

    /*!
     * @brief This function returns the value of member num_integrity
     * @return Value of member num_integrity
     */
    eProsima_user_DllExport uint8_t num_integrity() const;

    /*!
     * @brief This function returns a reference to member num_integrity
     * @return Reference to member num_integrity
     */
    eProsima_user_DllExport uint8_t& num_integrity();


    /*!
     * @brief This function copies the value in member integrity
     * @param _integrity New value to be copied in member integrity
     */
    eProsima_user_DllExport void integrity(
            const std::vector<aspn23_dds::TypeIntegrity>& _integrity);

    /*!
     * @brief This function moves the value in member integrity
     * @param _integrity New value to be moved in member integrity
     */
    eProsima_user_DllExport void integrity(
            std::vector<aspn23_dds::TypeIntegrity>&& _integrity);

    /*!
     * @brief This function returns a constant reference to member integrity
     * @return Constant reference to member integrity
     */
    eProsima_user_DllExport const std::vector<aspn23_dds::TypeIntegrity>& integrity() const;

    /*!
     * @brief This function returns a reference to member integrity
     * @return Reference to member integrity
     */
    eProsima_user_DllExport std::vector<aspn23_dds::TypeIntegrity>& integrity();

private:

    aspn23_dds::TypeRemotePoint m_remote_point;
    aspn23_dds::TypeDirection3DToPointReferenceFrameValue m_reference_frame{aspn23_dds::ASPN23_TYPE_DIRECTION_3D_TO_POINT_REFERENCE_FRAME_AZ_EL};
    std::array<double, 2> m_obs{0.0};
    std::vector<double> m_covariance;
    bool m_has_observation_characteristics{false};
    aspn23_dds::TypeImageFeature m_observation_characteristics;
    aspn23_dds::TypeDirection3DToPointErrorModelValue m_error_model{aspn23_dds::ASPN23_TYPE_DIRECTION_3D_TO_POINT_ERROR_MODEL_NONE};
    uint16_t m_num_error_model_params{0};
    std::vector<double> m_error_model_params;
    uint8_t m_num_integrity{0};
    std::vector<aspn23_dds::TypeIntegrity> m_integrity;

};

} // namespace aspn23_dds

#endif // _FAST_DDS_GENERATED_ASPN23_DDS_TYPEDIRECTION3DTOPOINT_H_



