// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file TypeImageFeature.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_ASPN23_DDS_TYPEIMAGEFEATURE_H_
#define _FAST_DDS_GENERATED_ASPN23_DDS_TYPEIMAGEFEATURE_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>

#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>



#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(TYPEIMAGEFEATURE_SOURCE)
#define TYPEIMAGEFEATURE_DllAPI __declspec( dllexport )
#else
#define TYPEIMAGEFEATURE_DllAPI __declspec( dllimport )
#endif // TYPEIMAGEFEATURE_SOURCE
#else
#define TYPEIMAGEFEATURE_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define TYPEIMAGEFEATURE_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima



namespace aspn23_dds {





/*!
 * @brief This class represents the structure TypeImageFeature defined by the user in the IDL file.
 * @ingroup TypeImageFeature
 */
class TypeImageFeature
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport TypeImageFeature();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~TypeImageFeature();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object aspn23_dds::TypeImageFeature that will be copied.
     */
    eProsima_user_DllExport TypeImageFeature(
            const TypeImageFeature& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object aspn23_dds::TypeImageFeature that will be copied.
     */
    eProsima_user_DllExport TypeImageFeature(
            TypeImageFeature&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object aspn23_dds::TypeImageFeature that will be copied.
     */
    eProsima_user_DllExport TypeImageFeature& operator =(
            const TypeImageFeature& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object aspn23_dds::TypeImageFeature that will be copied.
     */
    eProsima_user_DllExport TypeImageFeature& operator =(
            TypeImageFeature&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x aspn23_dds::TypeImageFeature object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const TypeImageFeature& x) const;

    /*!
     * @brief Comparison operator.
     * @param x aspn23_dds::TypeImageFeature object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const TypeImageFeature& x) const;

    /*!
     * @brief This function sets a value in member response
     * @param _response New value for member response
     */
    eProsima_user_DllExport void response(
            double _response);

    /*!
     * @brief This function returns the value of member response
     * @return Value of member response
     */
    eProsima_user_DllExport double response() const;

    /*!
     * @brief This function returns a reference to member response
     * @return Reference to member response
     */
    eProsima_user_DllExport double& response();


    /*!
     * @brief This function sets a value in member orientation
     * @param _orientation New value for member orientation
     */
    eProsima_user_DllExport void orientation(
            double _orientation);

    /*!
     * @brief This function returns the value of member orientation
     * @return Value of member orientation
     */
    eProsima_user_DllExport double orientation() const;

    /*!
     * @brief This function returns a reference to member orientation
     * @return Reference to member orientation
     */
    eProsima_user_DllExport double& orientation();


    /*!
     * @brief This function sets a value in member size
     * @param _size New value for member size
     */
    eProsima_user_DllExport void size(
            double _size);

    /*!
     * @brief This function returns the value of member size
     * @return Value of member size
     */
    eProsima_user_DllExport double size() const;

    /*!
     * @brief This function returns a reference to member size
     * @return Reference to member size
     */
    eProsima_user_DllExport double& size();


    /*!
     * @brief This function sets a value in member class_id
     * @param _class_id New value for member class_id
     */
    eProsima_user_DllExport void class_id(
            uint16_t _class_id);

    /*!
     * @brief This function returns the value of member class_id
     * @return Value of member class_id
     */
    eProsima_user_DllExport uint16_t class_id() const;

    /*!
     * @brief This function returns a reference to member class_id
     * @return Reference to member class_id
     */
    eProsima_user_DllExport uint16_t& class_id();


    /*!
     * @brief This function sets a value in member octave
     * @param _octave New value for member octave
     */
    eProsima_user_DllExport void octave(
            uint16_t _octave);

    /*!
     * @brief This function returns the value of member octave
     * @return Value of member octave
     */
    eProsima_user_DllExport uint16_t octave() const;

    /*!
     * @brief This function returns a reference to member octave
     * @return Reference to member octave
     */
    eProsima_user_DllExport uint16_t& octave();


    /*!
     * @brief This function sets a value in member descriptor_size
     * @param _descriptor_size New value for member descriptor_size
     */
    eProsima_user_DllExport void descriptor_size(
            uint16_t _descriptor_size);

    /*!
     * @brief This function returns the value of member descriptor_size
     * @return Value of member descriptor_size
     */
    eProsima_user_DllExport uint16_t descriptor_size() const;

    /*!
     * @brief This function returns a reference to member descriptor_size
     * @return Reference to member descriptor_size
     */
    eProsima_user_DllExport uint16_t& descriptor_size();


    /*!
     * @brief This function copies the value in member descriptor
     * @param _descriptor New value to be copied in member descriptor
     */
    eProsima_user_DllExport void descriptor(
            const std::vector<uint8_t>& _descriptor);

    /*!
     * @brief This function moves the value in member descriptor
     * @param _descriptor New value to be moved in member descriptor
     */
    eProsima_user_DllExport void descriptor(
            std::vector<uint8_t>&& _descriptor);

    /*!
     * @brief This function returns a constant reference to member descriptor
     * @return Constant reference to member descriptor
     */
    eProsima_user_DllExport const std::vector<uint8_t>& descriptor() const;

    /*!
     * @brief This function returns a reference to member descriptor
     * @return Reference to member descriptor
     */
    eProsima_user_DllExport std::vector<uint8_t>& descriptor();

private:

    double m_response{0.0};
    double m_orientation{0.0};
    double m_size{0.0};
    uint16_t m_class_id{0};
    uint16_t m_octave{0};
    uint16_t m_descriptor_size{0};
    std::vector<uint8_t> m_descriptor;

};

} // namespace aspn23_dds

#endif // _FAST_DDS_GENERATED_ASPN23_DDS_TYPEIMAGEFEATURE_H_



