// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file TypeSatnavTime.cpp
 * This source file contains the implementation of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "TypeSatnavTime.h"

#include <fastcdr/Cdr.h>


#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>


namespace aspn23_dds {



TypeSatnavTime::TypeSatnavTime()
{
}

TypeSatnavTime::~TypeSatnavTime()
{
}

TypeSatnavTime::TypeSatnavTime(
        const TypeSatnavTime& x)
{
    m_week_number = x.m_week_number;
    m_seconds_of_week = x.m_seconds_of_week;
    m_time_reference = x.m_time_reference;
}

TypeSatnavTime::TypeSatnavTime(
        TypeSatnavTime&& x) noexcept
{
    m_week_number = x.m_week_number;
    m_seconds_of_week = x.m_seconds_of_week;
    m_time_reference = x.m_time_reference;
}

TypeSatnavTime& TypeSatnavTime::operator =(
        const TypeSatnavTime& x)
{

    m_week_number = x.m_week_number;
    m_seconds_of_week = x.m_seconds_of_week;
    m_time_reference = x.m_time_reference;
    return *this;
}

TypeSatnavTime& TypeSatnavTime::operator =(
        TypeSatnavTime&& x) noexcept
{

    m_week_number = x.m_week_number;
    m_seconds_of_week = x.m_seconds_of_week;
    m_time_reference = x.m_time_reference;
    return *this;
}

bool TypeSatnavTime::operator ==(
        const TypeSatnavTime& x) const
{
    return (m_week_number == x.m_week_number &&
           m_seconds_of_week == x.m_seconds_of_week &&
           m_time_reference == x.m_time_reference);
}

bool TypeSatnavTime::operator !=(
        const TypeSatnavTime& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function sets a value in member week_number
 * @param _week_number New value for member week_number
 */
void TypeSatnavTime::week_number(
        uint16_t _week_number)
{
    m_week_number = _week_number;
}

/*!
 * @brief This function returns the value of member week_number
 * @return Value of member week_number
 */
uint16_t TypeSatnavTime::week_number() const
{
    return m_week_number;
}

/*!
 * @brief This function returns a reference to member week_number
 * @return Reference to member week_number
 */
uint16_t& TypeSatnavTime::week_number()
{
    return m_week_number;
}


/*!
 * @brief This function sets a value in member seconds_of_week
 * @param _seconds_of_week New value for member seconds_of_week
 */
void TypeSatnavTime::seconds_of_week(
        double _seconds_of_week)
{
    m_seconds_of_week = _seconds_of_week;
}

/*!
 * @brief This function returns the value of member seconds_of_week
 * @return Value of member seconds_of_week
 */
double TypeSatnavTime::seconds_of_week() const
{
    return m_seconds_of_week;
}

/*!
 * @brief This function returns a reference to member seconds_of_week
 * @return Reference to member seconds_of_week
 */
double& TypeSatnavTime::seconds_of_week()
{
    return m_seconds_of_week;
}


/*!
 * @brief This function sets a value in member time_reference
 * @param _time_reference New value for member time_reference
 */
void TypeSatnavTime::time_reference(
        aspn23_dds::TypeSatnavTimeTimeReferenceValue _time_reference)
{
    m_time_reference = _time_reference;
}

/*!
 * @brief This function returns the value of member time_reference
 * @return Value of member time_reference
 */
aspn23_dds::TypeSatnavTimeTimeReferenceValue TypeSatnavTime::time_reference() const
{
    return m_time_reference;
}

/*!
 * @brief This function returns a reference to member time_reference
 * @return Reference to member time_reference
 */
aspn23_dds::TypeSatnavTimeTimeReferenceValue& TypeSatnavTime::time_reference()
{
    return m_time_reference;
}




} // namespace aspn23_dds
// Include auxiliary functions like for serializing/deserializing.
#include "TypeSatnavTimeCdrAux.ipp"

