// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file TypeSatnavTime.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_ASPN23_DDS_TYPESATNAVTIME_H_
#define _FAST_DDS_GENERATED_ASPN23_DDS_TYPESATNAVTIME_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>

#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>



#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(TYPESATNAVTIME_SOURCE)
#define TYPESATNAVTIME_DllAPI __declspec( dllexport )
#else
#define TYPESATNAVTIME_DllAPI __declspec( dllimport )
#endif // TYPESATNAVTIME_SOURCE
#else
#define TYPESATNAVTIME_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define TYPESATNAVTIME_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima



namespace aspn23_dds {

/*!
 * @brief This class represents the enumeration TypeSatnavTimeTimeReferenceValue defined by the user in the IDL file.
 * @ingroup TypeSatnavTime
 */
enum TypeSatnavTimeTimeReferenceValue : uint32_t
{
    ASPN23_TYPE_SATNAV_TIME_TIME_REFERENCE_TIME_GPS,
    ASPN23_TYPE_SATNAV_TIME_TIME_REFERENCE_TIME_GALILEO,
    ASPN23_TYPE_SATNAV_TIME_TIME_REFERENCE_TIME_BEIDOU,
    ASPN23_TYPE_SATNAV_TIME_TIME_REFERENCE_TIME_GLONASS
};


/*!
 * @brief This class represents the structure TypeSatnavTime defined by the user in the IDL file.
 * @ingroup TypeSatnavTime
 */
class TypeSatnavTime
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport TypeSatnavTime();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~TypeSatnavTime();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object aspn23_dds::TypeSatnavTime that will be copied.
     */
    eProsima_user_DllExport TypeSatnavTime(
            const TypeSatnavTime& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object aspn23_dds::TypeSatnavTime that will be copied.
     */
    eProsima_user_DllExport TypeSatnavTime(
            TypeSatnavTime&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object aspn23_dds::TypeSatnavTime that will be copied.
     */
    eProsima_user_DllExport TypeSatnavTime& operator =(
            const TypeSatnavTime& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object aspn23_dds::TypeSatnavTime that will be copied.
     */
    eProsima_user_DllExport TypeSatnavTime& operator =(
            TypeSatnavTime&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x aspn23_dds::TypeSatnavTime object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const TypeSatnavTime& x) const;

    /*!
     * @brief Comparison operator.
     * @param x aspn23_dds::TypeSatnavTime object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const TypeSatnavTime& x) const;

    /*!
     * @brief This function sets a value in member week_number
     * @param _week_number New value for member week_number
     */
    eProsima_user_DllExport void week_number(
            uint16_t _week_number);

    /*!
     * @brief This function returns the value of member week_number
     * @return Value of member week_number
     */
    eProsima_user_DllExport uint16_t week_number() const;

    /*!
     * @brief This function returns a reference to member week_number
     * @return Reference to member week_number
     */
    eProsima_user_DllExport uint16_t& week_number();


    /*!
     * @brief This function sets a value in member seconds_of_week
     * @param _seconds_of_week New value for member seconds_of_week
     */
    eProsima_user_DllExport void seconds_of_week(
            double _seconds_of_week);

    /*!
     * @brief This function returns the value of member seconds_of_week
     * @return Value of member seconds_of_week
     */
    eProsima_user_DllExport double seconds_of_week() const;

    /*!
     * @brief This function returns a reference to member seconds_of_week
     * @return Reference to member seconds_of_week
     */
    eProsima_user_DllExport double& seconds_of_week();


    /*!
     * @brief This function sets a value in member time_reference
     * @param _time_reference New value for member time_reference
     */
    eProsima_user_DllExport void time_reference(
            aspn23_dds::TypeSatnavTimeTimeReferenceValue _time_reference);

    /*!
     * @brief This function returns the value of member time_reference
     * @return Value of member time_reference
     */
    eProsima_user_DllExport aspn23_dds::TypeSatnavTimeTimeReferenceValue time_reference() const;

    /*!
     * @brief This function returns a reference to member time_reference
     * @return Reference to member time_reference
     */
    eProsima_user_DllExport aspn23_dds::TypeSatnavTimeTimeReferenceValue& time_reference();

private:

    uint16_t m_week_number{0};
    double m_seconds_of_week{0.0};
    aspn23_dds::TypeSatnavTimeTimeReferenceValue m_time_reference{aspn23_dds::ASPN23_TYPE_SATNAV_TIME_TIME_REFERENCE_TIME_GPS};

};

} // namespace aspn23_dds

#endif // _FAST_DDS_GENERATED_ASPN23_DDS_TYPESATNAVTIME_H_



