// generated from rosidl_generator_cpp/resource/idl.hpp.em
// generated code does not contain a copyright notice

#ifndef ASPN23_ROS_INTERFACES__MSG__MEASUREMENT_ACCUMULATED_DISTANCE_TRAVELED_HPP_
#define ASPN23_ROS_INTERFACES__MSG__MEASUREMENT_ACCUMULATED_DISTANCE_TRAVELED_HPP_

#include "aspn23_ros_interfaces/msg/detail/measurement_accumulated_distance_traveled__builder.hpp"
#include "aspn23_ros_interfaces/msg/detail/measurement_accumulated_distance_traveled__struct.hpp"
#include "aspn23_ros_interfaces/msg/detail/measurement_accumulated_distance_traveled__traits.hpp"
#include "aspn23_ros_interfaces/msg/detail/measurement_accumulated_distance_traveled__type_support.hpp"

#endif // ASPN23_ROS_INTERFACES__MSG__MEASUREMENT_ACCUMULATED_DISTANCE_TRAVELED_HPP_
