// generated from rosidl_generator_cpp/resource/idl.hpp.em
// generated code does not contain a copyright notice

#ifndef ASPN23_ROS_INTERFACES__MSG__MEASUREMENT_MAGNETIC_FIELD_MAGNITUDE_HPP_
#define ASPN23_ROS_INTERFACES__MSG__MEASUREMENT_MAGNETIC_FIELD_MAGNITUDE_HPP_

#include "aspn23_ros_interfaces/msg/detail/measurement_magnetic_field_magnitude__builder.hpp"
#include "aspn23_ros_interfaces/msg/detail/measurement_magnetic_field_magnitude__struct.hpp"
#include "aspn23_ros_interfaces/msg/detail/measurement_magnetic_field_magnitude__traits.hpp"
#include "aspn23_ros_interfaces/msg/detail/measurement_magnetic_field_magnitude__type_support.hpp"

#endif // ASPN23_ROS_INTERFACES__MSG__MEASUREMENT_MAGNETIC_FIELD_MAGNITUDE_HPP_
