// generated from rosidl_generator_cpp/resource/idl.hpp.em
// generated code does not contain a copyright notice

#ifndef ASPN23_ROS_INTERFACES__MSG__MEASUREMENT_POSITION_VELOCITY_ATTITUDE_HPP_
#define ASPN23_ROS_INTERFACES__MSG__MEASUREMENT_POSITION_VELOCITY_ATTITUDE_HPP_

#include "aspn23_ros_interfaces/msg/detail/measurement_position_velocity_attitude__builder.hpp"
#include "aspn23_ros_interfaces/msg/detail/measurement_position_velocity_attitude__struct.hpp"
#include "aspn23_ros_interfaces/msg/detail/measurement_position_velocity_attitude__traits.hpp"
#include "aspn23_ros_interfaces/msg/detail/measurement_position_velocity_attitude__type_support.hpp"

#endif // ASPN23_ROS_INTERFACES__MSG__MEASUREMENT_POSITION_VELOCITY_ATTITUDE_HPP_
