// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen 1.5.2


/**
 * This code is generated via firehose.
 * DO NOT hand edit code.  Make any changes required using the firehose repo instead
 */
#ifndef _aspn23_lcm_type_integrity_h
#define _aspn23_lcm_type_integrity_h

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifdef __cplusplus
extern "C" {
#endif


/**
 * Integrity provides a numerical measure of the trustworthiness of the associated measurement. The
 * integrity_method enum specifies the integrity method and the appropriate interpretation of the
 * integrity_value.
 */
typedef struct _aspn23_lcm_type_integrity aspn23_lcm_type_integrity;
struct _aspn23_lcm_type_integrity
{

    /**
     * Non ASPN. Do not use. Extra field encoding the struct name to disambiguate LCM type fingerprint hashes.
     */
    int8_t     icd_type_integrity;

    /**
     * Enumerated field which describes the meaning of the integrity value. Integrity methods may use
     * multiple enum entries if there is a need to pass multiple integrity values. For example, an
     * integrity method with 3 parameters may use 3 enum entries (e.g., MY_METHOD_VALUE1, MY_METHOD_VALUE2,
     * MY_METHOD_VALUE3). When integrity is reported in a message, a vector of integrity types is passed.
     * In the MY_METHOD example, num_integrity = 3 just for the MY_METHOD integrity. If additional
     * integrity methods are also reported, then num_integrity would be greater than 3 to include those
     * additional methods.
     */
    int16_t    integrity_method;

    /**
     * Description: Measurement integrity value to be interpreted based on the definition in the
     * integrity_type enum.
     * Units: none
     */
    double     integrity_value;
};

/**
 * Create a deep copy of a aspn23_lcm_type_integrity.
 * When no longer needed, destroy it with aspn23_lcm_type_integrity_destroy()
 */
aspn23_lcm_type_integrity* aspn23_lcm_type_integrity_copy(const aspn23_lcm_type_integrity* to_copy);

/**
 * Destroy an instance of aspn23_lcm_type_integrity created by aspn23_lcm_type_integrity_copy()
 */
void aspn23_lcm_type_integrity_destroy(aspn23_lcm_type_integrity* to_destroy);

/**
 * Identifies a single subscription.  This is an opaque data type.
 */
typedef struct _aspn23_lcm_type_integrity_subscription_t aspn23_lcm_type_integrity_subscription_t;

/**
 * Prototype for a callback function invoked when a message of type
 * aspn23_lcm_type_integrity is received.
 */
typedef void(*aspn23_lcm_type_integrity_handler_t)(
    const lcm_recv_buf_t *rbuf, const char *channel,
    const aspn23_lcm_type_integrity *msg, void *userdata);

/**
 * Publish a message of type aspn23_lcm_type_integrity using LCM.
 *
 * @param lcm The LCM instance to publish with.
 * @param channel The channel to publish on.
 * @param msg The message to publish.
 * @return 0 on success, <0 on error.  Success means LCM has transferred
 * responsibility of the message data to the OS.
 */
int aspn23_lcm_type_integrity_publish(lcm_t *lcm, const char *channel, const aspn23_lcm_type_integrity *msg);

/**
 * Subscribe to messages of type aspn23_lcm_type_integrity using LCM.
 *
 * @param lcm The LCM instance to subscribe with.
 * @param channel The channel to subscribe to.
 * @param handler The callback function invoked by LCM when a message is
 *     received. This function is invoked by LCM during calls to lcm_handle()
 *     and lcm_handle_timeout().
 * @param userdata An opaque pointer passed to @p handler when it is invoked.
 * @return 0 on success, <0 if an error occured
 */
aspn23_lcm_type_integrity_subscription_t* aspn23_lcm_type_integrity_subscribe(
    lcm_t *lcm, const char *channel, aspn23_lcm_type_integrity_handler_t handler, void *userdata);

/**
 * Removes and destroys a subscription created by aspn23_lcm_type_integrity_subscribe()
 */
int aspn23_lcm_type_integrity_unsubscribe(lcm_t *lcm, aspn23_lcm_type_integrity_subscription_t* hid);

/**
 * Sets the queue capacity for a subscription.
 * Some LCM providers (e.g., the default multicast provider) are implemented
 * using a background receive thread that constantly revceives messages from
 * the network.  As these messages are received, they are buffered on
 * per-subscription queues until dispatched by lcm_handle().  This function
 * how many messages are queued before dropping messages.
 *
 * @param subs the subscription to modify.
 * @param num_messages The maximum number of messages to queue
 *  on the subscription.
 * @return 0 on success, <0 if an error occured
 */
int aspn23_lcm_type_integrity_subscription_set_queue_capacity(
    aspn23_lcm_type_integrity_subscription_t* subs, int num_messages);

/**
 * Encode a message of type aspn23_lcm_type_integrity into binary form.
 *
 * @param buf The output buffer.
 * @param offset Encoding starts at this byte offset into @p buf.
 * @param maxlen Maximum number of bytes to write.  This should generally
 *               be equal to aspn23_lcm_type_integrity_encoded_size().
 * @param msg The message to encode.
 * @return The number of bytes encoded, or <0 if an error occured.
 */
int aspn23_lcm_type_integrity_encode(void *buf, int offset, int maxlen, const aspn23_lcm_type_integrity *p);

/**
 * Decode a message of type aspn23_lcm_type_integrity from binary form.
 * When decoding messages containing strings or variable-length arrays, this
 * function may allocate memory.  When finished with the decoded message,
 * release allocated resources with aspn23_lcm_type_integrity_decode_cleanup().
 *
 * @param buf The buffer containing the encoded message
 * @param offset The byte offset into @p buf where the encoded message starts.
 * @param maxlen The maximum number of bytes to read while decoding.
 * @param msg Output parameter where the decoded message is stored
 * @return The number of bytes decoded, or <0 if an error occured.
 */
int aspn23_lcm_type_integrity_decode(const void *buf, int offset, int maxlen, aspn23_lcm_type_integrity *msg);

/**
 * Release resources allocated by aspn23_lcm_type_integrity_decode()
 * @return 0
 */
int aspn23_lcm_type_integrity_decode_cleanup(aspn23_lcm_type_integrity *p);

/**
 * Check how many bytes are required to encode a message of type aspn23_lcm_type_integrity
 */
int aspn23_lcm_type_integrity_encoded_size(const aspn23_lcm_type_integrity *p);

// LCM support functions. Users should not call these
int64_t __aspn23_lcm_type_integrity_get_hash(void);
uint64_t __aspn23_lcm_type_integrity_hash_recursive(const __lcm_hash_ptr *p);
int __aspn23_lcm_type_integrity_encode_array(
    void *buf, int offset, int maxlen, const aspn23_lcm_type_integrity *p, int elements);
int __aspn23_lcm_type_integrity_decode_array(
    const void *buf, int offset, int maxlen, aspn23_lcm_type_integrity *p, int elements);
int __aspn23_lcm_type_integrity_decode_array_cleanup(aspn23_lcm_type_integrity *p, int elements);
int __aspn23_lcm_type_integrity_encoded_array_size(const aspn23_lcm_type_integrity *p, int elements);
int __aspn23_lcm_type_integrity_clone_array(const aspn23_lcm_type_integrity *p, aspn23_lcm_type_integrity *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
