// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen 1.5.2


/**
 * This code is generated via firehose.
 * DO NOT hand edit code.  Make any changes required using the firehose repo instead
 */
#ifndef _aspn23_lcm_measurement_satnav_h
#define _aspn23_lcm_measurement_satnav_h

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifdef __cplusplus
extern "C" {
#endif

#include "aspn23_lcm_type_header.h"
#include "aspn23_lcm_type_timestamp.h"
#include "aspn23_lcm_type_satnav_time.h"
#include "aspn23_lcm_type_satnav_obs.h"
#include "aspn23_lcm_type_integrity.h"
/// Raw measurements from a satnav receiver.
typedef struct _aspn23_lcm_measurement_satnav aspn23_lcm_measurement_satnav;
struct _aspn23_lcm_measurement_satnav
{

    /**
     * Non ASPN. Do not use. Extra field encoding the struct name to disambiguate LCM type fingerprint hashes.
     */
    int8_t     icd_measurement_satnav;

    /**
     * Description: Standard ASPN measurement header.
     * Units: none
     */
    aspn23_lcm_type_header header;

    /**
     * Description: Time at which the measurement is considered to be valid.
     * Units: none
     */
    aspn23_lcm_type_timestamp time_of_validity;

    /**
     * Description: Receiver clock time. In a multi-GNSS receiver (GPS/GLONASS/Galileo/QZSS/BeiDou) all
     * pseudorange observations must refer to one receiver clock only. The receiver clock time of the
     * measurement is the receiver clock time of the received signals. It is identical for the phase and
     * range measurements and is identical for all satellites observed in a given epoch.
     * Units: none
     */
    aspn23_lcm_type_satnav_time receiver_clock_time;

    /**
     * Description: Number of different signal types tracked in the current epoch. Examples of signal
     * types include GPS L1 C/A code, Galileo E1B.
     * Units: none
     */
    int32_t    num_signal_types;

    /**
     * Description: Total number of signals tracked across all PRNs and signal types.
     * Units: none
     */
    int32_t    num_signals_tracked;

    /**
     * Description: Array of satnav obs data for all of the signals/PRNs being tracked in this epoch.
     * Units: none
     * LCM Type: aspn23_lcm.type_satnav_obs[num_signals_tracked]
     */
    aspn23_lcm_type_satnav_obs *obs;

    /**
     * Description: Number of integrity values.
     * Units: none
     */
    int16_t    num_integrity;

    /**
     * Description: Measurement integrity at the sensor level. Integrity is also available for each
     * observable, which is found in the observable type definition. Includes the integrity method used and
     * an integrity value (which is to be interpreted based upon the integrity method). The intent of
     * allowing num_integrity > 1 is to report multiple integrity values based on multiple integrity
     * methods.
     * Units: none
     * LCM Type: aspn23_lcm.type_integrity[num_integrity]
     */
    aspn23_lcm_type_integrity *integrity;
};

/**
 * Create a deep copy of a aspn23_lcm_measurement_satnav.
 * When no longer needed, destroy it with aspn23_lcm_measurement_satnav_destroy()
 */
aspn23_lcm_measurement_satnav* aspn23_lcm_measurement_satnav_copy(const aspn23_lcm_measurement_satnav* to_copy);

/**
 * Destroy an instance of aspn23_lcm_measurement_satnav created by aspn23_lcm_measurement_satnav_copy()
 */
void aspn23_lcm_measurement_satnav_destroy(aspn23_lcm_measurement_satnav* to_destroy);

/**
 * Identifies a single subscription.  This is an opaque data type.
 */
typedef struct _aspn23_lcm_measurement_satnav_subscription_t aspn23_lcm_measurement_satnav_subscription_t;

/**
 * Prototype for a callback function invoked when a message of type
 * aspn23_lcm_measurement_satnav is received.
 */
typedef void(*aspn23_lcm_measurement_satnav_handler_t)(
    const lcm_recv_buf_t *rbuf, const char *channel,
    const aspn23_lcm_measurement_satnav *msg, void *userdata);

/**
 * Publish a message of type aspn23_lcm_measurement_satnav using LCM.
 *
 * @param lcm The LCM instance to publish with.
 * @param channel The channel to publish on.
 * @param msg The message to publish.
 * @return 0 on success, <0 on error.  Success means LCM has transferred
 * responsibility of the message data to the OS.
 */
int aspn23_lcm_measurement_satnav_publish(lcm_t *lcm, const char *channel, const aspn23_lcm_measurement_satnav *msg);

/**
 * Subscribe to messages of type aspn23_lcm_measurement_satnav using LCM.
 *
 * @param lcm The LCM instance to subscribe with.
 * @param channel The channel to subscribe to.
 * @param handler The callback function invoked by LCM when a message is
 *     received. This function is invoked by LCM during calls to lcm_handle()
 *     and lcm_handle_timeout().
 * @param userdata An opaque pointer passed to @p handler when it is invoked.
 * @return 0 on success, <0 if an error occured
 */
aspn23_lcm_measurement_satnav_subscription_t* aspn23_lcm_measurement_satnav_subscribe(
    lcm_t *lcm, const char *channel, aspn23_lcm_measurement_satnav_handler_t handler, void *userdata);

/**
 * Removes and destroys a subscription created by aspn23_lcm_measurement_satnav_subscribe()
 */
int aspn23_lcm_measurement_satnav_unsubscribe(lcm_t *lcm, aspn23_lcm_measurement_satnav_subscription_t* hid);

/**
 * Sets the queue capacity for a subscription.
 * Some LCM providers (e.g., the default multicast provider) are implemented
 * using a background receive thread that constantly revceives messages from
 * the network.  As these messages are received, they are buffered on
 * per-subscription queues until dispatched by lcm_handle().  This function
 * how many messages are queued before dropping messages.
 *
 * @param subs the subscription to modify.
 * @param num_messages The maximum number of messages to queue
 *  on the subscription.
 * @return 0 on success, <0 if an error occured
 */
int aspn23_lcm_measurement_satnav_subscription_set_queue_capacity(
    aspn23_lcm_measurement_satnav_subscription_t* subs, int num_messages);

/**
 * Encode a message of type aspn23_lcm_measurement_satnav into binary form.
 *
 * @param buf The output buffer.
 * @param offset Encoding starts at this byte offset into @p buf.
 * @param maxlen Maximum number of bytes to write.  This should generally
 *               be equal to aspn23_lcm_measurement_satnav_encoded_size().
 * @param msg The message to encode.
 * @return The number of bytes encoded, or <0 if an error occured.
 */
int aspn23_lcm_measurement_satnav_encode(void *buf, int offset, int maxlen, const aspn23_lcm_measurement_satnav *p);

/**
 * Decode a message of type aspn23_lcm_measurement_satnav from binary form.
 * When decoding messages containing strings or variable-length arrays, this
 * function may allocate memory.  When finished with the decoded message,
 * release allocated resources with aspn23_lcm_measurement_satnav_decode_cleanup().
 *
 * @param buf The buffer containing the encoded message
 * @param offset The byte offset into @p buf where the encoded message starts.
 * @param maxlen The maximum number of bytes to read while decoding.
 * @param msg Output parameter where the decoded message is stored
 * @return The number of bytes decoded, or <0 if an error occured.
 */
int aspn23_lcm_measurement_satnav_decode(const void *buf, int offset, int maxlen, aspn23_lcm_measurement_satnav *msg);

/**
 * Release resources allocated by aspn23_lcm_measurement_satnav_decode()
 * @return 0
 */
int aspn23_lcm_measurement_satnav_decode_cleanup(aspn23_lcm_measurement_satnav *p);

/**
 * Check how many bytes are required to encode a message of type aspn23_lcm_measurement_satnav
 */
int aspn23_lcm_measurement_satnav_encoded_size(const aspn23_lcm_measurement_satnav *p);

// LCM support functions. Users should not call these
int64_t __aspn23_lcm_measurement_satnav_get_hash(void);
uint64_t __aspn23_lcm_measurement_satnav_hash_recursive(const __lcm_hash_ptr *p);
int __aspn23_lcm_measurement_satnav_encode_array(
    void *buf, int offset, int maxlen, const aspn23_lcm_measurement_satnav *p, int elements);
int __aspn23_lcm_measurement_satnav_decode_array(
    const void *buf, int offset, int maxlen, aspn23_lcm_measurement_satnav *p, int elements);
int __aspn23_lcm_measurement_satnav_decode_array_cleanup(aspn23_lcm_measurement_satnav *p, int elements);
int __aspn23_lcm_measurement_satnav_encoded_array_size(const aspn23_lcm_measurement_satnav *p, int elements);
int __aspn23_lcm_measurement_satnav_clone_array(const aspn23_lcm_measurement_satnav *p, aspn23_lcm_measurement_satnav *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
