// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen 1.5.2


/**
 * This code is generated via firehose.
 * DO NOT hand edit code.  Make any changes required using the firehose repo instead
 */
#ifndef _aspn23_lcm_type_satnav_obs_h
#define _aspn23_lcm_type_satnav_obs_h

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifdef __cplusplus
extern "C" {
#endif

#include "aspn23_lcm_type_satnav_satellite_system.h"
#include "aspn23_lcm_type_satnav_signal_descriptor.h"
#include "aspn23_lcm_type_integrity.h"
/// Instantaneous Doppler at measurement time. Units = Hz Cov. Units = Hz^2
#define ASPN23_LCM_TYPE_SATNAV_OBS_PSEUDORANGE_RATE_TYPE_PSR_RATE_DOPPLER 0

/**
 * Change in pseudorange (integrated Doppler) over a specified time interval. The interval is
 * provided in metadata_satnav_obs. Units = m Cov. Units = m^2
 */
#define ASPN23_LCM_TYPE_SATNAV_OBS_PSEUDORANGE_RATE_TYPE_PSR_RATE_DELTA_RANGE 1
/// unknown source
#define ASPN23_LCM_TYPE_SATNAV_OBS_IONO_CORRECTION_SOURCE_UNKNOWN 0
/// modeled using the ionospheric models in IS-GPS-200, IS-GPS-700, or IS-GPS-800
#define ASPN23_LCM_TYPE_SATNAV_OBS_IONO_CORRECTION_SOURCE_MODELED 1
/// measured using dual frequencies
#define ASPN23_LCM_TYPE_SATNAV_OBS_IONO_CORRECTION_SOURCE_MEASURED 2


/**
 * Defines measurements that come from a satnav receiver tracking a single signal from a single
 * satellite.
 */
typedef struct _aspn23_lcm_type_satnav_obs aspn23_lcm_type_satnav_obs;
struct _aspn23_lcm_type_satnav_obs
{

    /**
     * Non ASPN. Do not use. Extra field encoding the struct name to disambiguate LCM type fingerprint hashes.
     */
    int8_t     icd_type_satnav_obs;

    /**
     * Description: Enumerated field which describes the Satellite System that generated the
     * observations.
     * Units: none
     */
    aspn23_lcm_type_satnav_satellite_system satellite_system;

    /**
     * Description: Satellite signal descriptor as defined in RINEX 3.05
     * Units: none
     */
    aspn23_lcm_type_satnav_signal_descriptor signal_descriptor;

    /**
     * Description: PRN code which identifies satellite (or slot number, in the case of GLONASS) for
     * the observables.
     * Units: none
     */
    int16_t    prn;

    /**
     * Description: Center frequency of signal. For GLONASS, this should be the center frequency of the
     * frequency-shifted signal with the k value taken into account.
     * Units: Hz
     */
    double     frequency;

    /**
     * Description: Pseudorange measurement
     * Units: m
     */
    double     pseudorange;

    /**
     * Description: Variance of pseudorange measurement noise/multipath. This value must be provided if
     * the pseudorange measurement is provided. Note: This is not intended to represent clock, atmospheric,
     * or satellite position errors.
     * Units: m^2
     */
    float      pseudorange_variance;

    /**
     * Indicates the type of measurement contained in pseudorange_rate.
     */
    int8_t     pseudorange_rate_type;

    /**
     * Description: Measurement of the change in the pseudorange. See pseudorange_rate_type for
     * details.
     * Units: Hz or m
     */
    double     pseudorange_rate;

    /**
     * Description: Variance of pseudorange_rate noise. This value must be provided if the
     * pseudorange_rate measurement is provided.
     * Units: Hz^2 or m^2
     */
    float      pseudorange_rate_variance;

    /**
     * Description: Carrier-phase (integrated Doppler) measurement. This measurement has an N cycle
     * ambiguity (where N is unknown and arbitrary integer).
     * Units: cycles (1 cycle = wavelength of carrier frequency)
     */
    double     carrier_phase;

    /**
     * Description: Variance of carrier-phase noise/multipath. This value must be provided if the
     * carrier-phase measurement is provided. Note: This is not intended to represent clock, atmospheric,
     * or satellite position errors or the integer N ambiguity.
     * Units: cycles^2
     */
    float      carrier_phase_variance;

    /**
     * Description: Carrier to noise density ratio. C/N0 = 10[log10(S/N0)]
     * Units: db-Hz
     */
    float      c_n0;

    /**
     * Description: Number of observations with continuous tracking (no cycle slips). Value of -1 means
     * that there is no loss of lock information available. First lock_count after cycle slip has occurred
     * will have a value of 0. The lock_count only applies to the carrier-phase measurement.
     * Units: none
     */
    int32_t    lock_count;

    /**
     * Enumerated field which describes the source of the ionospheric delay correction.
     */
    int8_t     iono_correction_source;

    /**
     * Description: Identifies if the ionospheric correction has been applied to the measurement. 1 =
     * Applied.
     * Units: none
     */
    int8_t     iono_correction_applied;

    /**
     * Description: Identifies if the tropospheric correction has been applied to the measurement. 1 =
     * Applied.
     * Units: none
     */
    int8_t     tropo_correction_applied;

    /**
     * Description: Represents biases within the transmitting signal that are identified in the
     * downlink data, Group Delay for LNAV, and Interchannel Signal Correction (ISC) message for MNAV. This
     * term indicates whether the correction is known, being applied to Pseudorange Correction, and its
     * associated estimated error applied to the ERE. When invalid the correction and estimated error are
     * not known and therefore not applied. 1 = Valid.
     * Units: none
     */
    int8_t     signal_bias_correction_applied;

    /**
     * Description: Number of integrity values.
     * Units: none
     */
    int16_t    num_integrity;

    /**
     * Description: Measurement integrity. Includes the integrity method used and an integrity value
     * (which is to be interpreted based upon the integrity method). The intent of allowing num_integrity >
     * 1 is to report multiple integrity values based on multiple integrity methods.
     * Units: none
     * LCM Type: aspn23_lcm.type_integrity[num_integrity]
     */
    aspn23_lcm_type_integrity *integrity;
};

/**
 * Create a deep copy of a aspn23_lcm_type_satnav_obs.
 * When no longer needed, destroy it with aspn23_lcm_type_satnav_obs_destroy()
 */
aspn23_lcm_type_satnav_obs* aspn23_lcm_type_satnav_obs_copy(const aspn23_lcm_type_satnav_obs* to_copy);

/**
 * Destroy an instance of aspn23_lcm_type_satnav_obs created by aspn23_lcm_type_satnav_obs_copy()
 */
void aspn23_lcm_type_satnav_obs_destroy(aspn23_lcm_type_satnav_obs* to_destroy);

/**
 * Identifies a single subscription.  This is an opaque data type.
 */
typedef struct _aspn23_lcm_type_satnav_obs_subscription_t aspn23_lcm_type_satnav_obs_subscription_t;

/**
 * Prototype for a callback function invoked when a message of type
 * aspn23_lcm_type_satnav_obs is received.
 */
typedef void(*aspn23_lcm_type_satnav_obs_handler_t)(
    const lcm_recv_buf_t *rbuf, const char *channel,
    const aspn23_lcm_type_satnav_obs *msg, void *userdata);

/**
 * Publish a message of type aspn23_lcm_type_satnav_obs using LCM.
 *
 * @param lcm The LCM instance to publish with.
 * @param channel The channel to publish on.
 * @param msg The message to publish.
 * @return 0 on success, <0 on error.  Success means LCM has transferred
 * responsibility of the message data to the OS.
 */
int aspn23_lcm_type_satnav_obs_publish(lcm_t *lcm, const char *channel, const aspn23_lcm_type_satnav_obs *msg);

/**
 * Subscribe to messages of type aspn23_lcm_type_satnav_obs using LCM.
 *
 * @param lcm The LCM instance to subscribe with.
 * @param channel The channel to subscribe to.
 * @param handler The callback function invoked by LCM when a message is
 *     received. This function is invoked by LCM during calls to lcm_handle()
 *     and lcm_handle_timeout().
 * @param userdata An opaque pointer passed to @p handler when it is invoked.
 * @return 0 on success, <0 if an error occured
 */
aspn23_lcm_type_satnav_obs_subscription_t* aspn23_lcm_type_satnav_obs_subscribe(
    lcm_t *lcm, const char *channel, aspn23_lcm_type_satnav_obs_handler_t handler, void *userdata);

/**
 * Removes and destroys a subscription created by aspn23_lcm_type_satnav_obs_subscribe()
 */
int aspn23_lcm_type_satnav_obs_unsubscribe(lcm_t *lcm, aspn23_lcm_type_satnav_obs_subscription_t* hid);

/**
 * Sets the queue capacity for a subscription.
 * Some LCM providers (e.g., the default multicast provider) are implemented
 * using a background receive thread that constantly revceives messages from
 * the network.  As these messages are received, they are buffered on
 * per-subscription queues until dispatched by lcm_handle().  This function
 * how many messages are queued before dropping messages.
 *
 * @param subs the subscription to modify.
 * @param num_messages The maximum number of messages to queue
 *  on the subscription.
 * @return 0 on success, <0 if an error occured
 */
int aspn23_lcm_type_satnav_obs_subscription_set_queue_capacity(
    aspn23_lcm_type_satnav_obs_subscription_t* subs, int num_messages);

/**
 * Encode a message of type aspn23_lcm_type_satnav_obs into binary form.
 *
 * @param buf The output buffer.
 * @param offset Encoding starts at this byte offset into @p buf.
 * @param maxlen Maximum number of bytes to write.  This should generally
 *               be equal to aspn23_lcm_type_satnav_obs_encoded_size().
 * @param msg The message to encode.
 * @return The number of bytes encoded, or <0 if an error occured.
 */
int aspn23_lcm_type_satnav_obs_encode(void *buf, int offset, int maxlen, const aspn23_lcm_type_satnav_obs *p);

/**
 * Decode a message of type aspn23_lcm_type_satnav_obs from binary form.
 * When decoding messages containing strings or variable-length arrays, this
 * function may allocate memory.  When finished with the decoded message,
 * release allocated resources with aspn23_lcm_type_satnav_obs_decode_cleanup().
 *
 * @param buf The buffer containing the encoded message
 * @param offset The byte offset into @p buf where the encoded message starts.
 * @param maxlen The maximum number of bytes to read while decoding.
 * @param msg Output parameter where the decoded message is stored
 * @return The number of bytes decoded, or <0 if an error occured.
 */
int aspn23_lcm_type_satnav_obs_decode(const void *buf, int offset, int maxlen, aspn23_lcm_type_satnav_obs *msg);

/**
 * Release resources allocated by aspn23_lcm_type_satnav_obs_decode()
 * @return 0
 */
int aspn23_lcm_type_satnav_obs_decode_cleanup(aspn23_lcm_type_satnav_obs *p);

/**
 * Check how many bytes are required to encode a message of type aspn23_lcm_type_satnav_obs
 */
int aspn23_lcm_type_satnav_obs_encoded_size(const aspn23_lcm_type_satnav_obs *p);

// LCM support functions. Users should not call these
int64_t __aspn23_lcm_type_satnav_obs_get_hash(void);
uint64_t __aspn23_lcm_type_satnav_obs_hash_recursive(const __lcm_hash_ptr *p);
int __aspn23_lcm_type_satnav_obs_encode_array(
    void *buf, int offset, int maxlen, const aspn23_lcm_type_satnav_obs *p, int elements);
int __aspn23_lcm_type_satnav_obs_decode_array(
    const void *buf, int offset, int maxlen, aspn23_lcm_type_satnav_obs *p, int elements);
int __aspn23_lcm_type_satnav_obs_decode_array_cleanup(aspn23_lcm_type_satnav_obs *p, int elements);
int __aspn23_lcm_type_satnav_obs_encoded_array_size(const aspn23_lcm_type_satnav_obs *p, int elements);
int __aspn23_lcm_type_satnav_obs_clone_array(const aspn23_lcm_type_satnav_obs *p, aspn23_lcm_type_satnav_obs *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
