// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen 1.5.2


/**
 * This code is generated via firehose.
 * DO NOT hand edit code.  Make any changes required using the firehose repo instead
 */
#ifndef _aspn23_lcm_measurement_direction_2d_to_points_h
#define _aspn23_lcm_measurement_direction_2d_to_points_h

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifdef __cplusplus
extern "C" {
#endif

#include "aspn23_lcm_type_header.h"
#include "aspn23_lcm_type_timestamp.h"
#include "aspn23_lcm_type_direction_2d_to_point.h"
/// 2D direction to points.
typedef struct _aspn23_lcm_measurement_direction_2d_to_points aspn23_lcm_measurement_direction_2d_to_points;
struct _aspn23_lcm_measurement_direction_2d_to_points
{

    /**
     * Non ASPN. Do not use. Extra field encoding the struct name to disambiguate LCM type fingerprint hashes.
     */
    int8_t     icd_measurement_direction_2d_to_points;

    /**
     * Description: Standard ASPN measurement header.
     * Units: none
     */
    aspn23_lcm_type_header header;

    /**
     * Description: Time at which the measurement is considered to be valid.
     * Units: none
     */
    aspn23_lcm_type_timestamp time_of_validity;

    /**
     * Description: Total number of observations.
     * Units: none
     */
    int32_t    num_obs;

    /**
     * Description: Array of observations.
     * Units: none
     * LCM Type: aspn23_lcm.type_direction_2d_to_point[num_obs]
     */
    aspn23_lcm_type_direction_2d_to_point *obs;
};

/**
 * Create a deep copy of a aspn23_lcm_measurement_direction_2d_to_points.
 * When no longer needed, destroy it with aspn23_lcm_measurement_direction_2d_to_points_destroy()
 */
aspn23_lcm_measurement_direction_2d_to_points* aspn23_lcm_measurement_direction_2d_to_points_copy(const aspn23_lcm_measurement_direction_2d_to_points* to_copy);

/**
 * Destroy an instance of aspn23_lcm_measurement_direction_2d_to_points created by aspn23_lcm_measurement_direction_2d_to_points_copy()
 */
void aspn23_lcm_measurement_direction_2d_to_points_destroy(aspn23_lcm_measurement_direction_2d_to_points* to_destroy);

/**
 * Identifies a single subscription.  This is an opaque data type.
 */
typedef struct _aspn23_lcm_measurement_direction_2d_to_points_subscription_t aspn23_lcm_measurement_direction_2d_to_points_subscription_t;

/**
 * Prototype for a callback function invoked when a message of type
 * aspn23_lcm_measurement_direction_2d_to_points is received.
 */
typedef void(*aspn23_lcm_measurement_direction_2d_to_points_handler_t)(
    const lcm_recv_buf_t *rbuf, const char *channel,
    const aspn23_lcm_measurement_direction_2d_to_points *msg, void *userdata);

/**
 * Publish a message of type aspn23_lcm_measurement_direction_2d_to_points using LCM.
 *
 * @param lcm The LCM instance to publish with.
 * @param channel The channel to publish on.
 * @param msg The message to publish.
 * @return 0 on success, <0 on error.  Success means LCM has transferred
 * responsibility of the message data to the OS.
 */
int aspn23_lcm_measurement_direction_2d_to_points_publish(lcm_t *lcm, const char *channel, const aspn23_lcm_measurement_direction_2d_to_points *msg);

/**
 * Subscribe to messages of type aspn23_lcm_measurement_direction_2d_to_points using LCM.
 *
 * @param lcm The LCM instance to subscribe with.
 * @param channel The channel to subscribe to.
 * @param handler The callback function invoked by LCM when a message is
 *     received. This function is invoked by LCM during calls to lcm_handle()
 *     and lcm_handle_timeout().
 * @param userdata An opaque pointer passed to @p handler when it is invoked.
 * @return 0 on success, <0 if an error occured
 */
aspn23_lcm_measurement_direction_2d_to_points_subscription_t* aspn23_lcm_measurement_direction_2d_to_points_subscribe(
    lcm_t *lcm, const char *channel, aspn23_lcm_measurement_direction_2d_to_points_handler_t handler, void *userdata);

/**
 * Removes and destroys a subscription created by aspn23_lcm_measurement_direction_2d_to_points_subscribe()
 */
int aspn23_lcm_measurement_direction_2d_to_points_unsubscribe(lcm_t *lcm, aspn23_lcm_measurement_direction_2d_to_points_subscription_t* hid);

/**
 * Sets the queue capacity for a subscription.
 * Some LCM providers (e.g., the default multicast provider) are implemented
 * using a background receive thread that constantly revceives messages from
 * the network.  As these messages are received, they are buffered on
 * per-subscription queues until dispatched by lcm_handle().  This function
 * how many messages are queued before dropping messages.
 *
 * @param subs the subscription to modify.
 * @param num_messages The maximum number of messages to queue
 *  on the subscription.
 * @return 0 on success, <0 if an error occured
 */
int aspn23_lcm_measurement_direction_2d_to_points_subscription_set_queue_capacity(
    aspn23_lcm_measurement_direction_2d_to_points_subscription_t* subs, int num_messages);

/**
 * Encode a message of type aspn23_lcm_measurement_direction_2d_to_points into binary form.
 *
 * @param buf The output buffer.
 * @param offset Encoding starts at this byte offset into @p buf.
 * @param maxlen Maximum number of bytes to write.  This should generally
 *               be equal to aspn23_lcm_measurement_direction_2d_to_points_encoded_size().
 * @param msg The message to encode.
 * @return The number of bytes encoded, or <0 if an error occured.
 */
int aspn23_lcm_measurement_direction_2d_to_points_encode(void *buf, int offset, int maxlen, const aspn23_lcm_measurement_direction_2d_to_points *p);

/**
 * Decode a message of type aspn23_lcm_measurement_direction_2d_to_points from binary form.
 * When decoding messages containing strings or variable-length arrays, this
 * function may allocate memory.  When finished with the decoded message,
 * release allocated resources with aspn23_lcm_measurement_direction_2d_to_points_decode_cleanup().
 *
 * @param buf The buffer containing the encoded message
 * @param offset The byte offset into @p buf where the encoded message starts.
 * @param maxlen The maximum number of bytes to read while decoding.
 * @param msg Output parameter where the decoded message is stored
 * @return The number of bytes decoded, or <0 if an error occured.
 */
int aspn23_lcm_measurement_direction_2d_to_points_decode(const void *buf, int offset, int maxlen, aspn23_lcm_measurement_direction_2d_to_points *msg);

/**
 * Release resources allocated by aspn23_lcm_measurement_direction_2d_to_points_decode()
 * @return 0
 */
int aspn23_lcm_measurement_direction_2d_to_points_decode_cleanup(aspn23_lcm_measurement_direction_2d_to_points *p);

/**
 * Check how many bytes are required to encode a message of type aspn23_lcm_measurement_direction_2d_to_points
 */
int aspn23_lcm_measurement_direction_2d_to_points_encoded_size(const aspn23_lcm_measurement_direction_2d_to_points *p);

// LCM support functions. Users should not call these
int64_t __aspn23_lcm_measurement_direction_2d_to_points_get_hash(void);
uint64_t __aspn23_lcm_measurement_direction_2d_to_points_hash_recursive(const __lcm_hash_ptr *p);
int __aspn23_lcm_measurement_direction_2d_to_points_encode_array(
    void *buf, int offset, int maxlen, const aspn23_lcm_measurement_direction_2d_to_points *p, int elements);
int __aspn23_lcm_measurement_direction_2d_to_points_decode_array(
    const void *buf, int offset, int maxlen, aspn23_lcm_measurement_direction_2d_to_points *p, int elements);
int __aspn23_lcm_measurement_direction_2d_to_points_decode_array_cleanup(aspn23_lcm_measurement_direction_2d_to_points *p, int elements);
int __aspn23_lcm_measurement_direction_2d_to_points_encoded_array_size(const aspn23_lcm_measurement_direction_2d_to_points *p, int elements);
int __aspn23_lcm_measurement_direction_2d_to_points_clone_array(const aspn23_lcm_measurement_direction_2d_to_points *p, aspn23_lcm_measurement_direction_2d_to_points *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
